fremtind/jokul

.github/pull_request_template.md

Types is set in header. And github treats checkboxes as task to be done, so they way we used to did not make that much sense, as a pr will never be

docs(pr-template): remove type section, as the commit enforces type selection

---

package.json
packages/core/package.json
packages/portal/src/pages/Contribute/Contribute.tsx
packages/utils/package.json
packages/utils/src/internal/StoryTemplate.tsx
yarn.lock

affects: @fremtind/jkl-button-react, @fremtind/jkl-button, @fremtind/jkl-core,
@fremtind/jkl-footer-react, @fremtind/jkl-footer, @fremtind/jkl-grid-react, @fremtind/jkl-grid,
@fremtind/jkl-header-react, @fremtind/jkl-header, @fremtind/jkl-logo-react,
@fremtind/parcel-consumer-example, @fremtind/jkl-portal, @fremtind/jkl-radio-button-react,
@fremtind/jkl-radio-button, @fremtind/jkl-storybook, @fremtind/jkl-text-field-react,
@fremtind/jkl-text-field, @fremtind/jkl-typography-react, @fremtind/jkl-utils,
@fremtind/webpack-consumer-example
Make changes to the build order so that it is possible to initially build the project. 
What types of changes does your code introduce to Jøkul?
-   [x] 🐞 Bugfix
-   [ ] ✨ New feature
-   [ ] ⚠️ Breaking change
-   [ ] 🤔 Other (Please specify):
-   [x] I …

fix: fix build order on initial setup

---

packages/button-react/src/Button.stories.tsx
packages/footer-react/src/Footer.stories.tsx
packages/header-react/src/Header.stories.tsx
packages/typography-react/src/Typography.stories.tsx

affects: @fremtind/jkl-button-react, @fremtind/jkl-footer-react, @fremtind/jkl-header-react,
@fremtind/jkl-typography-react
After refactor style were removed from storybook, now its back

fix(storybook): fix style import in storybook

---

packages/accordion-react/src/Accordion.tsx
packages/accordion/accordion.scss
packages/accordion/example/index.tsx

affects: @fremtind/jkl-accordion-react, @fremtind/jkl-accordion
Replace the chevron svg in the accordion component with a styled DOM element
This fixes an issue with CI

feat(accordion): replace chevron svg with css

---

packages/bullet-list-react/example/index.tsx
packages/bullet-list-react/src/Li.tsx
packages/bullet-list-react/src/List.stories.tsx
packages/bullet-list-react/src/List.test.tsx
packages/bullet-list/bullet-list.scss

affects: @fremtind/jkl-bullet-list-react, @fremtind/jkl-bullet-list
Change implementation of bullet lists to use semantic nesting of elements, as used in plain HTML.
This might be a bit more verbose, but is more accessible, and makes more sense when using only the style package.
Before:
```jsx
<Ul>
<Li>Some element</Li>
<Li nested>Some nested element</Li>
</Ul>
```
Now:
```jsx
<Ul>
<Li>
Some element
<Ul>
<Li>Some …
```

feat(bullet-list): enable semantic nesting in bullet lists@

---

packages/core/src/typography/root.scss

Implement the font using `@font-face`. 
This enables us to use `font-weight: bold` to get Akkurat Pro instead of Akkurat Light Pro. Currently it looks for the locally installed fonts (which does not work in Safari), but it is trivial to use a url instead when we distribute the font later.
**Please note:** All styles specifying `font-family: "Akkurat Pro"` should be changed to use `font-weight: bold`.

feat(core): implement font-face for better font handling

---

packages/button/README.md
portal/src/pages/components/button.tsx
portal/src/presentation/markdownRenderer.ts

Add a renderer for `markdown-react` to use our styles for typographic elements when displaying the `readme.md` file for a component.
Currently handles paragraphs (not lead), headings and bullet lists (turns all lists into unordered lists)

feat(portal): make markdown parser use our components

---

.travis.yml

Make travis build docs before deploy
Not 100% sure if this will work, but we'll see!

fix(ci): force build:docs before deploy

---

portal/gatsby-browser.js
portal/src/components/Header.scss
portal/src/components/Layout.scss
portal/src/components/Menu.scss

Use correct imports from `jkl-core`. Build on master now fails because of these imports in the Portal.

fix(portal): use correct sass imports in portal components

---

.github/pull_request_template.md
README.md
gulpfile.js
packages/checkbox-react/example/index.tsx
packages/checkbox/example/index.tsx
packages/footer-react/example/index.tsx
packages/footer/example/index.tsx

affects: @fremtind/jkl-checkbox-react, @fremtind/jkl-checkbox, @fremtind/jkl-footer-react,
@fremtind/jkl-footer
It used to just autoprefix the minified css files. Now it does it to both normal css and css.min files. Also excludes scss files in example to be compiled.
-   [ ] I have read the [CONTRIBUTING]("../guides/Contribute.md") doc

fix(css): output prefixed css files, fix import from core

---

packages/bullet-list-react/src/BulletList.tsx
packages/bullet-list/bullet-list.scss
packages/bullet-list/example/index.html
portal/src/presentation/markdownRenderer.ts

affects: @fremtind/jkl-bullet-list, @fremtind/portal
Remove unneeded import of `paragraph.css`. A class name for paragraph style (like `jkl-p` or `jkl-lead`) will now have to be applied to the list element along with `jkl-bullet-list`.

fix(bullet-list): remove import of paragraph styles and align spacing

---

packages/core/headings.scss
packages/core/paragraphs.scss

Add spacing after typographic elements (headers and paragraphs), to restore some air to layouts.
The exact spacing used should be looked at by the designers. As of now, there is no guidelines for this in the DS.

feat(core): add spacing after typographic elements

---

portal/src/components/Menu/Menu.tsx

make `Menu` component use `Location` (from `@reach/router`) for getting url path instead of using the `window` object.
The Menu component is a bit ugly now. We might consider refactoring sometime

fix(portal): make portal build correctly

---

packages/dropdown-react/README.md
packages/dropdown-react/example/index.html
packages/dropdown-react/example/index.scss
packages/dropdown-react/example/index.tsx
packages/dropdown-react/package.json
packages/dropdown/README.md
packages/dropdown/dropdown.scss

affects: @fremtind/jkl-dropdown-react, @fremtind/jkl-dropdown
Dropdown was place a little to low when no value were selected. Imports did not work on linux. Updated readmes to updated standard.

fix(dropdown): fixed minor placement issue, update documentation

---

packages/dropdown-react/example/index.tsx
packages/dropdown-react/src/Select.test.tsx
packages/dropdown-react/src/Select.tsx
packages/dropdown-react/src/index.ts
packages/dropdown/dropdown.scss
packages/dropdown/example/index.html
packages/dropdown/example/index.scss
packages/dropdown/example/index.ts
packages/dropdown/package.json
portal/src/examples/DropdownExample.tsx

affects: @fremtind/jkl-dropdown-react, @fremtind/jkl-dropdown
Add a dropdown version based on the `<select>` element, to be used on mobile and other places where the normal dropdown does not fit/cannot be used.

Add <select>-based dropdown

---

packages/message-box/message-box.scss

affects: @fremtind/jkl-message-box
Fix issue where messageboxes is bigger than container.

fix(message-box): dont let it grow beoynd its size

---

packages/dropdown-react/example/index.scss
packages/dropdown-react/example/index.tsx
packages/dropdown-react/src/Dropdown.tsx
packages/dropdown/dropdown.scss

Make dropdown actually use passed className prop. Align label and value far left as per new sketches.

fix(dropdown): make dropdown use passed classname prop

---

packages/radio-button/radio-button.scss

Styles the fieldset of `jkl-radio-button.choice` to match other field labels in the design system

fix(radio-button): style fieldset and label correctly

---

packages/text-input/text-input.scss

Specify `-webkit-appearance: none` on text input fields to ensure bottom border is shown in mobile Safari 🤷‍♂️

fix(text-input): show underline in mobile Safari

---

portal/src/components/Menu/Menu.scss

Align the GitHub and Figma links at the bottom of the menu with the top-level items.
These items and their icons felt like they were too far to the right, especially when the last menu accordion was not open.

fix(portal): align github and figma links in menu

---

packages/core/src/utils/tabListener.ts

Make tabListener listen only for the `Tab` key when deciding when to turn on keyboard navigation highlighting. Until now it has also listened to the arrow keys, which causes unwanted behavior e.g. when moving the cursor/selecting text in a text field.

fix(tablistener): only listen to Tab key, not arrows

---

packages/datepicker-react/package.json
packages/datepicker-react/src/DatePicker.tsx
packages/datepicker/datepicker.scss

Use the `Select` component from `jkl-dropdown` for the month dropdown, instead of a custom styled `select` element.
This adds some weight to the component, since it must now depend on both `jkl-dropdown` and `jkl-dropdown-react`, but it keeps the style in sync.

feat(datepicker-react): use select from jkl-dropdown for month picker

---

packages/datepicker-react/src/DatePicker.tsx
portal/src/examples/DatepickerExample.tsx

Add `type="button"` to datepicker toggle to stop it from submitting any forms it is part of when toggled.

fix(datepicker-react): stop datepicker from submitting forms when opened

---

packages/datepicker-react/package.json
yarn.lock

affects: @fremtind/jkl-datepicker-reac
Upgrade to latest version of @nrk/core-datepicker. This fixes bug where custom month/day names are not shown correctly.

chore(datepicker-react): update @nrk/core-datepicker to latest

---

packages/accordion/package.json
packages/bullet-list/package.json
packages/button/package.json
packages/card/package.json
packages/checkbox/package.json
packages/core/package.json
packages/datepicker/package.json
packages/divider-line/package.json
packages/dropdown/package.json
packages/field-group/package.json
packages/hamburger/package.json
packages/loader/package.json
packages/logo/package.json
packages/message-box/package.json
packages/radio-button/package.json
packages/text-input/package.json
packages/toggle-switch/package.json

affects: @fremtind/jkl-accordion, @fremtind/jkl-bullet-list, @fremtind/jkl-button,
@fremtind/jkl-card, @fremtind/jkl-checkbox, @fremtind/jkl-core, @fremtind/jkl-datepicker,
@fremtind/jkl-divider-line, @fremtind/jkl-dropdown, @fremtind/jkl-field-group,
@fremtind/jkl-hamburger, @fremtind/jkl-loader, @fremtind/jkl-logo, @fremtind/jkl-message-box,
@fremtind/jkl-radio-button, @fremtind/jkl-text-input, @fremtind/jkl-toggle-switch
The `clean` script only removed build javascript files and types. Update the script in style packages to also remove generated css files.
-   [x] I have added tests that prove my fix is effective or that my feature …

chore: make clean script clean generated css files

---

packages/loader-react/src/Loader.test.tsx
packages/loader-react/src/Loader.tsx

affects: @fremtind/jkl-loader-react
Add the possibility to pass a `className` prop to the `Loader` component. Can be useful for positioning with the `jkl-spacing` classes, for example.

feat(loader-react): make loader accept className as prop

---

packages/datepicker-react/example/index.tsx
packages/hamburger-react/example/index.tsx
portal/src/examples/ButtonExample.tsx
portal/src/examples/DropdownExample.tsx
portal/src/examples/HamburgerExample.tsx

affects: @fremtind/jkl-datepicker-react, @fremtind/jkl-hamburger-react, @fremtind/portal
The alerts in many of the examples are so annoying! This replaces all of them with `console.log`s 🎉

fix: remove all alerts from examples

---

packages/dropdown-react/example/index.tsx
packages/dropdown-react/src/Dropdown.tsx
packages/dropdown-react/src/Select.test.tsx
packages/dropdown-react/src/Select.tsx
packages/dropdown-react/src/SelectValuePair.test.ts
packages/dropdown-react/src/SelectValuePair.ts

Let `Dropdown` and `Select` accept value/label pairs in addition to `string`s as items. This matches native behaviour better, and closes #362 .
The form of the value/label pairs is defined as a type (`SelectValuePair`) in `SelectValuePair.ts` and can be imported from there. Both `Dropdown` and `Select` accepts an array of _either_ `string`s or `SelectValuePair`s as the `items` prop.
```ts
type SelectValuePair = {
value: string;
label: string;
};
```
```ts
interface Props {
...
items: …
```

Dropdown value pairs

---

packages/checkbox/checkbox.scss
packages/radio-button/radio-button.scss

affects: @fremtind/jkl-checkbox
Checkboxes were spaced to close together when stacked vertically. This gives them the same spacing as radio buttons.

fix(jkl-checkbox): give checkboxes correct vertical spacing when stacked

---

packages/accordion/accordion.scss
packages/button/button.scss
packages/checkbox/checkbox.scss
packages/core/links.scss
packages/core/variables/_colors.scss
packages/dropdown/dropdown.scss
packages/hamburger/hamburger.scss
packages/radio-button/radio-button.scss
packages/table/table.scss
packages/text-input/text-input.scss
packages/toggle-switch/toggle-switch.scss

affects: @fremtind/jkl-accordion, @fremtind/jkl-button, @fremtind/jkl-checkbox, @fremtind/jkl-core,
@fremtind/jkl-dropdown, @fremtind/jkl-hamburger, @fremtind/jkl-radio-button, @fremtind/jkl-table,
@fremtind/jkl-text-input, @fremtind/jkl-toggle-switch
The colors currently used for errors and focus are not WCAG compliant. This PR implements the new red/blue color variants defined in the style library.
Closes #390, closes #393 

fix(core): add and use wcag-compliant error/focus colors

---

packages/accordion/accordion.scss
packages/accordion/example/index.tsx

ISSUES CLOSED: #397
Use div instead of span to ensure that padding works consistently (i.e. block level element).
Another alternative is to use CSS in the accordion package.

fix(accordion-react): use div to contain title text to avoid inline bug

---

portal/src/components/Menu/Menu.scss

Reset the style of the accordions used in the main menu. The new style broke them completely.

fix(portal): reset style of accordions in main menu

---

packages/core/labels.scss
packages/core/src/index.ts
packages/core/variables/_font-size.scss
packages/datepicker-react/example/index.tsx
packages/dropdown-react/example/index.tsx
packages/field-group-react/example/index.tsx
packages/field-group-react/src/FieldGroup.tsx
packages/radio-button-react/example/index.tsx
packages/text-input-react/example/index.scss
packages/text-input-react/example/index.tsx
packages/text-input-react/src/TextArea.tsx
packages/text-input-react/src/TextField.tsx
packages/text-input/text-input.scss
packages/typography-react/src/SupportLabel.tsx
portal/src/examples/DatepickerExample.tsx
portal/src/examples/DropdownExample.tsx
portal/src/examples/TextAreaExample.tsx
portal/src/examples/TextFieldExample.tsx

- Change the names of the label size variants to `small`, `medium` and `large`, and make the `medium` size default (was `large`) to ease transition from old version.
- Add the possibility to force compact ("mobile") mode on the `TextField`, `TextArea` and `FieldGroup` components.
I'd really like to get this in today's release, since I lied about there not being big changes in the forum yesterday 😅 This should make the transition a bit less jarring. There should be no breaking changes …

Add compact mode for text fields

---

packages/core/labels.scss
packages/text-input-react/example/index.scss
packages/text-input-react/example/index.tsx
packages/text-input-react/src/TextField.tsx
packages/text-input/README.md
packages/text-input/text-input.scss
packages/typography-react/src/Label.tsx
portal/src/examples/TextFieldExample.tsx

Implement inline (in-text) version of `TextField` as discussed in #426 . This also adds a screenreader-only version of the label so it can be hidden without creating an empty `<label>` element.
affects: @fremtind/jkl-core, @fremtind/jkl-text-input-react, @fremtind/jkl-text-input,
@fremtind/jkl-typography-react
- Repurposes the existing `inline` prop (which had no real effect) for this, which strictly speaking breaks current functionality; We should give a heads-up to the teams before …

feat(text-field): implement in line version of TextField

---

packages/dropdown-react/README.md
packages/dropdown-react/src/Dropdown.tsx
packages/dropdown-react/src/Select.tsx

affects: @fremtind/jkl-dropdown-react
- Add documentation about the dropdown packages being deprecated
- Throw warnings in dev when using the deprecated components

Document deprecation of the Dropdown packages

---

packages/typography-react/src/SupportLabel.tsx

affects: @fremtind/jkl-typography-react
ISSUES CLOSED: #490
Fix a tiny capitalization bug.

fix(typography-react): remove capitalization of className for helpLabel

---

packages/checkbox-react/src/Checkbox.test.tsx

affects: @fremtind/jkl-checkbox-react
Stop one of the tests in `Checkbox` from complaining about being a controlled component without an `onChange` method...

test(checkbox-react): make test stop complaining about missing prop

---

packages/datepicker/datepicker.scss

Make sure the year value in the datepicker (for selecting year in the open state) is left-aligned as per the design sketches.

fix(datepicker): fix alignment of year value in picker

---

packages/datepicker-react/src/DatePicker.test.tsx
packages/datepicker-react/src/DatePicker.tsx

date picker should fire onChange when a valid date is entered into the input field

fix(datepicker-react): datepicker fire onChange on edit

---

packages/button/button.scss
packages/checkbox/checkbox.scss
packages/core/README.md
packages/core/headings.scss
packages/core/labels.scss
packages/core/mixins/_helpers.scss
packages/core/paragraphs.scss
packages/radio-button/radio-button.scss
packages/select/select.scss
packages/text-input/text-input.scss

For å lette implementasjonen av kompakt modus i løsninger som f.eks. Flyt, legger denne PR'en til støtte for å sette kompakt modus globalt:
Ved å sette attributten `data-compactlayout` på et HTML-element vil alle Jøkul-komponenter inne i dette elementet vises i kompakt modus. Man kan dermed sette kompakt modus på hele applikasjonen med `<body data-compactlayout>`, eller bare på en del av den med f.eks. `<aside data-compactlayout>`.
Se #494 for diskusjon av for- og bakdeler med dette.
affects: …

feat: add support for global compact mode

---

packages/select-react/example/index.tsx
packages/select-react/src/NativeSelect.test.tsx
packages/select-react/src/NativeSelect.tsx
packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx

`Select` and `NativeSelect` no longer requires an initial value to function.
ISSUES CLOSED: #500

fix(select-react): make Select & NativeSelect useable as uncontrolled

---

packages/core/reset.scss
packages/field-group-react/src/FieldGroup.tsx
packages/field-group/field-group.scss

Move styling of fieldset from `jkl-field-group` to `core/reset.css`, to remove hidden dependency in `jkl-radio-button-react`

feat(core): move fieldset styling to reset.css

---

packages/bullet-list-react/README.md
packages/bullet-list-react/src/BulletList.tsx
packages/bullet-list-react/src/BulletListItem.tsx
packages/bullet-list/README.md

affects: @fremtind/jkl-bullet-list-react
Adds a deprecation warning when using BulletList, as well as changes to the readme.
Connected to #505 

docs: add deprecation warning for usage of BulletList

---

packages/button/button.scss
packages/checkbox/checkbox.scss
packages/core/headings.scss
packages/core/labels.scss
packages/core/mixins/_helpers.scss
packages/core/paragraphs.scss
packages/radio-button/radio-button.scss
packages/select/select.scss
packages/text-input/text-input.scss

affects: @fremtind/jkl-button, @fremtind/jkl-checkbox, @fremtind/jkl-core,
@fremtind/jkl-radio-button, @fremtind/jkl-select, @fremtind/jkl-text-input
Refactor to standard naming convention for css

refactor: rename compactMode to compact-mode

---

packages/select-react/example/index.html
packages/select-react/src/Select.tsx

closes #531
Fixes a bug where an empty value for `<Select />` resulted in the outer wrapper shrinking in height.

(select-react) fix: fix visual jump when value is empty

---

packages/divider-line-react/example/index.tsx

affects: @fremtind/jkl-divider-line-react
Import `core.min.css` in the dev example so that the divider actually shows up in Chrome.
Closes #532

docs(divider-line-react): import core style in example

---

portal/src/pages/style.scss

The portal tried to load the webfonts from `/fonts` instead of `/jokul/fonts` since scss-files don't get path-prefixed. By specifying a relative path in the scss it sort of works, even though the font files end up in two different folders during the Gatsby build 🤔
There might be a more elegant solution to this, but the portal is live in Times New Roman right now, so time is sort of of the ssence here 😅

fix(portal): use prefix path when loading webfonts

---

package.json
yarn.lock

1. Typescript 3.7
- Inneholder litt nytt snask som
- Optional chaning
- Nullish Coalescing
- Bedre støtte for `never` typen
- Les mer https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html
2. React med typedefinisjoner
- React typene og React-dom typene er litt kranglefanter, så er nå satt at vi resolver til versjonen satt av react typen, selvom react-dom kanskje ber om en annen. Dette gir litt hodeverk for yarn, som ikke heeeelt henger med. Det betyr at man kanskje må slette node_modules og yarn.lock og gjøre `yarn` på nytt for å få ting på plass igjen
-   [ ] I have added tests that prove my fix is effective …

chore(core): upgrade to typescript 3.7 and update react with types

---

.eslintrc.js
package.json
yarn.lock

affects: @fremtind/jkl-typography-react
I dagens så bruker vi prettier til å gjøre ting mer eller mindre pent og eslint til å gjøre ting mer eller mindre riktig. Dette er igrunn sider av samme sak, og eslint kan fint gjøre hele jobben ved å gi linteren tilgang på prettier-pluginen. Det gjør at vi kan fjerne en del script og shave et millisekund eller to av bygg og commit osv. Legger man sammen flere millisekund, så blir det for mange millisekund, og det kan bli sekunder etter hvert. I know math. 
-   [ ] I have added necessary documentation (if …

chore(lint): use eslint to perform prettier, cleans up pkgjson

---

.github/workflows/deploy.yml
.github/workflows/test.yml
package.json
yarn.lock

run test lint and typecheck in paralell
Dagens actions _KAN_ velge nyere versjoner av våre dependencies enn det som er utviklet mot lokalt. Med denne endringen så vil lock-fila bli respektert. Kjører også lint-test og typecheck i paralell.

chore(ci): force use of lockfile on ci

---

packages/webfonts/webfonts.scss

affects: @fremtind/jkl-webfonts
Update the local font names in the `@font-face` rules to work with other variants than regular. Should restore bold/italic styles when on a computer that has Fremtind Grotesk installed.

fix(webfonts): update @font-face rules to handle locally installed fonts

---

packages/accordion-react/src/AccordionItem.test.tsx
packages/accordion-react/src/AccordionItem.tsx

Add support for custom className on the `AccordionItem` component.
Closes #569

feat(accordion-react): add support for custom className on AccordionItem

---

packages/select/select.scss

ISSUES CLOSED: #572
Stop the native dropdown toggle button from showing in IE11.

fix(select): stop native arrow from showing in IE11

---

packages/toggle-switch-react/src/ToggleSwitch.tsx
packages/toggle-switch/toggle-switch.scss

affects: @fremtind/jkl-toggle-switch-react, @fremtind/jkl-toggle-switch
Remove the usage of `jkl-p` in the toggle switch label to get rid of bottom margin.

fix(toggle-switch): fix formatting of toggle switch label

---

portal/src/components/Example/Example.scss
portal/src/components/Menu/Menu.scss

`@include font-size` caused an error when building the portal. The mixin got deleted in #591.

fix(portal): fix usage of deleted mixin

---

.github/workflows/test.yml

The greenkeeper branches keep waiting for CI because the script only runs on "base" branches without slashes in the name. This updates the trigger to the default (`"**"`) so that it will run on `greenkeeper/**`-branches as well.

chore(ci): run CI script on all branches (also with slashes)

---

packages/text-input/text-input.scss

ISSUES CLOSED: #611
The line-height between text and line in text-area when set to compact is too small. 
Setting the line-height from 2 to 3 will fix it.
Earlier it made the line-height for desktop version too big. I didn't get this bug this time, but it might occur on other screens. I tested with chrome and firefox.

fix(text-input): change to bigger line-height

---

portal/src/components/Menu/links.ts

closes: #655 
Fjern den tomme "Grunnleggende"-kategorien fra hovedmenyen i portalen

docs(portal): remove empty category from main menu

---

packages/list-react/documentation/Example.tsx
packages/list-react/documentation/List.mdx
packages/list/list.scss

closes #647, closes #650 
Et lite avvik fra designet i Figma:
Padding på venstre side av listen måtte være `layout-spacing--small` (24px) for at punktene ikke skulle ligge bittelitt til venstre for resten av teksten på siden. Det neste steget ned på skalaen vår er 16px og det ble for lite. Fått ok fra @Murstam på det.
---
Ellers skal alt være riktig. Samt at screen reader nå ikke leser opp bullet, men den leser fortsatt siffer foran nummerert liste så for det første punktet i en liste på fire med innhold "tekst" blir det lest opp "1 tekst 1 av 4". Regner med dette er riktig siden det nå bare er et \<ol>-element med `list-style: decimal`.
Endret også litt på dokumentasjonen slik jeg følte ble naturlig.
-   [x] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONT …

Update list to new design

---

packages/core/links.scss

Lenkene våre har sett rare ut etter bytte til ny font og nye avsnittstiler. Understreken ligger veldig langt nede, og nærmere linjen under enn lenken den er en del av:
Foreslår å ta vekk paddingen over og under lenketeksten som er der i dag, og samtidig legge på bittelitt padding på sidene, slik at hovereffekten ikke "kutter av" de ytterste bokstavene:
Det er sikkert plass til en piksel eller to med padding over/under dersom man vil ha et enda luftigere uttrykk.

fix(links): adjust padding around links for new font

---

packages/datepicker-react/src/DatePicker.test.tsx

closes: #705 
Regelen for `form-field-multiple-labels` er disabled: 
Får kun feilmeldingen på extended-variant av datepicker. Den har tilsynelatende ikke flere labels, usikkert hvorfor man får den beskjeden. Axe accessibility gir ikke samme beskjed i browser. Skjermleser leser ikke opp noe rart (dog kun testet med voiceover i chrome)

test(datepicker): add a11y-tests

---

packages/accordion/accordion.scss
packages/button/button.scss
packages/checkbox/checkbox.scss
packages/datepicker/datepicker.scss
packages/divider-line/divider-line.scss
packages/hamburger/hamburger.scss
packages/message-box/message-box.scss
packages/radio-button/radio-button.scss
packages/select/select.scss
packages/text-input/text-input.scss
packages/toggle-switch/toggle-switch.scss

affects: @fremtind/jkl-accordion, @fremtind/jkl-button, @fremtind/jkl-checkbox,
@fremtind/jkl-datepicker, @fremtind/jkl-divider-line, @fremtind/jkl-hamburger,
@fremtind/jkl-message-box, @fremtind/jkl-radio-button, @fremtind/jkl-select,
@fremtind/jkl-text-input, @fremtind/jkl-toggle-switch
Flytter alle stilendringer for kompakt- og mobilversjon til slutten av komponentens stil, etter eventuelle varianter (som `--active`, `--secondary`, etc.). Dette gir ryddigere css etter kompilering, og reduserer risikoen for at vi overskriver allerede definerte regler.
Fjerner også all bruk av de responsive tekststil-hjelpeklassene til fordel for de spesifikke, siden de responsive introduserer en skjult `@include small-device`. Se nyeste blogginnlegg på Confluence for mer diskusjon rundt det.
-   [x] I …

refactor: clean up scss for mobile and compact versions of components

---

jest/setupTests.ts
packages/datepicker-react/src/DatePicker.test.tsx

Flytte `expect.extend(toHaveNoViolations)` til `setupTests.ts` slik at den ikke må repeteres i hver eneste `.test.tsx`-fil.

chore(jest-axe): move repeated setup to global

---

packages/accordion-react/src/AccordionItem.test.tsx

Add missing a11y-test for AccordionItem
Testet med VoiceOver samtidig

test(accordion-item): add a11y-test

---

packages/button-react/documentation/Example.tsx
packages/button-react/documentation/buttons.mdx
packages/button-react/documentation/index.scss
packages/button-react/package.json
packages/button-react/src/Button.tsx
packages/button/button.scss

affects: @fremtind/jkl-button-react, @fremtind/jkl-button
Legger til invertert fargemodus for knappene, til bruk på mørke bakgrunner. Fikser også en bug der `PrimaryButton` har hvitt omriss i stedet for svart.
Ønsker tilbakemeldinger fra design på om en ren invertering er veien å gå. Et konkret brukseksempel er redigering i de mørke kortene i Flyt.

feat(button): add inverted color mode for buttons

---

packages/text-input/text-input.scss

Fix placeholder font weight to match design in Figma.
Placeholder _almost_ looks like input when set to bold.

refactor(text-input): set placeholder font weight to normal

---

packages/button-react/documentation/Example.tsx
packages/select-react/documentation/Example.tsx
packages/text-input-react/documentation/Example.tsx
packages/toggle-switch-react/README.md
packages/toggle-switch-react/documentation/Example.tsx
packages/toggle-switch-react/src/ToggleSwitch.test.tsx
packages/toggle-switch-react/src/ToggleSwitch.tsx
packages/toggle-switch/toggle-switch.scss
portal/src/components/Menu/Menu.tsx

affects: @fremtind/jkl-toggle-switch-react, @fremtind/jkl-toggle-switch
Change the ToggleSwitch component to an implementation using a `<button>` with the `aria-pressed` attribute indicating toggled state. This is best practice according to W3C, and makes screenreaders announce the button as a toggle button rather than as a checkbox.
`checked` prop is replaced by `pressed`, `onChange` prop is replaced by `onClick`
Closes #726 
We shouold consider whether we want to let the …

feat(toggle-switch): change toggle switch to button element (from input)

---

packages/text-input-react/src/ActionTextField.test.tsx
packages/text-input-react/src/BaseInputField.test.tsx
packages/text-input-react/src/InlineTextField.test.tsx
packages/text-input-react/src/TextArea.test.tsx
packages/text-input-react/src/TextField.test.tsx

Add a11y tests
Deaktiverte regelen `label` for BaseInputField. Label er tatt bort med vilje. Ønsket bruksmønster er dokumentert under "[Særskilt bruk](https://github.com/fremtind/jokul/tree/master/packages/text-input-react#særskilt-bruk)" i pakken.

test(text-input-react): add a11y-tests

---

packages/toggle-switch-react/src/ToggleSwitch.test.tsx

affects: @fremtind/jkl-toggle-switch-react
Tested med VoiceOver: Resulterte i et funn om at toggle switches (toggle button som det tydeligvis egt heter) skal være et button-element med attribute `aria-pressed="true/false". Issue blir opprettet.

test(toggle-switch-react): add a11y-tests

---

packages/radio-button-react/documentation/Example.tsx
packages/radio-button-react/src/RadioButtonOption.tsx
packages/radio-button-react/src/RadioButtons.tsx
packages/radio-button/radio-button.scss

affects: @fremtind/jkl-radio-button-react, @fremtind/jkl-radio-button
Implement dark mode for radio buttons. This is not run by any designers, but is probably not a controversial solution 😅

feat(radio-button): add inverted mode

---

packages/list-react/documentation/Example.tsx
packages/list-react/documentation/List.mdx
packages/react-hooks/documentation/hooks.mdx
portal/src/components/Header/Header.tsx

affects: @fremtind/jkl-list-react, @fremtind/jkl-react-hooks
Fix incorrect heading levels on some documentation pages/examples.

docs(portal): correct heading levels in component docs

---

packages/text-input-react/src/Icons/IconClear.tsx
packages/text-input-react/src/Icons/IconSearch.tsx
packages/text-input/text-input.scss

affects: @fremtind/jkl-text-input-react, @fremtind/jkl-text-input
Tweaks size and position of the action icon in `ActionTextField`, and adds keyboard focus indication to it in the form of blue focus color.
We should probably find a better way of indicating focus state, but this is better than nothing, and was easy to implement via CSS.

feat(text-input): tweak action icon placement and add focus state

---

packages/datepicker-react/package.json
packages/datepicker-react/src/CalendarIcon.tsx
packages/datepicker-react/src/DatePicker.test.tsx
packages/datepicker-react/src/DatePicker.tsx
packages/datepicker/datepicker.scss
yarn.lock

affects: @fremtind/jkl-datepicker-react, @fremtind/jkl-datepicker
Calendar will no longer open when the input is focused, but instead when a button is pressed. This should address most/all issues in #593, #773 and #774.
Closes #593, closes #773, closes #774

feat(datepicker): add button to open datepicker calendar

---

portal/src/components/Header/header-react/src/header.tsx
portal/src/components/Header/header/header.scss
portal/src/components/Layout/layout-react/src/Layout.tsx
yarn.lock

Greatly simplify the structure of the `Header` component. It seems like the `Card` component from Jøkul was used as a basis, and a lot of the props/functionality from that was still implemented.
I realize I've also made it a bit less generalized, but I don't think we need to implement patterns for headers we don't really _have_ a pattern for yet.
This is not directly related to this PR, but I'm not sure that i like this architecture:
I presume it is meant to approximate the structure of the …

Refactor portal header

---

packages/core/src/index.ts
packages/core/src/utils/breakpoints.ts
packages/core/src/utils/index.ts
packages/react-hooks/documentation/Example.tsx
packages/react-hooks/documentation/ScreenExample.tsx
packages/react-hooks/documentation/hooks.mdx
packages/react-hooks/package.json
packages/react-hooks/src/index.ts
packages/react-hooks/src/useScreen/state.ts
packages/react-hooks/src/useScreen/useScreen.ts

affects: @fremtind/jkl-core, @fremtind/jkl-react-hooks
Eksponerer våre breakpoints i javascript kontekst som en hook.
Per nå eksponerte jeg bare breakpointene i en ts fil. Kan også eksportere fra scss til js, men det virker til å være funksjonalitet lagt inn i webpack og ikke standard funksjonalitet. Virker ikke med parcel ut av boksen. 
Kanskje dette burde kommet fra Figma?
Alternativ implementasjon er å sette content på body elementet i scss, og plukke opp den derifra isteden for å bruke …

feat(react-hooks): add hook for responsivity in js

---

packages/datepicker-react/src/DatePicker.test.tsx
packages/datepicker-react/src/DatePicker.tsx

📥 Proposed changes
Handle "resetting" of the datepicker when the user clears the text input. Will call onChange with
undefined in those cases.
**NB!** This is a **BREAKING CHANGE**, as the `onChange` method passed as a prop to `Datepicker` must now accept a value of `undefined` in addition to a `Date` object:
```ts
onChange?: (date?: Date) => void;
```
Closes #801

fix(datepicker-react): add handling of empty dates in datepicker

---

packages/button/button.scss

Fix bug where compact version of `TertiaryButton` had `min-width` even if it should not.
Closes #802

fix(button): unset min-width on compact tertiary button

---

packages/accordion/accordion.scss

affects: @fremtind/jkl-accordion
Fixes an issue where accordion does not take up the full width of its container, causing it to grow/shrink in width as it reveals/hides its content.

fix(accordion): make accordion fill entire width of container

---

packages/table/table.scss

affects: @fremtind/jkl-table
is it then really a bug? what even is a bug? is zero a number? is 2 a prime?
Changed the styling of jkl-table__row into something that IE 11 can understand.

fix(table): fix bug causing shadow not to be drawn in IE 11

---

gulpfile.js
package.json
packages/checkbox-react/src/Checkbox.test.tsx
packages/react-hooks/documentation/AnimationExample.tsx
packages/react-hooks/documentation/MutationObserverExample.tsx
packages/table-react/src/TableData.tsx
packages/toggle-switch-react/src/ToggleSwitch.test.tsx
yarn.lock

typescript 3.8, nessestiate an upgrade of babel, prettier and eslint to use new features. Prettier is a major upgrade, but almost no changes to our project, as prettier has aligned their defaults pretty much with our settings.
The somewhat random changes here is due to the upgrade of prettier 2. To avoid getting these updates in an unreleated PR, `eslint --fix` has been executed on the entire project.
Also, I think its about time we say that Jokul isnt 0.0.0, so howabout 1.0.0? …

feat: update typescript, prettier and babel

---

.github/workflows/test.yml

Remove the GitHub action for testing/linting Greenkeeper branches, since Greenkeeper is no more..

chore: remove greenkeeper-specific github action

---

packages/logo-react/src/Logo.tsx

affects: @fremtind/jkl-logo-react
IE11 does not support having CSS transform svg. However it supports
the transform attribute directly on the element.
Add hard coded transforms for rotating logo symbol in IE. These are overridden by CSS.

fix(logo): add transforms for logo symbol support

---

packages/text-input/text-input.scss

Hotfix for wrong height on compact text inputs
Closes #877

fix: use correct height for compact text inputs

---

portal/gatsby-browser.js
portal/src/components/Typography/FormatProvider.tsx
portal/src/components/Typography/Typography.tsx
portal/src/components/Typography/index.ts
portal/src/components/Typography/typography.scss

Add back code highlighting (both inline and for blocks) that we lost when moving from markdownRemark to mdx

feat(formatting): add code highlighting to mdx parser

---

portal/src/components/Typography/Typography.tsx

Fixes a bug in the `CodeBlock` typographic component in the Portal, that caused page builds to fail if a Markdown code block had no assigned language.

fix(codeblock): account for code blocks without language

---

packages/datepicker-react/documentation/Example.tsx
packages/datepicker-react/src/DatePicker.tsx
packages/select-react/documentation/Example.tsx
packages/select-react/src/NativeSelect.tsx
packages/select-react/src/Select.tsx
packages/text-input-react/documentation/Example.tsx

Adds `onFocus`and `onBlur` props to Select, NativeSelect and DatePicker.
Should close #886

Add missing event handlers to Select and DatePicker

---

packages/core/links.scss
packages/typography-react/documentation/Example.tsx
packages/typography-react/src/Link.tsx

affects: @fremtind/jkl-core, @fremtind/jkl-typography-react
ISSUES CLOSED: #905
Ettersom vi har funnet at http/https-sjekk på `.jkl-link` kan være for aggressivt, er denne sjekken byttet ut med `.jkl-link--external` for å få samme styling.

feat(links): add external prop and style to links

---

packages/icon-button/icon-button.scss

affects: @fremtind/jkl-icon-button
Specify the height of the icon in `IconButton` to avoid alignment issues like the one illustradet below.
Before: uneven spacing
After: even spacing

fix(icon-button): specify height of icon to correct alignment

---

packages/portal-components/package.json
packages/portal-components/src/ComponentExample.tsx
yarn.lock

Use unique field names in the `ComponentExample` component, to avoid issues when several examples with the same variable names are used on the same page.
ISSUES CLOSED: #920
affects: @fremtind/jkl-portal-components

fix(example-knobs): use unique field names on knobs

---

packages/checkbox-react/documentation/Checkbox.mdx
packages/checkbox-react/documentation/Example.tsx
packages/checkbox-react/documentation/index.tsx
packages/checkbox-react/src/Checkbox.tsx
packages/checkbox/checkbox.scss

add support for inverted variant, and tentative support for global dark mode
This adds support for inverted mode using the `inverted` prop, as in the other components. However, I've also tried an implementation using CSS custom properties, that coexists with the other solution:
If the browser supports CSS custom properties, and `data-theme` is set to `light` or `dark` on a containing element on the page, the custom properties are used. Otherwise, the values in the `--inverted` variant of the …

Add inverted mode to checkbox (plus POC of global dark mode)

---

packages/text-input-react/documentation/TextAreaExample.tsx
packages/text-input-react/documentation/TextInputExample.tsx
packages/text-input-react/src/BaseInputField.tsx

closes #927 
La til onKeyDown, onKeyUp og onKeyPress til interface.
Jeg la også til en console.log i eksemplene.

feat(text-input-react): add functionality to pass onKey events

---

packages/radio-button-react/README.md
packages/radio-button-react/src/RadioButtons.tsx

I portalen står det skrevet at en kan bruke radiobuttons uten forhåndsvalg, men ingen eksempler på hvordan. Siden det er en teknisk detalj bør det kanskje heller stå i readme-filen, men da må i såfall teksten i portalen ha med eksempler eller omformuleres.
Denne PR'en setter `selectedValue` som optional for å muliggjør at radiobutton kan stå unchecked.
Løsningen på hvordan jeg klarte å bruke radiobutton uten forhåndsvalg var å la valgene stå tomme uten en "default"-verdi, men allikevel la …

make selectedValue optional

---

packages/core/src/components/Label.tsx
packages/core/src/components/Link.tsx
packages/core/src/components/SupportLabel.test.tsx
packages/core/src/components/SupportLabel.tsx
packages/core/src/components/index.ts
packages/core/src/index.ts
packages/datepicker-react/package.json
packages/datepicker-react/src/DatePicker.tsx
packages/field-group-react/src/FieldGroup.tsx
packages/select-react/src/NativeSelect.tsx
packages/select-react/src/Select.tsx
packages/text-input-react/README.md
packages/text-input-react/src/TextArea.tsx
packages/text-input-react/src/TextInput.tsx
packages/typography-react/src/Label.tsx
packages/typography-react/src/Link.tsx
packages/typography-react/src/SupportLabel.tsx
portal/src/components/Info/WebComponentInfo.tsx
portal/src/components/Typography/FormatProvider.tsx
yarn.lock

Flytt de gjenværende komponentene i `jkl-typography-react` til `jkl-core` og merk de gamle utgavene som utgått.
Stilen til `Link`, `Label` og `SupportLabel`, samt typen for `LabelVariant`, ligger allerede i `jkl-core`. Det føles derfor mer naturlig å importere disse komponentene fra samme sted.
Closes #903

Flytt typografikomponentene

---

packages/text-input-react/src/BaseInputField.tsx

closes #947 
PR-en åpner for at man kan legge til custom className ved siden av `jkl-text-input__input`.

fix(BaseInputField): fix proper passing of className prop

---

package.json
packages/alert-message-react/README.md
packages/alert-message-react/src/AlertMessage.test.tsx
packages/alert-message-react/src/AlertMessage.tsx

Ettersom Pio hadde et godt forslag med å bruke mer deskriptive props knakk koblingen mellom prop og CSS-egenskap. Denne er nå fikset ved å lage et map mellom deskriptive navn og CSS-egenskaper.
Lagt til tester for å se at denne koblingen funker senere. 
Oppdatert litt utdatert dokumentasjon, og lagt til `test:watch` for ikke å klikke av å kjøre test runneren på nytt hele tiden 😅

Alert message fix

---

.github/workflows/release.yml

Fix a bug where continuous release always bumps version numbers. See https://github.com/actions/checkout/issues/217 

fix(ci): make git history available to release action

---

packages/typography-react/src/Label.tsx
packages/typography-react/src/Link.tsx
packages/typography-react/src/SupportLabel.tsx

Ensure that the deprecation warnings are only shown once, to avoid flooding the console during
development.
affects: @fremtind/jkl-typography-react

fix(typography-react): make deprecation warnings less intrusive

---

packages/button-react/src/Button.tsx
packages/button-react/src/index.ts
packages/text-input-react/src/BaseInputField.tsx
packages/text-input-react/src/TextArea.tsx
packages/text-input-react/src/TextInput.tsx
packages/text-input-react/src/index.ts

affects: @fremtind/jkl-button-react, @fremtind/jkl-text-input-react
will be used to extend interfaces with required props in BM
I BM utvider vi noen komponenter med større krav til props. Dette kan være obligatorisk tracking key til mixpanel i knapper. Men i dette tilfellet er det å legge til obligatorisk data-testautoid prop til bruk for TestComplete.
Eksponering av prop interfacene fra komponenter vil gjøre det enklere å extende disse til å ta flere props når komponenter blir definert internt i prosjekter.
-   [X] I have added necessary documentation …

feat: expose prop interface for textinput and button

---

packages/text-input-react/package.json
packages/text-input-react/src/TextArea.tsx
packages/text-input-react/src/TextInput.tsx
yarn.lock

Add missing `nanoid` dependency to `text-input-react`.

fix(text-input-react): add missing nanoid dependency

---

packages/datepicker/datepicker.scss

i miljøer hvor CSP er i bruk, og konfigurert til å blokkere inline CSS
vil stylingen av kalenderen i datepickeren feile.
Sett `display:block` statisk fra CSS-filen.

fix: fiks en bug hvor CSP vil blokkere inline CSS

---

portal/src/components/Layout/Layout.scss
portal/src/components/Layout/components/ThemeBG.scss

fixes issue in firefox where white background were not set
closes: #993

fix(portal): explicitly set background color

---

portal/src/components/Layout/Layout.scss

fix of bg color in firefox caused regression in dark mode.

fix: fix darkmode

---

.github/dependabot.yml

Synk checks and updates if there is security reasons to do so. Dependabot replaces the behavior of greenkeeper, where it will try to update dependecies regardless of the upgrade reason. This will also check for updates in the workflow depdencies.

chore: add dependabot to replace greenkeeper

---

packages/checkbox-react/package.json
packages/checkbox-react/src/Checkbox.tsx
packages/datepicker-react/src/DatePicker.tsx
packages/divider-line-react/package.json
packages/logo-react/package.json
packages/logo-react/src/Logo.tsx
packages/select-react/package.json
packages/select-react/src/NativeSelect.tsx
packages/select-react/src/Select.tsx
packages/text-input-react/package.json
rollup.config.js
yarn.lock

affects: @fremtind/jkl-checkbox-react, @fremtind/jkl-datepicker-react,
@fremtind/jkl-divider-line-react, @fremtind/jkl-logo-react, @fremtind/jkl-select-react,
@fremtind/jkl-text-input-react
Vi hadde 3 ulike versjoner av nanoid depdendencyen i ulike pakker. Det i seg selv er som regel ikke et stort problem, men det lagde problemer i portalen når man brukte portal-components komponenten og checkbox hvor det var konflikt i versjoner. Men det som kanskje er mer kritisk er at mellom versjon 2 og 3, så har nanoid droppet støtte for IE. 
Denne PR oppdater alle nanoid til nyeste, oppdaterer importen i alle som brukte v2. Legger også til nanoid til å transpileres ved bygg.
-   [x] `yarn build` …

fix: align nanoid version, and migrate to 3

---

packages/core/headings.scss
packages/core/paragraphs.scss

Sørg for at kompakt variant brukes i kompakt modus

fix(core): make text style util classes respect compact mode

---

portal/src/components/Typography/Typography.tsx

Add `id` attribute to all level 2 headings in the portal to facilitate TOC-style linking within documentation.

feat(portal): add ids to level 2 headings for linking

---

portal/src/components/Documentation/Colors/ColorDescription.scss
portal/src/components/Documentation/Colors/ColorDescription.tsx
portal/src/components/Documentation/Colors/ColorTable.scss
portal/src/components/Documentation/Colors/ColorTable.tsx
portal/src/components/Documentation/Colors/Colors.scss
portal/src/components/Documentation/Colors/Colors.tsx
portal/src/texts/profile/colors.mdx

Oppgrader fargedokumentasjonen under "profilen vår".
Jeg kunne sikkert ha delt opp støttekomponentene i et par filer for lesbarhetens skyld. Si fra om dere synes jeg bør det. Har også brukt CSS-grid her, men kun i et omfang som bør støttes av IE med `-ms-grid` om vi vil ha inn støtte for IE i portalen senere.
Closes: #1015

docs(profile): improve documentation of colors

---

packages/core/documentation/Spacing/Spacing.scss
packages/core/documentation/Spacing/Spacing.tsx
packages/core/documentation/spacing.mdx
packages/core/spacing.scss
packages/core/variables/_spacing.scss
portal/src/components/Documentation/Spacing/SpacingTable.scss
portal/src/components/Documentation/Spacing/SpacingTable.tsx
portal/src/texts/profile/formdesign.mdx
portal/src/texts/profile/icon.mdx
portal/src/texts/profile/picture.mdx
portal/src/texts/profile/shadow.mdx
portal/src/texts/profile/spacing.mdx

- Legger til nye utility-klasser for spacing, som dekker både komponent- og layout-skalaen. De gamle util-klassene beholdes for kompatibilitet.
- Legger til dokumentasjon av spacing-skalaene både under "Profil" og "Komponenter" i portalen.
Closes #1017

Nye util-klasser for spacing, og dokumentasjon av spacing

---

portal/src/components/CodeBlock/CodeBlock.scss
portal/src/components/CodeBlock/CodeBlock.tsx
portal/src/components/CodeBlock/fremtindTheme.ts
portal/src/components/CodeBlock/fremtindThemeDark.ts
portal/src/components/CodeBlock/index.ts
portal/src/components/Typography/Typography.tsx
portal/src/components/Typography/typography.scss

Add support for dark mode, and adjust light theme, for code blocks in the portal. Achieves AA
contrast in both dark and light themes.

Make portal code blocks accessible and add dark mode support

---

packages/accordion-react/src/Accordion.test.tsx
packages/accordion-react/src/AccordionItem.test.tsx
packages/alert-message-react/src/AlertMessage.test.tsx
packages/button-react/src/Button.test.tsx
packages/card-react/src/Card.test.tsx
packages/checkbox-react/src/Checkbox.test.tsx
packages/core/src/components/ScreenReaderOnly.test.tsx
packages/core/src/components/SupportLabel.test.tsx
packages/datepicker-react/src/DatePicker.test.tsx
packages/field-group-react/src/FieldGroup.test.tsx
packages/hamburger-react/src/Hamburger.test.tsx
packages/icon-button-react/src/IconButton.test.tsx
packages/list-react/src/List.test.tsx
packages/loader-react/src/Loader.test.tsx
packages/message-box-react/src/MessageBox.test.tsx
packages/progress-bar-react/src/ProgressBar.test.tsx
packages/radio-button-react/src/RadioButtonOption.test.tsx
packages/radio-button-react/src/RadioButtons.test.tsx
packages/react-hooks/src/useClickOutside.test.tsx
packages/react-hooks/src/useFocusOutside.test.tsx
packages/select-react/src/NativeSelect.test.tsx
packages/select-react/src/Select.test.tsx
packages/table-react/src/Table.test.tsx
packages/text-input-react/src/TextArea.test.tsx
packages/text-input-react/src/TextInput.test.tsx
packages/toggle-switch-react/src/ToggleSwitch.test.tsx
packages/typography-react/src/SupportLabel.test.tsx
packages/typography-react/src/Typography.test.tsx

Endre alle enhetstester til å bruke den nye og mer effektive `screen.getBy`-syntaksen fremfor `const { getBy } = render()`.
affects: @fremtind/jkl-accordion-react, @fremtind/jkl-alert-message-react,
@fremtind/jkl-button-react, @fremtind/jkl-card-react, @fremtind/jkl-checkbox-react,
@fremtind/jkl-core, @fremtind/jkl-datepicker-react, @fremtind/jkl-field-group-react,
@fremtind/jkl-hamburger-react, @fremtind/jkl-icon-button-react, @fremtind/jkl-list-react,
@fremtind/jkl-loader-react, …

test: update tests to use new testing library syntax

---

packages/checkbox-react/src/Checkbox.tsx

Adds support for refs, plus support for onFocus and onBlur event handlers, to the Checkbox component. Should facilitate use with `react-hook-form`.
affects: @fremtind/jkl-checkbox-react

feat(checkbox): add support for refs to checkbox

---

packages/core/documentation/Spacing/Spacing.tsx
portal/src/components/Documentation/Spacing/SpacingTable.tsx
portal/src/components/Documentation/Typography/TypograhyTable/ExampleRow.tsx

Fixes a bug in the typography and spacing doc pages, where calculated values and previews would not load correctly unless the page was reloaded.

Fix small bug in spacing/typography docs

---

packages/core/src/index.ts
packages/select-react/src/Select.tsx

affects: @fremtind/jkl-core, @fremtind/jkl-select-react
Ifbm. implementering av Test Complete trengs det støtte for `data-testautoid` på `Select`. Denne PRen legger til et interface som kan extendes på komponenter for å legge til dette som en prop.
På sikt må vi se på hvordan implementere dette bredere. Foreløpig fungerer dette som en PoC.

feat: legg til data-testautoid type og props på Select

---

portal/src/components/CodeBlock/CodeBlock.tsx

After doing an analysis of the js-bundle for the portal I discovered that roughly 30% of the total bundle-size is used by refractor (used for syntax-highlighting code blocks in portal). Refractor supports syntax highlighting of tons of languages but we only use `tsx`, `scss` and `html`.
This PR changes the way we import `react-syntax-highlighter` so that the bundle only includes the languages we use.
Screenshot of the bundle analyse:

chore(build-config): add a lighter version of the syntax highlighter

---

cypress/support/index.js
portal/integration/frontpage.spec.js
portal/src/components/PortalImg/PortalImg.tsx
portal/src/components/PortalImg/style.scss
portal/src/components/Typography/FormatProvider.tsx
portal/src/pages/index.tsx

Hvordan blogge-posten var ikke heeeelt riktig når det kom til bilder. Vi hadde ikke håntert withPrefix fra img i markdown, så den fant ikke riktig adresse til static når portalen var i PROD.
For å løse dette så lager vi en komponent som erstatter default img komponenten i markdown parseren. Det gjør også at vi kan gjøre litt gøy med bilder, ved at de maks får størrelsen til tekstbredden i portalen, men man kan klikke på bildet for å få det opp i fullskjermsvisning.
Fikset også bug med hvilken post som vises på forsiden.
-   [x] …

chore(portal): handle images in mdx files

---

portal/src/components/DownloadAsset/DownloadAsset.tsx

ISSUES CLOSED:  #1190
Liten gatsby quirk, fungerer lokalt, siden gatsby der ligger flatt på localhost, men ikke på github pages, siden den der ligger prefixet med jokul. WithPrefix løser biffen.

fix(portal): add prefix to dowload logo

---

packages/accordion-react/documentation/accordion.mdx
packages/accordion-react/documentation/index.html
packages/accordion-react/documentation/index.tsx
packages/accordion/accordion.scss

affects: @fremtind/jkl-accordion-react, @fremtind/jkl-accordion
Ble en feil med spacing i accordion i overgangen til nye designet. Men det syns ikke på hvit/svart bakgrunn.
Oppdatert:
I prod nå:

fix(accordion): fix accordion spacing issue

---

packages/core/links.scss
patches/@nrk+core-toggle+3.0.8.patch
portal/src/components/Header/components/FullScreenMenuItem.scss
portal/src/components/Header/components/FullScreenMenuItem.tsx
portal/src/components/Header/components/MainMenu.scss
portal/src/components/Sidebar/Sidebar.scss
portal/src/components/Sidebar/SidebarMenuItem.tsx

- Bruk den nye `jkl-nav-link`-komponenten (kun stilark) i fullskjerm- og sidemenyene i portalen
- Endre hovedmenyen til å følge de nye skissene i Figma (se #1222)
- Fiks en bug i `jkl-link` og `jkl-nav-link` som gjorde at fokus-staten hang igjen etter klikk ved bruk av musen
Er det bare meg, eller blir det litt fargeløst i portalen nå som vi bare har blå på hover?

Fix portal menu styling

---

package.json
portal/package.json

Bygg portalen uten `--prefix-paths` siden vi har flyttet portalen til custom domene

chore(portal): build portal without prefix paths when deploying

---

packages/core/documentation/Colors/Colors.tsx
packages/core/documentation/Colors/colors.scss
packages/portal-components/component-example.scss
portal/src/components/Card/card.scss
portal/src/components/DoDontExample/DoDontExample.scss
portal/src/components/DoDontExample/DoDontExample.tsx
portal/src/components/Layout/Layout.scss
portal/src/components/PortalImg/PortalImg.tsx
portal/src/components/PortalImg/style.scss
portal/src/pages/index.scss

Portalen ser ikke spesielt bra ut på mobil i dag. Så med noen relativt enkle grep fikses de fleste overflyts feilene, så portalen skal bli litt hyggeligere for alle mobilbrukere.
Gjennstående oppgaver:
- Hovedmenyen kan fortsatt flyte over ved lange lenker
- Innholdet bak hovedmenyen bør låses når den er åpen, spesielt iphones har en tendens til å kunne få tak i underliggende innhold og lage en veldig rar scroll opplevelse. (iphones må ha position fixed på underliggende innhold for å sikre oss helt mot dette)
-   [x] I have added necessary documentation …

Mobile portal

---

packages/text-input-react/documentation/Autosuggest.mdx

Move the experimental icon to the end of the title for Autosuggest to improve alignment in menus.
Use a soft hyphen at the start to keep sorting order.
**Before**:
**After**:
affects: @fremtind/jkl-text-input-react.

docs(autosuggest): move experimental icon to end of title

---

packages/accordion/accordion.scss
packages/checkbox/checkbox.scss
packages/datepicker/datepicker.scss

Lets the inverted styles (for IE11) override custom variables completely, to avoid situations where they conflict.
affects: @fremtind/jkl-accordion, @fremtind/jkl-checkbox, @fremtind/jkl-datepicker

fix: override css custom properties when inverted mode is set

---

packages/core/core.scss

Per nå har vi bare Fremtind Grotesk satt som font. Det har en rekke problemer ved seg, først så har vi ingen kontroll over hvilken font som vises frem til vår font er lasta, det er opp til standard settingen til nettleseren. Hvis nedlastingen av vår font feiler eller blir blokkert, så blir man stående på feks Times New Roman, som ikke er det vi har lyst til sannsynligvis. Videre så inneholder ikke Fremtind Grotesk alle tegn, så hvis man bruker et tegn fonten ikke har, så skjer det ting. 
Konkret bug oppdaget i ahv: soft-hyphens rendres feil på iOS Safari. Åpne denne på iOS https://it1b7.csb.app/
Kode:
https://codesandbox.io/s/relaxed-sinoussi-it1b7?file=/src/App.tsx
Legg merke til at det legges inn et space som ikke skal være der mellom safari og internett, som også er det når soft hypen …

fix(core): add a font stack

---

packages/icons-react/documentation/Example.tsx
packages/icons-react/documentation/internal/AnimatedIcon.tsx
packages/icons-react/documentation/internal/IconExample.tsx
packages/icons-react/src/animated-icons/ArrowHorizontalAnimated.tsx
packages/icons-react/src/animated-icons/ArrowVerticalAnimated.tsx
packages/icons-react/src/animated-icons/HamburgerCloseAnimated.tsx
packages/icons-react/src/animated-icons/PlusRemoveAnimated.tsx
packages/icons-react/src/icons/ArrowDown.tsx
packages/icons-react/src/icons/ArrowLeft.tsx
packages/icons-react/src/icons/ArrowRight.tsx
packages/icons-react/src/icons/ArrowUp.tsx
packages/icons-react/src/icons/ArrowUpRight.tsx
packages/icons-react/src/icons/Calendar.tsx
packages/icons-react/src/icons/CheckMark.tsx
packages/icons-react/src/icons/Close.tsx
packages/icons-react/src/icons/Error.tsx
packages/icons-react/src/icons/Hamburger.tsx
packages/icons-react/src/icons/Info.tsx
packages/icons-react/src/icons/Plus.tsx
packages/icons-react/src/icons/Search.tsx
packages/icons-react/src/icons/Success.tsx
packages/icons-react/src/icons/Warning.tsx

Use `displayName` instead of `name` to display icon names in the portal example
-   [ x] I have added necessary documentation (if appropriate)
affects: @fremtind/jkl-icons-react
ISSUES CLOSED: #1299

docs(icons): use displayName in portal example

---

packages/alert-message/alert-message.scss

affects: @fremtind/jkl-alert-message
Fikset en bug som gjorde at alert-message gikk utenfor skjermen og skapte en unødig horisontal scrollbar.

fix: fix a bug where alert-message would go outside screen bounds

---

packages/datepicker-react/documentation/Example.tsx
patches/@nrk+core-datepicker+3.0.8.patch

Pilene i den enkle datovelgeren blar ikke i månedene, men flytter markert dato en måned frem/tilbake i tid. Hvis den nye datoen er utenfor tillatt periode i datovelgeren vil det derfor ikke være mulig å bruke pilene selv om det også er gyldige datoer i månedene de peker mot.
Denne PRen fikser dette gjennom en ny patch av core-datepicker.
Jeg er litt usikker på om vi får testet dette skikkelig, men skal prøve å skrive noe på et litt mindre ugudelig tidspunkt 😅
affects: …

fix(datepicker): make next/prev month buttons work properly

---

packages/text-input-react/documentation/AutosuggestExample.tsx
packages/text-input-react/src/autosuggest/Menu.tsx
packages/text-input/autosuggest.scss

affects: @fremtind/jkl-text-input-react, @fremtind/jkl-text-input
changes alignment of noHits in the autosuggest component

fix(text-input): changes alignment

---

packages/react-hooks/src/useIntersectionObserver/useIntersectionObserver.ts

Lar `useIntersectionObserver` observere SVG-elementer i tillegg til HTML-elementer. Trenger denne til arbeidet med footer.

feat(useintersection): allow observing svg elements

---

portal/src/components/Layout/Layout.tsx

På min mac har jeg satt engelsk språk i operativsystemet. Dette gjør at skjermleseren (default macos oppsett for voiceover) stort sett leser på engelsk. Det samme gjaldt portalen, men den leste de norske tekstene med en annen engelsk stemme. Ved å ta vekk "-nb" leser skjermleseren de norske tekstene med den norske stemmen.
Det virker som om VoiceOver ikke takler denne presiseringen når OS-språket er satt til engelsk.
Endret html lang attributten til "no".

Oppdater HTML lang attributt for bedre skjermleser opplevelse

---

packages/core/documentation/Spacing/Spacing.tsx
portal/src/components/Documentation/Spacing/SpacingTable.tsx

Når man ser på spacing skalaen i komponent dokumentasjonen, får man bare scss variabelnavnet, men ikke pixel verdien. Dette er noe jeg savner når jeg ser etter riktig spacing ihht. designet som foreligger.
Lagt til pixelverdien i title for eksemplene. Dette gir meg pixelverdien når jeg hovrer over eksemplene.

docs: add title to spacing example

---

packages/button-react/src/Button.tsx
packages/button/button.scss
packages/core/src/utils/tabListener.ts

Legg til animasjon på knappene ved touch, slik at de ikke skal føles så "døde" på mobile flater.
Denne løsningen bruker CSS custom properties, men alle mobile nettlesere støtter dette. Koden for å oppdatere touch-punktet på knappen er kanskje ikke super-React-aktig, men jeg slet litt med typen til `forwardRef` ifmb dette. Tar gjerne imot tips, så vi kan få flyttet den koden ut i en hook e.l.
Kjørende kode her hvis man vil teste på mobil: https://7gyzm.csb.app

Button touch animations

---

packages/image/image.scss

Løser problem er fargen på loader ble satt til grå av image stilen.
affects: @fremtind/jkl-image
ISSUES CLOSED: #1481

fix(image): fixes issue where loader color were overwitten

---

packages/radio-button-react/src/RadioButtonOption.tsx

affects: @fremtind/jkl-radio-button-react
Lagt til støtte for individuelle props på RadioButtonOption. Dette er for å kunne bruke attributter som `aria-describedby` for å legge til help label når man bruker RadioButtonOption selvstendig.

feat: add support for more attributes on RadioButtonOption

---

.github/workflows/cypress.yml

Byggtiden til portalen har gått noe opp i det siste, som gjør at vi igjen toucher på grensa til at cypress timer ut. 

chore(cypress): increase time cypress will wait for portal

---

packages/feedback-react/README.md
packages/feedback-react/package.json

Adds missing dependency `@fremtind/jkl-radio-button-react` to the `Feedback` component

chore: add missing dependency to feedback-react

---

packages/core/variables/_spacing.scss

Legger til et nytt steg i layout-spacing-skalaen (`layout-spacing--xs`) med verdi 1rem/16px. Denne verdien blir ofte brukt i skisser som avstand mellom elementer, men man har til nå måttet bruke en verdi fra component-spacing-skalaen for å få den.
ISSUES CLOSED: #1043

feat(core): expand layout spacing scale with new value

---

packages/react-hooks/src/useScreen/state.ts

Hvis skjermbredden er 768, faller alle sjekker igjennom siden breakpointet er 768 for small og det ikke sjekkes som bredden er lik.
Legger til sjekk om skjermbredden er lik breakpointet for small.

fix(react-hooks): fix small device check in useScreen

---

packages/button-react/src/Button.tsx
packages/button/button.scss

affects: @fremtind/jkl-button-react, @fremtind/jkl-button
Fikser feil der klassenavn blir satt på feil komponent når man tar i bruk loaderen. Venstrejusterer loaderen, så den ikke havner langt til høyre for der knappen var.

fix(button): set classname on wrapper for with loader

---

packages/summary-table-react/README.md
packages/summary-table/README.md

affects: @fremtind/jkl-summary-table-react, @fremtind/jkl-summary-table
Removes outdated props from documentation and fixes wrong url

docs(@fremtind/jkl-summary-table): updates documentation

---

portal/src/texts/uu/dialog.mdx
portal/src/texts/uu/farger.mdx
portal/src/texts/uu/liste.mdx
portal/src/texts/uu/lyd-video.mdx
portal/src/texts/uu/skjema.mdx

Fikser lenker som pekte til `localhost` på de nye UU-sidene.

docs(uu): fix dead links in accessibility pages

---

packages/button-react/src/Button.tsx

`type` feltet mangler fra typedefinisjonen til buttons fordi den plukket feil element.

fix(button): add missing types from button

---

packages/select/select.scss

Fikser en feil der hele wrapper-`<div>`en for Select hadde bakgrunnsfarge.
affects: @fremtind/jkl-select

fix(select): remove background color from select wrapper div

---

packages/summary-table-react/package.json

Legger stilpakken til som dependency for `jkl-summary-table-react` slik at den blir automatisk installert ved bruk.
affects: @fremtind/jkl-summary-table-react

fix(summary-table-react): add style pkg as dependency

---

packages/datepicker-react/src/DatePicker.tsx

Hvis det ikke er supportlabel så settes fortsatt describedby iden til supportlabelen. Det gjør at vi peker screenreaderen til noe som ikke finnes, som er litt uheldig.

fix(datepicker): fix broken aria reference when no supportlabel

---

packages/button-react/documentation/Example.tsx
packages/button-react/documentation/style.scss
packages/button/button.scss

affects: @fremtind/jkl-button-react, @fremtind/jkl-button
increases clip-path percentage and adds padding to make the focus outline for button visible
ISSUES CLOSED: #1704
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, …

fix(@fremtind/jkl-button): fixes clipped focus-bug in button

---

packages/button-react/src/BaseButton.tsx
packages/button-react/src/Button.test.tsx
packages/button-react/src/Button.tsx
packages/button-react/src/index.ts
packages/button-react/src/types.ts

ISSUES CLOSED:  #1783
defining button inside button caused an rerender all the way out to the DOM for each change in the
react tree

fix(button): fix rerender issue

---

packages/feedback-react/documentation/Example.tsx
packages/feedback-react/package.json
packages/feedback-react/src/BaseFeedback.tsx
packages/feedback-react/src/Feedback.tsx
packages/feedback-react/src/FeedbackValues.tsx
packages/feedback-react/src/SimplifiedFeedback.tsx
packages/feedback-react/src/index.ts
packages/feedback/feedback.scss

Bevegelsene var veldig stakato tidligere, nå legges det på en diskret bevegelse ut og inn når ting endrer seg i komponenten.
Legger også til en mye mer dynamisk resultat på fra feedbacken. Dagens funksjonalitet er bevart, men man kan nå ta over ansvaret selv for å generere "success" visningen etter feedbacken er sendt. Der har man tilgengelig svaret og meldingen, så man kan diferensiere hva man sier til kunden om vedkommende var fornøyd eller ikke. Kan også gjøre ting med meldingen om man ønsker det, feks lete etter personopplysinger som ikke burde være der og informere om at de ikke får hjelp her.
-   [x] I have added tests that …

Bevegelse i Feedback og custom suksessmelding

---

packages/feedback-react/src/BaseFeedback.tsx
packages/feedback-react/src/Feedback.test.tsx
packages/feedback/feedback.scss

affects: @fremtind/jkl-feedback-react, @fremtind/jkl-feedback
ADDED WRAPPER
Dette betyr om man sender inn className til wrapperen, ikke til Feedback input blokka. Dette bør ikke knekke normale implementasjoner.

feat(feedback): added wrapper, add test

---

packages/core/documentation/Example.tsx
packages/core/documentation/Mixins/Keyboard.tsx
packages/core/documentation/Mixins/keyboard.scss
packages/core/documentation/mixins.mdx
packages/core/mixins/_all.scss
packages/core/mixins/_navigation.scss

I dag så strør vi rundt oss med denne `html:not([data-mousenavigation]):not([data-touchnavigation])` rundt om kring i kode, som i seg selv ikke er et stort problem. Men det gjør at det ikke er spesielt enkelt for klienter å ta ibruk denne funksjonaliteten i sine komponenter uten for jøkul. Ved å tilby dette som en mixin, så fristiller vi klientene fra å ha et forhold til disse funksjonene. Hvis det også skulle dukke opp utvida behov for denne, som det gjorde med touchnavigation, så kan vi oppdatere det et sted, isteden for å distribuere ansvaret. 
1. Er å lage denne og publisere den
2. Erstatte alle interne referanser til `html:not([data-mousenavigation]):not([data-touchnavigation])` med `keyboard-navigation`
-   [x] I have read the …

feat(core): add keyboard mixin

---

packages/text-input-react/src/BaseInputField.tsx

Eksponerer prop som er praktisk i en del tilfeller.

fix(text-input): expose default value prop

---

packages/list-react/src/ListItem.tsx
packages/list/list.scss

Fikser en bug der ikonene i ikon-listen dekket over starten av teksten i listepunktet (i IE11).
affects: @fremtind/jkl-list-react, @fremtind/jkl-list
Closes: #1827

fix(list): fix display of icon list in IE

---

packages/list-react/src/List.test.tsx
packages/list-react/src/ListItem.tsx

affects: @fremtind/jkl-list-react
actually set className not className as a string as class
Tidligere `<ListItem className="hest" />` ble `<li class="jkl-list-item className" />`
Nå:  `<ListItem className="hest" />` ble `<li class="jkl-list-item hest" />`

fix(list): set className in correct position

---

portal/src/texts/profile/animation.mdx

Noe av teksten i animasjonsdoc var uklar og er nå forbedret

docs(portal): juster tekst i animasjonsdokumentasjon

---

packages/card/card.scss

affects: @fremtind/jkl-card
ISSUES CLOSED: #1853
Add a focus outline to clickable cards

feat: add focus outline on keyboard nav for clickable card

---

packages/alert-message-react/documentation/AlertMessage.mdx
packages/alert-message-react/documentation/AlertMessageExample.tsx
packages/alert-message-react/documentation/index.tsx
packages/alert-message-react/package.json
packages/alert-message-react/src/AlertMessage.tsx
packages/alert-message/alert-message.scss

Legger til mulighet for en "lukk"-knapp på AlertMessage for å kunne fjerne meldinger.
Denne dekker et ønske fra Smartforhandler der det nå er en global AlertInfoMessage om at siden er under ombygging. Vi ønsker å la brukeren klikke denne vekk så de slipper å se den hver gang de besøker siden (som ofte brukes hver dag). Det er ikke lagt inn noe logikk her, slik at håndtering av dette kan tilpasses appen den brukes i.

Legg til mulighet for å lukke AlertMessage

---

packages/validators-util/src/isValidDogId/isValidDogId.ts

Denne validerer kun norske nummer, det er sannsynligvis strengere enn man vil ha. Denne kommer nok til å endre seg til å ta med flere gyldige landskoder. Vær klar for at det kommer breaking change på denne om man tar den i bruk.

fix: add deprecation warning dogid

---

packages/alert-message-react/src/AlertMessage.tsx

Fikser feil der browser gir følgende feilmelding
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
at div
at div
at http://localhost:9000/main.js:14249:17
at p
at div
at messageBox (http://localhost:9000/main.js:12651:22)
If this is a relatively large or complex …

fix: <div> cannot appear as a descendant of <p>

---

packages/icons-react/src/animated-icons/HamburgerCloseAnimated.tsx
packages/icons-react/src/animated-icons/PlusRemoveAnimated.tsx
packages/icons-react/src/icons/ArrowDown.tsx
packages/icons-react/src/icons/ArrowLeft.tsx
packages/icons-react/src/icons/ArrowRight.tsx
packages/icons-react/src/icons/ArrowUp.tsx
packages/icons-react/src/icons/ArrowUpRight.tsx
packages/icons-react/src/icons/Calendar.tsx
packages/icons-react/src/icons/CheckMark.tsx
packages/icons-react/src/icons/Close.tsx
packages/icons-react/src/icons/Error.tsx
packages/icons-react/src/icons/Hamburger.tsx
packages/icons-react/src/icons/Info.tsx
packages/icons-react/src/icons/Plus.tsx
packages/icons-react/src/icons/Search.tsx
packages/icons-react/src/icons/Success.tsx
packages/icons-react/src/icons/Warning.tsx
packages/icons-react/src/icons/types.ts
packages/icons/animated-icons.scss

affects: @fremtind/jkl-icons-react, @fremtind/jkl-icons
ISSUES CLOSED: #1811
Oppfører seg som før, men kan nå ta i mot title og description som props. Fikser også problem med animated plusclose og hamburger hvor tittelfeltet vises for første ikonet uansett.

feat(icons): add title and desc as props

---

portal/package.json
portal/src/components/PortalImg/PortalImg.tsx
portal/src/components/PortalImg/style.scss
yarn.lock

Per i dag har ikke bildene noen fokus-state i portalen, så for tastaturbrukere er det veldig vanskelig å se at de er klikkbare. Og enda verre å lukke. Legger til fokus-state på bildet, og en lukk knapp med focustrap.

fix(portal): add focus state and trap to portalimg

---

packages/text-input-react/src/TextArea.tsx

Fiks for en bug der `TextArea` var `aria-describedby` help-/errorLabel, selv når den ikke ble vist. Har brukt samme pattern her som i `TextInput`.

fix(text-area): remove describedby attr when field has no message

---

packages/react-hooks/src/animation.tsx

Ignorer `transition`-eventer fra inne i elementet som animeres. Dette hindrer at elementet lukkes for tidlig dersom det brukes CSS-animasjon inne i det, f.eks. ved `TextInput` som mister fokus.

fix(useAnimatedHeight): ignore bubbling transitions

---

packages/datepicker-react/src/DatePicker.test.tsx
packages/datepicker-react/src/internal/reducer.ts

Legger til funksjonalitet for automatisk å lukke kalenderen dersom en gyldig dato skrives inn i datofeltet i `DatePicker`.
**Merk**: Vi godtar i dag årstall med to siffer. Bør vi endre det til kun fire siffer, for å være konsekvente? Støtte for to siffer ble lagt inn for fem måneder siden, mener det var etter et ønske/behov fra BM. Har dere noen tanker, @frisol97 og @joms?
ISSUES CLOSED: #2033

Lukk kalender når en gyldig dato er skrevet inn

---

.github/workflows/cypress.yml

The bot access token is required to write snapshots back to the repo

revert(cypress): add back bot token to cypress workflow

---

packages/feedback-react/src/BaseFeedback.tsx
packages/feedback-react/src/Feedback.test.tsx

affects: @fremtind/jkl-feedback-react
Det var en bug hvor en lagret tilbakemelding ble sendt på nytt når man forlot siden.
Jeg prøvde å flytte hele `feedbackSubmitted` inn i `feedbackValuesRef`, men da fikk state oppdateringen problemer. Litt usikker på hvorfor dette skjedde, men det ser ut til å funke fint å representere UI med state og business-logikk med ref.

fix(feedback): fiks en bug hvor en allerede lagret tilbakemelding ble lagret på nytt

---

packages/cookie-consent/cookie-consent.scss

Fiks bakgrunnsfargen til CookieConsent i dark mode
affects: @fremtind/jkl-cookie-consent

fix(dark mode): use correct bg-color in dark mode

---

packages/button-react/documentation/style.scss
packages/button-react/src/Button.tsx

Knappene har en bug i prod der de utvider seg når de starter å loade og muligens flytter innhold på siden. En av internsene fant denne buggen når de skulle ta i bruk dekningsvelgeren som vi bruker i smartforhandler.  Dette er en quick fix for at det ikke skal skje. 

fix: changed when withLoader div shows in button

---

packages/content-toggle-react/documentation/ContentToggle.mdx
packages/content-toggle-react/documentation/Example.tsx
packages/content-toggle-react/documentation/index.tsx
packages/content-toggle-react/src/ContentToggle.tsx
packages/content-toggle/content-toggle.scss
packages/hamburger-react/documentation/Example.tsx
packages/hamburger-react/documentation/Hamburger.mdx
packages/hamburger-react/documentation/index.tsx
packages/hamburger-react/src/Hamburger.tsx
packages/hamburger/hamburger.scss

Den tidligere API-endringen for å legge til `actionLabel` er utvidet med støtte for å kunne slå på animasjon, og muligheten til å plassere teksten til høyre eller venstre for hamburgeren. 
Plassering er løst med å rotere først hele elementet, og så rotere tekstene igjen. Dette var det eneste jeg fikk til å fungere på en god måte. Grunnen til at det har vært trøblete er at children er absolutt posisjonerte, som ikke gir parent et godt forhold til bredde.
Sistnevnte har jeg prøvd å løse ved å kalkulere en gjetning på bredde, men dette fungerer mest for å få hamburgermenyen til å ta en mer riktig plass i DOM-treet. 
Jeg er åpen for forslag på bedre løsninger enn å bruke rotasjon.
-   [X] …

Legg til mer snadder på hamburger, og gi den bedre breddekontroll

---

packages/core/mixins/_text-style.scss

Fikser en bug der tekststilen `heading 2` har fet skrift på små skjermer

fix(text-styles): use correct weight for heading 2 on small screens

---

packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx
packages/select/select.scss

affects: @fremtind/jkl-select## 📥 Proposed changes
Legg til hover farger for innhold i select.
Legg til støtte for å bruke pil ned til å åpne select. Dette ble gjort ved å fremtvinge et klikk-event på knappen, da å bruke `onToggle` eller endre `dropdownIsShown` som brukes av CoreToggle ikke lot seg bruke direkte. CoreToggle feilet med at den satte i gang en evig renderløkke...
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you …

fix: add hover color and cursor for select

---

packages/core/_jkl.scss

Eksporter funksjonene i `_functions.scss` gjennom det nye endepunktet `@fremtind/jkl-core/jkl` for enklere bruk.
```scss
@use "@fremtind/jkl-core/jkl";
$border-width: jkl.rem(2px);
```

feat(sass): forward functions to new jkl entrypoint

---

.github/dependabot.yml

Endre frekvens på Dependabot-skann fra daglig til ukentlig. Det blir uansett ikke fikset daglig, og det kommer patcher _hele tiden_

chore(ci): change dependabot frequency to weekly

---

packages/feedback-react/src/Feedback.tsx
packages/field-group-react/src/FieldGroup.tsx
packages/text-input-react/src/TextInput.tsx
packages/text-input-react/src/autosuggest/BaseAutosuggest.tsx

This commit removes default variant value from components
which uses the Label component. This allows the default to be
dictated by Label.
This commit also changes the default variant for BaseAutosuggest
from medium to small to match the default value of Label.

fix: default variant should be small

---

packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx
patches/@nrk+core-toggle+3.0.8.patch

ISSUES CLOSED: #1688, #2126
Jeg var først overbevist om at dette var en bug i `@nrk/core-toggle`. Såpass at jeg begynte på en patch og tenkte jeg skulle åpne et issue hos dem. Jeg tenker fortsatt at det kan være lurt, for jeg mener det er noe galt der. Kort fortalt mener jeg denne patchen burde gjøres for å slippe å ha dette timingproblemet i utgangspunktet:
```diff
set value (data = false) {
if (!this.button || !this.popup.length) return
const button = …
```

fix: fikser et timingproblem som ga feil aria-label i Select

---

packages/alert-message-react/README.md
packages/alert-message-react/src/AlertMessage.tsx
packages/message-box-react/README.md
packages/message-box-react/src/MessageBox.test.tsx
packages/message-box-react/src/MessageBox.tsx
portal/src/texts/getstarted/buildWithJkl.mdx

affects: @fremtind/jkl-alert-message-react, @fremtind/jkl-message-box-react, @fremtind/portal
MessageBox og dens varianter lar deg nå overstyre role fra det som har vært standard (alert).
InfoMessage og SuccessMessage får endret standardrolle til status. Med denne endringen kan f. eks.
InfoMessage brukes som et rent presentasjonselement (med \`role="none presentation\`).
ISSUES CLOSED: #1687

feat: prop for å styre role på MessageBox

---

.github/workflows/external-contributions-sync.yml

Dersom det er endringer på external-contributions som ikke er i main vil ikke en rebase kunne pushes
uten --force. Velger å gå for en merge i stedet. Jobben kan fremdeles feile pga merge conflicts, men
de må i så fal håndteres manuelt på external-contributions.

chore: bruk merge i stedet for rebase i syncjobb

---

.github/workflows/weekly-tasks.yml

creates a weekly issue to upgrade dependencies with rotation among the assignees
Denne action-en vil lage en issue ukentlig for oppgradering av avhengigheter.
Det er også rotasjon blant assignees.
Fulgte denne guiden:  https://docs.github.com/en/actions/guides/scheduling-issue-creation
Denne bruker en tredjepartsbot som heter Issue Bot Action: https://github.com/marketplace/actions/issue-bot-action
-   [x] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) doc
If this is a relatively large or complex change, kick off the discussion by explaining why you …

chore: creates a weekly issue to upgrade dependencies

---

.github/workflows/weekly-tasks.yml

Fikser typo i project-feltet for weekly-tasks.yml og endrer fra tidpsunkt for ukentlig oppgradering fra søndag kl5 til mandag kl5

chore: fixes typo in weekyl-tasks.yml

---

.github/workflows/portal.yml

Det er en merkbar forskjell på localhost mellom et clean bygg og det neste. Gjør et forsøk med
caching for å korte ned byggtiden til portalen.
ISSUES CLOSED: #1574

chore: bruk en cache for Gatsby-bygget

---

.github/workflows/release.yml

Bruk et PAT (fra min bruker) for å publisere til GitHub Packages, inntil vi får på plass en mer permanent løsning (f.eks. via @fremtind-bot )
Jeg er ikke 100 % sikker på at dette vil løse problemet vi har hatt med publisering, men skader ikke å prøve!

chore(ci): use PAT for publishing to github packages

---

packages/hamburger-react/README.md
packages/hamburger-react/src/Hamburger.test.tsx
packages/hamburger-react/src/Hamburger.tsx
packages/hamburger/hamburger.scss

Legger til `aria-haspopup` og `aria-expanded` som egenskaper på Hamburger, for å bedree kommunisere egenskapene dens til f.eks. skjermlesere. Jeg valgte foreløpig å _ikke_ la disse endres, da hamburgeren alltid skal brukes til å styre en meny og derfor alltid vil trenge disse egenskapene.
Legger også til støtte for valgfri prop `aria-controls` som kan peke på `id`en til elementet som inneholder menyen og åpnes/lukkes av knappen.
-   [x] Jeg har lagt til tester som …

Bedre semantikk og tilgjengelighet i Hamburger

---

.github/workflows/weekly-tasks.yml

Bruk et sett med labels som er ulikt Dependabot så Issue Bot kan finne igjen forrige assignee.
Skriv om til norsk arbeidsspråk.

chore: fiks rotering av assignee på weekly

---

.github/workflows/release.yml
packages/image/package.json

- Legger til feltet `repository` i `package.json`-fila til `jkl-image`, slik at pakken kan publiseres til GitHub Packages uten problemer.
- Bruk GITHUB_TOKEN ved release til GitHub Packages

chore: add repository field to package.json

---

.github/dependabot.yml

Dependabot sjekker by default på et [tilfeldig tidspunkt](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleday) i løpet av mandag når interval står på "weekly"
I tilfelle den ukentlige assigneen ønsker å få unna oppgavene på mandag kan det kanskje være praktisk å tidspunktet litt frem 😄 
-   [ ] Jeg har lest [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) og dokumentasjon det henvises til
-   [ ] Jeg har lagt til tester som demonstrerer at feilen er rettet …

Endre tidspunktet dependabot sjekker etter nye oppdateringer

---

packages/select/select.scss
portal/src/texts/blog/cursor-pointer.mdx

affects: @fremtind/jkl-select, @fremtind/portal
ISSUES CLOSED: #2173
Setter `cursor:pointer` på select. Dette ser ut til å være det eneste klikkbare elementet som ikke brukte denne stilen. Endringen gjøres etter å ha diskutert dette på ds-forum.
Jeg har også skrevet en bloggpost om hvorfor og hvordan vi har tatt denne avgjørelsen. Fint om noen vil lese over og komme med tilbakemeldinger.
-   [X] Jeg har kjørt `yarn build` og `yarn ci:test` og disse gir ingen feil
-   [X] Jeg har lagt til tester som demonstrerer at feilen er rettet eller …

feat: use cursor:pointer style on select

---

packages/validators-util/src/isValidChassisnummer/isValidChassisnummer.test.ts
packages/validators-util/src/isValidChassisnummer/isValidChassisnummer.ts

affects: @fremtind/jkl-validators-util
Tillat strings med tall og bokstaver, men ikke spesialtegn, på 9 eller 17 tegn
isValidChassisnummer tillater nå ikke-numeriske strings og strings på 17 tegn. Om du parser
resultatet som et tall eller har en lengdebegrensning i databaseskjemaet ditt må du oppdatere
appen din til å støtte den nye regelen.
ISSUES CLOSED: #1662
-   [x] Jeg har lagt til tester som demonstrerer at feilen er rettet eller featuren …

fix: oppdater valideringsreglene for chassisnummer

---

.github/workflows/cypress.yml
.github/workflows/portal.yml
.github/workflows/release.yml
.github/workflows/test.yml
lerna.json

Prøv å begrens bruken av særlig visuelle regresjonstester og byggsteg for endringer som ikke rører
kode.
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths

chore: begrens hvilke filer som starter en GitHub Action

---

.github/workflows/release.yml

Ikke feile release-flyten når det ikke finnes endringer å publisere. Vanskelig å teste dette uten å merge, men mener at jeg har lest dokumentasjonen av GitHub Actions riktig her:
- [continue-on-error](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error)
- [steps context](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context)
-   [x] Jeg har lagt til tester som demonstrerer …

chore(ci): ikke feile release-flyt når det ikke er endringer

---

lerna.json

Testet endringen på en fork og klonet den til et annet sted på disk. Kjørte `yarn boot`. Portalen fungerte fint med `yarn dev`, og med `yarn build:docs && yarn server`.
ISSUES CLOSED: #2428 

chore: stopp versjonering av portalen

---

portal/gatsby-config.js

Oppgraderingen av Gatsby hadde fjernet en source for mye. Det finnes
visst bilder i components-mappa som brukes blant annet på Profil ->
Bildebruk.

fix: gjenopprett bilder i Bildebruk

---

packages/accordion-react/src/Accordion.test.tsx
packages/select-react/documentation/SelectExample.tsx
packages/select-react/src/NativeSelect.test.tsx
packages/select-react/src/NativeSelect.tsx
packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx
packages/select-react/src/index.ts
portal/src/components/Examples/SimpleForm/AddressForm.tsx

Skriv om `Select` og `NativeSelect` så begge kan brukes som uncontrolled components (les: med `register`)
Testet OK med react-hook-form på #2489, så rebaset på `main`
ISSUES CLOSED: #2456

fix: legg til støtte for react-hook-form i select-react

---

portal/src/texts/getstarted/processGuide.mdx

I tråd med praten fra forum i dag (16/11) og tidligere diskusjoner, har jeg ett forslag til å "slutte å snakke om prosess" og heller bruke siden som i dag heter "[Designsystemprosessen](https://jokul.fremtind.no/komigang/prosessen)" til å snakke om hvordan man kan bidra til Jøkul i stedet. Siden skal ha innhold, lenker og tips som hjelper bidragsyterne videre på veien til å skape gode bidrag som kan bli en del av Jøkul.
Også er [siden som forklarer](https://jokul.fremtind.no/komigang/prosessen) "prosessen" vår i dag er utdatert og ikke noe vi jobber etter per dags dato. 😄
-   [x] Jeg har satt target branch til `main`, eller `external-contributions` dersom pull …

docs: eradicate "the process" 🤠

---

packages/text-input/text-input.scss

Fikser en regresjon etter #2509 (bugfix for clipping av Å)

fix: rett feil linjehøyde for kompakte tekstfelt

---

portal/src/components/portal-image/PortalImage.tsx

Ser ut som om tekst under bildet ikke har jkl class og at det må settes manuelt. 

fix: added jkl class to text under photos

---

packages/button/button.scss

Fikser en bug hvor bruk av .jkl-button ikke blir håndtert likt på alle elementer. Feks `<a href="#" class="jkl-button">`
Close #2585 
-   [X] Jeg har kjørt `yarn build` og `yarn ci:test` og disse gir ingen feil
-   [X] Jeg har lagt til tester som demonstrerer at feilen er rettet eller featuren fungerer
-   [X] Jeg har skrevet relevant dokumentasjon

fix: make all button elements respect width constraint

---

packages/text-input-react/src/BaseInputField.tsx
packages/text-input/text-input.scss

affects: @fremtind/jkl-text-input-react, @fremtind/jkl-text-input
TextInput uten definert maxLength blei like breie som containeren sin, dette var feil og er fiksa i denne PRen.

fix: bruk riktig lengde for TextInput

---

packages/text-input-react/documentation/Autosuggest.mdx
packages/text-input-react/documentation/AutosuggestExample.tsx
packages/text-input-react/documentation/TextInput.mdx
packages/text-input-react/src/autosuggest/Autosuggest.tsx
packages/text-input-react/src/autosuggest/index.ts
packages/text-input-react/src/index.ts
portal/src/components/Experimental/Experimental.tsx

Rendyrk Autosuggest som en komponent hvor formålet er å tillate fritekst, men komme med kjente forslag der vi har dem. Dette tydeliggjør rollene til denne komponenten og en søkbar Select. Ingen kodeendringer, bare dokumentasjon.
Om `leadText`: dette er ikke et mønster vi bruker i skjemaene våre. Det skal ikke være et avsnitt med tekst mellom
en label og skjemafeltet. Bruk helpLabel eller flytt denne teksten ovenfor skjemafeltets label i et selvstendig avsnitt.
ISSUES CLOSED: #2575 
-   [x] Jeg har kjørt `yarn build` og `yarn ci:test` og disse …

docs: dokumenter Autosuggest, deprecate leadText

---

packages/tabs-react/package.json
packages/tabs-react/src/Tabs.test.tsx
packages/tabs-react/src/Tabs.tsx

Vi har et behov for å kunne reagere når hvilke tab som er aktiv endrer seg. Dette er for å kunne registrere bruksmønster i Mixpanel. Her har jeg lagt til en onChange funksjon som trigges hver gang den aktive tabIndexen endrer seg.
-   [X] Jeg har kjørt `yarn build` og `yarn ci:test` og disse gir ingen feil
-   [X] Jeg har lagt til tester som demonstrerer at feilen er rettet eller featuren fungerer
-   [X] Jeg har skrevet relevant dokumentasjon

feat: add onChange event to tabs

---

package.json
portal/src/texts/getstarted/GettingStartedDev.mdx

For å luke ut et opplevd problem etter mixing av npm og yarn

fix: clean også node_modules på rotnivå

---

packages/hamburger/hamburger.scss

affects: @fremtind/jkl-hamburger
dette lar konsumenten selv styre hvordan spacing rundt hamburgeren skal være
-   [ X Jeg har kjørt `yarn build` og `yarn ci:test` og disse gir ingen feil

fix: fjern padding fra hamburger

---

packages/button-react/src/Button.test.tsx
packages/button-react/src/Button.tsx

Var en logikkfeil som gjorde at loadingtekst ble lest opp umiddelbart, og ikke lest opp når
loadingtilstanden ble startet.
ISSUES CLOSED: #2647

fix: sett korrekt aria-hidden basert på showLoader

---

.github/workflows/pull_request.yml
cypress.json

Test for å få ned kjøretid av visuelle regresjonstester
Videoene tar tid å laste opp og har en kostnad under opptak også. De
blir sjeldent brukt under feilsøking. Om man opplever å ikke få
reprodusert feilen lokalt kan det eventuelt skrus på igjen etter
behov. I dag er det som oftest tilstrekkelig med screenshots av diff
og actual, som kan sammenlignes med originalene på disk.

chore: dropp videoopptak under Cypress-test

---

.github/ISSUE_TEMPLATE/funksjonalitets-nske.md

Veksle fra å snakke om å "_ønske_ ny funksjonalitet" til **komme med nye bidrag**. Dagens ordlyd motstrider målet vårt om at bidragsyterne _selv_ skal sikre kvaliteten i Jøkul, og hverandres bidrag, med _støtte_ fra kjerneteamet—i stedet for godkjenning. I tillegg er premisset for at nye issues opprettes basert på at behovet for ny funksjonalitet allerede bekreftet.

docs: endre issue tittelen og beskrivelsen

---

packages/expand-button-react/src/ExpandButton.tsx

affects: @fremtind/jkl-expand-button-react
Form trigget av ExpandButton da den ikke hadde type="button"
-   [x] Minstekrav til dokumentasjon er oppfyllt (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker)
-   [x] Testdekningen er god nok (enhetstest, visuell regresjonstest)

fix(expand-button): changed to type=button

---

packages/constants-util/src/unicode.ts

affects: @fremtind/jkl-constants-util
La til ZERO_WIDTH_SPACE konstant for å kunne kontrollere ordbrytning

feat(constants): add zero-width space unicode constant

---

packages/expand-button-react/src/ExpandButton.tsx
packages/expand-button/expand-button.scss
packages/react-hooks/documentation/UseIdExample.tsx
packages/react-hooks/documentation/index.tsx
packages/react-hooks/documentation/useId.mdx
packages/react-hooks/package.json
packages/react-hooks/src/index.ts
packages/react-hooks/src/useId.ts
packages/table-react/documentation/ExpandableTableExample.tsx
packages/table-react/documentation/Table.mdx
packages/table-react/documentation/index.tsx
packages/table-react/package.json
packages/table-react/src/ExpandableTableRow.tsx
packages/table-react/src/ExpandableTableRowCell.tsx
packages/table-react/src/ExpandableTableRowController.tsx
packages/table-react/src/Table.tsx
packages/table-react/src/index.ts
packages/table-react/src/tableContext.tsx
packages/table/table-cell.scss
packages/table/table-row.scss

Legg til funksjonalitet for utvidbare tabellrader. Se kommentarer for notater om triks og vurderinger.
Endringer: 
- Lagt til ny tabellrad som bruker `TableRow` for å bygge en ekspanderbar tabell
- Utvidet funksjonaliteten i `ExpandButton` for å kun vise pil

Implementer utvidbar tabell-rad

---

.github/workflows/pull_request.yml
.github/workflows/pull_request_close.yml
package.json
portal/gatsby-config.js
portal/src/pages/hello-world.tsx

Inspirert av [denne bloggposten](https://daiyi.co/blog/pr-previews-for-github-pages/), og det faktum at AWS Amplify (som vi hadde tenkt å gjøre en PoC med) tydeligvis ikke er fans av pull request previews for annet enn private repoer.
Det er for øvrig verdt å [watch this space](https://github.com/github/feedback/discussions/7730) – støtte for previews er på roadmapet (uten ETA, men "medium term").
**Fordeler**
- Løser det umiddelbare problemet for Jøkul med dagens verktøy og infrastruktur
- Veien til GitHub-offisielle previews er forhåpentligvis kort, den dagen det lanseres
**Ulemper**
- Previews havner på samme domene
- Litt _janky_
- Vi må ha på `--all` ved publisering for ikke å slette previews mellom deploys, og prøve å rydde opp etter oss ved lukket PR
Jeg er åpen for at vi bør gå …

PoC: forhåndsvisning av brancher med GitHub Pages

---

packages/image-react/package.json

Den nye bildekomponenten hadde gammel versjon av stilpakken som dependency. Endre dette til den nye versjonen.
-   [x] Minstekrav til dokumentasjon er oppfyllt (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker)
-   [x] Testdekningen er god nok (enhetstest, visuell regresjonstest)

fix(deps): bruk riktig versjon av stilpakken

---

patches/cz-lerna-changelog+2.0.3.patch

Fjern steg som vi egentlig ikke bruker. Skaper unødvendig usikkerhet når man skal bidra.
Fjerner stegene `scope` og `affected packages`.
Det var ingen options for å fjerne ting (bare legge til flere), men vi har heldigvis `patch-package`.

chore: patch commitizen til vårt bruk

---

packages/text-input/text-input.scss

Eg retta tidligare ein feil som at startOpen ikkje fungerte sammen med counter på TextArea. Dette innførte ein ny feil, TextArea fekk feil høgde (høgden til teksten + høgden til den usynlige counteren). Feilen er fiksa i denne PRen.

fix: add correct max-height to textarea with counter

---

gulpfile.js
package.json
packages/formatters-util/package.json
patches/gulp-sass+5.1.0.patch
yarn.lock

Jeg prøver å lande denne patchen upstream, men det er lite respons fra maintainer. Skal følge opp, men er jo ingen grunn til at vi må vente 😄
Med dette kommer vi oss vekk fra et deprecated Sass-API (og får et par sekunders raskere bygg via sass-embedded, ikke at det gjør den største forskjellen 😛)

chore: patch gulp-sass for å bruke sass-embedded

---

packages/feedback-react/src/questions/SmileyQuestion.tsx

Child keys må ligge på "roten" når man mapper en liste om til React-elementer.
Flytter derfor key prop fra input til Fragment.

fix: child keys on SmileyQuestion

---

packages/formatters-util/documentation/FormattersExample.tsx
packages/formatters-util/src/telefonnummer/formatTelefonnummer.test.ts
packages/formatters-util/src/telefonnummer/formatTelefonnummer.ts

affects: @fremtind/jkl-formatters-util

feat: legg til støtte for landkode i telefonnummer

---

packages/image-react/src/index.ts

Eksporterer typen ImageProps. Litt usikker om dette er den mest riktige/beste måten å gjøre det på?
-   [ x] `yarn build` og `yarn ci:test` gir ingen feil

fix: exporter type for ImageProps

---

packages/text-input-react/src/TextArea.tsx

De to funksjonene ble ikke hentet ut av restProps, og de interne
funksjonene som oppdaterer state ble overskrevet. Refactor ut all
bruk av `restProps.propName` for å unngå sånne situasjoner.
ISSUES CLOSED: #2770

fix: intern tilstand oppdateres selv med onBlur

---

packages/formatters-util/src/util/parseNumber.test.ts
packages/formatters-util/src/util/parseNumber.ts
tsconfig.json

affects: @fremtind/jkl-formatters-util
Earlier parseNumber accepted formats way beyond what could be expected
of a legal number. I've now changed it to be closer to the native
functionality of Number, and try to make the assumption that most
numbers will be in a norwegian-ish format
number parsing is more strict
- …

feat: make parseNumber less naive and including

---

packages/summary-table-react/documentation/SummaryTableExample.tsx
packages/summary-table-react/mocks/index.tsx
packages/summary-table-react/src/SummaryTableRow.tsx

allows header and content props of SummaryTableRow to take ReactNode to allow use of jkl-sr-only to
provide better accesibility

fix: makes header and content props of SummaryTableRow more flexible

---

packages/table/table-row.scss

move expand controller to the right side, and adjust how it influences
the borders

feat: make expand row more appealing on mobile

---

packages/react-hooks/src/useId.ts

Fikk litt warnings ved kompiliering ved bruk av useId dersom man hadde react versjon lavere enn 18.

fix: using React default export to avoid warnings when using react below v18

---

portal/src/pages/index.scss
portal/src/pages/index.tsx

Se prod på hjemmesiden. Tekstfargen er feil i navcard

fix: navcards on frontpage now shows correct color on text

---

packages/button-react/documentation/buttons.mdx
packages/checkbox-react/documentation/Checkbox.mdx
packages/core/src/components/Label.spec.tsx
packages/datepicker-react/documentation/Datepicker.mdx
packages/datepicker-react/src/DatePicker.test.tsx
packages/datepicker-react/src/DatePicker.tsx
packages/field-group-react/documentation/FieldGroup.mdx
packages/field-group-react/src/FieldGroup.test.tsx
packages/field-group-react/src/FieldGroup.tsx
packages/radio-button-react/documentation/RadioButton.mdx
packages/radio-button-react/documentation/RadioButtonExample.tsx
packages/radio-button-react/documentation/RadioButtonInputRequiredExample.tsx
packages/radio-button-react/documentation/RadioButtonPreselectedExample.tsx
packages/radio-button-react/src/RadioButton.tsx
packages/radio-button-react/src/RadioButtonGroup.test.tsx
packages/select-react/documentation/Select.mdx
packages/select-react/src/NativeSelect.test.tsx
packages/select-react/src/NativeSelect.tsx
packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx
packages/text-input-react/documentation/TextInput.mdx
packages/text-input-react/src/TextArea.test.tsx
packages/text-input-react/src/TextArea.tsx
packages/text-input-react/src/TextInput.test.tsx
packages/text-input-react/src/TextInput.tsx
packages/text-input-react/src/autosuggest/Autosuggest.test.tsx
packages/text-input-react/src/autosuggest/Autosuggest.tsx
packages/text-input-react/src/autosuggest/BaseAutosuggest.tsx
portal/src/texts/blog/updates/april-2022.mdx

- Gjør `labelProps` tilgjengelig i skjemakomponenter der det manglet (for `labelProps.srOnly` i hovedsak, men med fleksibilitet)
- Gjør så `RadioButton` tar `children` på samme måte som `Checkbox`
- Lenk til eksempel på skjema og skjemakode fra komponentdocs så det er mulig å oppdage

feat: uniformt API for å skjule labels visuelt, RadioButton tar children

---

packages/formatters-util/src/valuta/formatValuta.test.ts
packages/formatters-util/src/valuta/formatValuta.ts

Fiks at en sum av 0 ikke blir tolket som false.

fix: fiks en bug hvor verdi 0 fikk formatValuta til å feile

---

packages/button-react/src/types.ts

Vi har hatt nettopp en feil der en knapp stod og lastet selv om `showLoader: false`. Dette var fordi vi hadde fjernet teksten på knappen ved et uhell under en refaktorering, og brukte nettopp litt til på å finne feilen fordi vi ikke fikk noe feilmelding fordi children er optional. Kan ikke se noen grunn for at den skal være optional. 
Vurderte også å se litt på logikken for at den loader selv om loading er false, men tenker at det ikke vil være noe problem nå som children ikke er optional lenger. 

fix: children is no longer optional

---

packages/field-group-react/README.md

Fikset skrivefeil i pakkenavn fra `@fremtind/field-group-react` til `@fremtind/jkl-field-group-react`. Feil navn resulterte i at pakken ikke ble funnet ved installering med `yarn`.

docs: fix typo

---

.github/workflows/pull_request.yml
portal/src/components/Typography/FormatProvider.tsx
portal/src/components/Typography/Typography.tsx
portal/src/components/Typography/index.ts

Bruk en godkjent tredjepartsaction for å oppdatere den samme sticky kommentaren ved preview av brancher. Gjør at forhåndsvisningskommentarer ikke ender opp med å spamme ned PRen. Gjør også at man _ikke_ får notification annet enn første gang kommentaren lages.
Tar inn det ene forslaget ditt fra en tidligere PR @piofinn, for å få en endring i portalen å teste med.

La Fremtind-bot oppdatere den samme kommentaren i pull requests

---

packages/formatters-util/documentation/Example.tsx
packages/formatters-util/documentation/InputMaskExample.tsx
packages/formatters-util/documentation/input-mask-example.scss
packages/formatters-util/src/util/parseNumber.ts
packages/formatters-util/src/util/registerWithMask.ts
packages/text-input-react/documentation/TextInput.mdx
packages/text-input-react/src/BaseInputField.tsx
packages/text-input/text-input.scss

Legg til maskert input for felter som bare trenger tusenskilletegn.

feat: add masked input for numbers

---

packages/datepicker-react/src/DatePicker.tsx
packages/datepicker-react/src/internal/Calendar.tsx
packages/datepicker-react/src/utils.ts
packages/select-react/src/NativeSelect.tsx
packages/text-input-react/src/TextInput.tsx

Vi baserer oss på å sjekke event.relatedTarget for å se om vi skal
trigge onBlur. Den er null dersom elementet som klikkes på ikke er
fokuserbart.
https://stackoverflow.com/a/42764495
Kalenderknapper er fokuserbare, men av _grunner_ så velger Safari
på macOS å ikke flytte fokus til knappen. Det slutter i stedet å
eksistere fokus. Argumentet har vært at det er sånn native-plattformen
fungerer, så f**k websiden din 🤷
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus
Det Safari derimot vil gjøre er å sende _parent_ som relatedTarget
dersom den har en tabindex, selv hvis den er -1. Ikke spør meg hvorfor.
https://codepen.io/andy-blum/pen/PoEzOwB
Vi setter tabIndex til -1 på rotnivå i datepicker så vi alltid har
en relatedTarget i Safari når det trykkes på …

fix: stopp onBlur i Safari ved klikk i input så kalender

---

packages/alert-message-react/package.json
packages/datepicker-react/package.json
packages/icon-button-react/package.json
packages/message-box-react/documentation/Example.tsx
packages/message-box-react/documentation/FormErrorMessageBoxExample.tsx
packages/message-box-react/documentation/MessageBox.mdx
packages/message-box-react/package.json
packages/message-box-react/src/FormErrorMessageBox.tsx
packages/message-box-react/src/MessageBox.tsx
packages/message-box/message-box.scss
packages/react-hooks/src/useAnimatedHeight.tsx
packages/text-input-react/package.json
portal/package.json
scripts/scaffold/templates/component-react/package.json
scripts/scaffold/templates/component/package.json
yarn.lock

Bundlestørrelsen ble altfor stor i forhold til hva vi fikk igjen.
ISSUES CLOSED: #2895

refactor: fjern framer-motion fra FormErrorMessageBox

---

packages/formatters-util/src/index.ts
packages/formatters-util/src/util/registerWithMask.ts

Typingen av options til register-funksjonene fra `registerWithMasks` var litt upresis. Her var `RegisterOptions<T>` fra react-hook-form brukt direkte, men det blir ikke riktig at `setValueAs` er med her. Dersom konsumenten sender med en verdi her, blir den ignorert. Da er det bedre å fjerne den fra typen.
- …

fix(formatters-util): bedre typing av options til register with mask

---

packages/tabs-react/src/Tabs.test.tsx
packages/tabs-react/src/Tabs.tsx

Legg til defaultTab som en prop til Tabs. Dette gjør at man kan bestemme hvilke tab som skal være valgt først, ved f.eks. retur fra skjema.

feat: add defaultTab prop to tabs

---

packages/text-input/text-input.scss

Unngå at telleren kolliderer med teksten og sørg for at textarea ekspanderer.
ISSUES CLOSED: #2931

fix: reset statisk høyde ved bruk av data-compactlayout

---

packages/formatters-util/src/util/registerWithMask.ts

Fikser en bug hvor delete og backspace inne i teksten fikk markøren til å flytte seg til enden.

fix: fix a bug where delete and backspace would reset caret position

---

packages/select-react/src/Select.tsx

Gjorde en feil ved forrige fiks. Du var nødt til å sende inn en onBlur til komponenten for at den skulle resette søket, men vi vil at den alltid skal resette seg onBlur. 

fix: always remove searchvalue onBlur

---

package.json

Unngå at sider som ikke lenger er i bruk er tilgjengelige via søkemotorer.
Bruker et globby-pattern for å beholde previews-mappa.
https://github.com/tschaub/gh-pages/blob/ef1c90d2524a51eaa2c9ecc996bb9311b6cd18eb/lib/index.js#L174
https://www.npmjs.com/package/globby
Fixes #3035 
-   [x] `yarn build` og `yarn …

chore: rydd vekk alt unntatt preview-mapper ved deploy

---

packages/text-input-react/documentation/AutosuggestExample.tsx
packages/text-input-react/src/autosuggest/Autosuggest.test.tsx
packages/text-input-react/src/autosuggest/Autosuggest.tsx
packages/text-input-react/src/autosuggest/BaseAutosuggest.tsx
packages/text-input-react/src/autosuggest/Menu.tsx
packages/text-input/_autosuggest.scss

ISSUES CLOSED: #3062
Lagt til noHits props som tar i mot et objekt som kan ta i mot text som en ReactNode, og også en fallback items liste som kan vises ved ingen treff.

feat: support fallback items on non-matching search

---

packages/core/.npmignore
packages/core/package.json

Dette er vel andre gangen jeg innfører denne feilen. Gå fra en include til en exclude. Ta med alt som ikke er config, tester, TypeScript-kilder og dokumentasjon.
https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files

chore: bytt om på hvordan pakken publiseres for å unngå rename-mishaps

---

packages/select/select.scss

Oppdaterer padding til riktige verdier

fix: bruk riktig padding på compact Select med søk

---

.github/ISSUE_TEMPLATE/ny-oppgave.md

Alt i repoet handler om Jøkul, vi trenger kanskje ikke repetere navnet vårt overalt?

fjern 'jøkul' fra "Ny oppgave" issue template

---

packages/text-input/text-input.scss

fix: la brukeren scrolle i TextArea som starter åpent

---

packages/react-hooks/documentation/IntersectionObserverExample.tsx
packages/react-hooks/documentation/index.scss
packages/react-hooks/documentation/intersectionObserver.mdx
packages/react-hooks/src/useIntersectionObserver/useIntersectionObserver.ts

La `useIntersectionObserver` ta inn flere elementer som en NodeList, slik at man enklere kan observere flere elementer samtidig.
ISSUES CLOSED: #3182

feat: la useIntersectionObserver ta inn flere elementer

---

packages/breadcrumb/breadcrumb.scss

Ikke ønsket visuelt, men beholdes som en lenke for UU.
ISSUES CLOSED: #3128

fix: fjern hovereffekt fra siste brødsmule

---

packages/validators-util/documentation/validators.mdx
packages/validators-util/src/hasNoIllegalCharacters/hasNoIllegalCharacters.test.tsx
packages/validators-util/src/hasNoIllegalCharacters/hasNoIllegalCharacters.ts
packages/validators-util/src/index.ts

Usikker på om dette var ønskelig i Jøkul, men vi bruker denne i hele kundeklienten og tenkte kanskje andre også ville ha bruk for den. 

feat: added hasNoIllegalCharacters validator

---

packages/cookie-consent/cookie-consent.scss

Når CookieConsentModal åpnast blir sida automatisk scrolla til botnen. Dette kan gjenskapast på komponentsida i portalen(https://jokul.fremtind.no/komponenter/cookieconsent). Grunnen til dette er at rot-elementet i modalen ikkje bruker position fixed. Posisjonen til elementet blir derfor der det er plassert i DOMen, som er nederst. Når modalen blir åpna blir den foksuert og nettlesaren scroller automatisk ned til det fokuserte elementet.
For å fikse dette la eg til position: fixed på rot-elementet på modalen.
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), …

fix: hindre automatisk scrolling når modal åpnes

---

packages/stylelint-config-jkl/rules/declaration.js

chore: ikke tving shorthands for grid og flex

---

packages/tooltip/tooltip.scss

Fjerner padding på knappen i `Tooltip`, slik at den ikke blir påvirket av nettleser-defaults som gjør den avlang.
Setter også `border-radius` til et høyt tall, slik at vi får en "pille" og ikke en oval _dersom_ knappen blir strukket.
ISSUES CLOSED: #3223

fix: sørg for at toltip-ikonet ikke strekkes i Safari Mobile

---

packages/alert-message/alert-message.scss

Viss man setter box-sizing: border-box på alle elementer globalt(som me gjør i SeOpp) blir ikonet på AlertMessage veldig lite på grunn av padding som blei lagt i ein nylig commit. Har endra paddingen til margin så den ikkje skal bli kalkulert med i størrelsen.

fix: gjør at ikonet får riktig størrelse hvis man globalt setter box-sizing:border-box

---

.github/workflows/pull_request.yml
actions/paths-filter/build/main.js
actions/paths-filter/src/main.ts
cypress.config.ts

Unngå dobbelt bygg av portalen. Sløser med CI-minutter. Bonus: preview kommer ut kjappere.
Miljøvariabelen `PREFIX_PATHS` [brukes av Gatsby](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/) for å legge til pathen fra `PREVIEW_PATHS` i bygg- og serve-steget.
-   [x] `pnpm build` og …

chore: gjenbruk branch preview til Cypress-tester

---

.npmrc
packages/icon-button-react/package.json
packages/icon-button-react/src/IconButton.tsx
pnpm-lock.yaml

Prøver å style en IconButton, men viss eg legger på className blir default className overridet. Burde eg merke denne som en breaking change? Viss nokon legger på className på ein IconButton kan endringen min få uønska virkningar.

feat: IconButton - gjør at custom className ikke overrider default className

---

packages/icon-button-react/src/IconButton.tsx

I forrige release avicon-button-react nettopp en bug der classNamet jkl-icon-button var forsvunnet. Wups! Fikset det her.

fix: IconButton - fikset bug der jøkul sitt className var forsvunnet

---

doc-utils/ComponentExample.tsx
doc-utils/ExampleBase.tsx
packages/table-react/documentation/Example.tsx
packages/table-react/documentation/StickyTableExample.tsx
packages/table-react/documentation/Table.mdx
packages/table-react/src/TableHead.tsx
packages/table/_table-head.scss

reverts 8a555fe to add support for
sticky heading. this is added through an optional prop, and exposing a
css variable to be able to set the background color of the head. this
defaults to the Jøkul background color

feat: add sticky table header

---

packages/table/_table-head.scss

Det ble bedre, men langt i fra fullkomment... Jeg klarte ikke å få borders til å feste seg, selv om det visst nok skal gå an å gjøre triks med `border-collapse`. Om noen vil prøve seg, er det bare å gjøre et forsøk.

fix: use box shadow as border so it stays with the sticky content

---

packages/table/_table-head.scss

dette gir mer luft mellom heading-raden og nettleseren ved scroll

fix: legg til luft over headingen

---

scripts/linker.js

chore: fiks linkerscriptet for pnpm

---

packages/expand-button/expand-button.scss

Unngår at rekkefølgen på import av core kan brekke komponenten visuelt, hvis den kom etter import av expand-button.
Selector går fra `.jkl-expand-button__arrow` til `.jkl-expand-button .jkl-expand-button__arrow`.
ISSUES CLOSED: #3323

fix: øk specificity for expand-button sin pil

---

portal/gatsby-node.js

1. Fjern hash fra output så ikke gh-pages vokser inn i evigheten.
2. Bruk en lifecycle for å bygge pages _som bruker cachen_. Reduserer byggtid lokalt fra 143s til 26s med varm cache.

chore: rigg om gatsby-bygget

---

.github/workflows/release_portal.yml

Ved endringer i portal-mappa endte vi opp med to back-to-back deploys. En for merge, og en til for versjonering. Lerna og fremtind-bot versjonerer portalen hver gang det er endringer, så sikt inn på det for publiseringen.

chore: unngå dobbelt publisering av portalen

---

.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/release_portal.yml

Via https://medium.com/emoteev-blog/10x-faster-ci-with-nx-and-github-actions-9a51fc4e82a6
Ser cachen vår har gradvist vokst til å bli problematisk. Ser ut som vi tar vare på mer enn vi bør.

chore: rekonfigurer cache keys for å unngå uendelig vekst

---

portal/src/components/UU/uu-content/liste.tsx

Førte til at Lyd og bilde-seksjonen ble duplisert (React `key`-trøbbel pga duplikater), og presenterte listeinnhold med feil overskrifter og tags.
Innført i https://github.com/fremtind/jokul/commit/3b5ade89727444ba1ee9ff8e2f6f69e8ffa424fb. 
Fant igjen riktig metadata her: https://github.com/fremtind/jokul/commit/3b5ade89727444ba1ee9ff8e2f6f69e8ffa424fb#diff-28fb5e6a5aee7cd9fba22d3406eeecdb46f2c2a69cc7554ebaa83d4faa6548a2
ISSUES CLOSED: #3316
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) …

docs: fiks feil metadata for Lister-seksjonen

---

packages/text-input/text-input.scss

Makshøyden settes uansett ved fokus
ISSUES CLOSED: #3321

fix: unngå at placeholder plasseres oppå border

---

packages/datepicker-react/src/types.ts

union types kan ikke brukes til å definere funksjoner, så med definisjonen under vil a og b bli implisitt `any` i stedet for typene definert av DatePickerChangeEventHandler.
`const handleChange: DatePickerChangeEventHandler => (a, b) => {}`
Denne PRen fikser dette, så man kan gjenbruke eventhandler definisjonene fra DatePicker.
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), …

fix: gjør typen for event handlere gjenbrukbar

---

packages/loader-react/src/Loader.test.tsx
packages/loader-react/src/Loader.tsx

fix: rett opp i feil bruk av aria-label i Loader

---

packages/select-react/src/Select.tsx

ref sin value (`<select>`) og eventet sin value var ulik, noe som forvirret react-hook-form sin validering av required
ISSUES CLOSED: #3373

fix: rett opp et synkroniseringsproblem

---

packages/footer-react/src/Footer.test.tsx
packages/select-react/documentation/SelectExample.tsx
packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx

Driv litt TDD for å forhåpentligvis unngå regresjoner som dette. Fikser de to feilene nevnt i #3421
- Ikke fyr av `onChange` ved første render hvis `value` er `undefined`.
- Unngå å havne i en loop om man endrer `value` utenfra, og har en `onChange` som setter `value` basert på `e.target.value` (som man jo gjerne har).
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skj …

fix: onChange hvis value er undefined, og render loop ved endring av value utenfra

---

packages/message-box/message-box.scss

ISSUES CLOSED: #3387
På mobil blir innholdet i messagebox smalt pga ikon og dismiss. Derfor er innholdet flytta ned under ikon og dismiss på smale skjermer (både tittel og brødtekst er flytta).

feat: legg innhold under ikon/dismiss-knapp på smale skjermer

---

packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx

Sjekk at `value` faktisk finnes i `items` før vi forsøker å sette det som `selectedValue`. Slik unngår vi en uendelig loop der vi forsøker å endre verdien mellom innsendt `value` og tom streng.
closes #3479 

Fiks feil der Select går i loop hvis innsendt verdi (value) ikke finnes i items

---

packages/select-react/package.json
packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx
pnpm-lock.yaml

Vi sjekket verdien til native-selecten før hook-form rakk å sette defaultValue
ISSUES CLOSED: https://github.com/fremtind/jokul/issues/3500

fix: select hook defaultvalue

---

.github/workflows/pull_request.yml

Legger på et -react-suffix på alle mappenavn som mangler det. uniq-filteret sørger for å unngå duplikater.
ISSUES CLOSED: #3493
```sh
CHANGED_PACKAGES=("list" "button" "button-react" "expand-button")
CHANGED_SPECS=$(printf "%s-react/**/*.spec.js\n" "${CHANGED_PACKAGES[@]/-react/}" | sort | uniq)
echo $CHANGED_SPECS
```

chore: kjør Cypress-tester ved endring i CSS-pakke

---

.github/workflows/release.yml

nx blir forvirret, muligens av at vi setter opp node på nytt før publisering til GitHub Packages
Bør fikse denne feilen:
https://github.com/fremtind/jokul/actions/runs/4913146332/jobs/8772989408

chore: restore registry før portalbygg

---

packages/toggle-switch-react/CHANGELOG.md

Retter opp noe feil beskrivelser av features og breaking changes i changeloggen til ToggleSwitch

docs: rett opp feilaktige beskrivelser i CHANGELOG

---

packages/card-react/src/InfoCard.tsx
packages/card-react/src/NavCard.tsx
packages/card-react/src/TaskCard.tsx
packages/card-react/src/types.ts
packages/card-react/src/utils.ts

Bruk padding i stedet for margin på innholdet i kort, for å unngå at marginen kollapser mot annet innhold på siden.
Kortene aksepterer nå også verdier fra den nye spacingskalaen 🎉

fix: pruk padding i stedet for margin på innholdet i kort

---

packages/react-hooks/src/useAnimatedHeight.tsx

Sørg for at vi ikke animerer elementer med useAnimatedHeight som skal starte åpne på første render

fix: ikke kjør animasjon ved første render i useAnimatedHeight

---

packages/toggle-switch-react/src/ToggleSwitch.tsx
packages/toggle-switch-react/src/useSwipeGesture.ts

```diff
- swipeHandled: import("react").MutableRefObject<false | "on" | "off">;
+ swipeHandled: MutableRefObject<"on" | "off" | false>;
// pluss MutableRefObject i importen, da
```

fix: wrap kodeeksempel i blokk, og unngå dynamisk import av react i typer

---

packages/react-hooks/documentation/AnimationBetweenExample.tsx
packages/react-hooks/documentation/AnimationExample.tsx
packages/react-hooks/documentation/AutoAnimationExample.tsx
packages/react-hooks/documentation/Example.tsx
packages/react-hooks/documentation/animation-example.scss
packages/react-hooks/documentation/animation.mdx
packages/react-hooks/src/index.ts
packages/react-hooks/src/useAnimatedHeight/index.ts
packages/react-hooks/src/useAnimatedHeight/types.ts
packages/react-hooks/src/useAnimatedHeight/useAnimatedHeight.ts
packages/react-hooks/src/useAnimatedHeight/useAnimatedHeightBetween.ts
packages/react-hooks/src/useAnimatedHeight/useAutoAnimateHeight.ts

Legger til to nye hooks i `jkl-react-hooks`:
- `useAnimatedHeightBetween` lar deg enklere animere mellom to tilstander, gitt ved å sette `data-expanded` på elementet til `true` eller `false`. Du bestemmer selv hvilke stiler elementet skal ha i de to tilstandene, og høyden animeres dersom den endrer seg.
- `useAutoAnimatedHeight` gjør det enklere å animere høyden på et element når innholdet endrer seg, men kan brukes på mer generelt grunnlag. Hooken tar inn en triggerverdi, og når denne endrer seg animeres høyden på elementet dersom den har endret seg.
-   [x] Testet …

Nye hooks for å animere mellom to høyder, eller basert på innhold

---

packages/contextual-menu-react/src/useMenuWideEvents.ts

Ved fersk boot av Jøkul kræsjer Tyepscript når den forsøker å inferre returtypen av `useMenuWideEvents`-hooken i `ContextualMenu`. Vi legger til spesifikke typer for å ungå dette.

fix: spesifiser type for eksportert hook som typescript ikke inferrer

---

packages/contextual-menu-react/documentation/ContextualMenuExample.tsx
packages/contextual-menu-react/documentation/ContextualMenuToggleSwitchExample.tsx
packages/contextual-menu-react/src/ContextualMenu.test.tsx
packages/contextual-menu-react/src/ContextualMenu.tsx

Use isOpen if you want full control over when the menu opens or closes 
Use onToggle callback if you want to track the open/closed state of the menu
ISSUES CLOSED: #3626

feat: add support for isOpen and onToggle props

---

portal/src/pages/beta.tsx

Endre redirect fra `jokul.fremtind.no/beta` slik at den peker på prodmiljøet av den nye portalen

feat: pek /beta på prodmiljøet av ny portal

---

packages/datepicker/_calendar-navigation-dropdown.scss

Not alle browsers support this but notably Edge does and coincidentally Edge also does not
properly set colors for darkmode.
ISSUES CLOSED: #3645

fix: explicitly style colors of option element

---

packages/contextual-menu-react/src/ContextualMenu.test.tsx
packages/contextual-menu-react/src/ContextualMenu.tsx
packages/tooltip-react/src/TooltipContent.tsx

I dag rendres popupene fra Tooltip og ContextualMenu ved siden av triggeren i DOMet. Det kan føre til uventet oppførsel hvis triggeren ligger inne i et element som har scroll eller som har `overflow` satt til en verdi i CSS. Under er et par eksempler fra den nye Jøkul-portalen der meny og tooltip dyttes til venstre fordi sidemenyen kan ha scroll.
Ved å rendre i en portal på "rot" (inne i `body`-elementet) vil popupene heller ta høyde for nettleservinduet når det skal beregne plassering, noe som vil gi forventet oppførsel i tilfellene over.
Måtte legge inn en liten workaround for å ta hensyn til lokal dark/light mode satt med `data-theme`, men det ser ut til å fungere fint.
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og …

Rendre TooltipContent og ContextualMenu i portaler

---

packages/tooltip-react/src/TooltipContent.tsx

Sett `jkl`-klassen på et wrapper-element for å unngå at bakgrunnsfargen i Tooltip blir overstyrt

fix: ikke la jkl-klassen overstyre bakgrunnsfarge

---

cypress/support/e2e.js

What exactly this number should be will probably be a matter of trial and error but it's becoming clear that with the current workflow setup it can't be the default of 0.01

chore: increase threshold for visual diff regression tests

---

packages/expand-button-react/src/ExpandButton.tsx
packages/expand-button-react/src/ExpandSection.test.tsx
packages/expand-button-react/src/ExpandSection.tsx
packages/expand-button/expand-button.scss

Gjort om ExpandSection til å bruke `<details>` og `<summary>` elementer slik at det ved bruk i en applikasjon som benytter SSR (feks via Remix eller Next) også vil ha funksjonalitet på plass før JS har lastet og React er mounted.

3751 expandable non js

---

packages/text-input-react/src/BaseTextInput.tsx

If no type is provided we end up having a key for "type" set to undefined and when the IconButton spreads
its rest-props to the button element it overwrites any previously set value, effectively removing it
ISSUES CLOSED: #3776

fix: make sure IconButtons have a default type of "button"

---

packages/checkbox/checkbox.scss

Checkbox midtstiller seg om label havner over flere linjer. Denne PRen legger checkbox mot toppen av label, så om label brekker over flere linjer holder den seg på toppen.

fix: align checkbox mot toppen for å støtte label over flere linjer

---

packages/table-react/src/TableFooter.tsx
packages/table/_table-row.scss

tabell-rader har en del funksjonalitet knyttet til thead. disse referansene er fjernet til fordel for .jkl-table-head for å kunne gjenbruke utseendet til en tabell, uten at det nødvendigvis er en HTML-table

fix: referer til jkl-klasser i stedet for elementer

---

packages/icon-button/icon-button.scss

While flexbox fixed the alignment for regular IconButtons it breaks it for the animated ones
ISSUES CLOSED: #3837

fix: revert display for animated icons

---

packages/formatters-util/documentation/InputMaskExample.tsx
packages/formatters-util/documentation/input-mask-example.scss
packages/formatters-util/package.json
packages/formatters-util/src/date/formatDate.test.ts
packages/formatters-util/src/date/formatDate.ts
packages/formatters-util/src/util/registerWithMask.ts
pnpm-lock.yaml

Legger til en formateringsfunksjon for innskrevne datoer, som også kan brukes med `registerWithMask`. Fungerer strålende sammen med `DatePicker` for enklere innskriving av dato.
ISSUES CLOSED: #3648
https://github.com/fremtind/jokul/assets/25739615/96ce0678-b710-411f-91c3-2e78946c7a08
-   [x] `pnpm build` og …

feat: legg til formatterer og maske for datofelter

---

packages/input-group-react/src/InputGroup.tsx
packages/select-react/src/Select.tsx

ISSUES CLOSED: #3855
Noe usikker på om dette løser issuet, men med lokal kopi av pakken (link fungerer ikke hos meg, heller ikke med `--global` flag, pnpm hoster ut en lang liste med feilmeldinger og så slutter hele greia å virke til jeg rydder opp manuelt). Det jeg uansett ser er at [InputGroupProps](https://github.com/fremtind/jokul/blob/7d2975a838a070a84bca31593dc0b80f8cc3db6e/packages/input-group-react/src/InputGroup.tsx#L15) deklareres som et interface men [eksporteres som en type](https://github.com/fremtind/jokul/blob/7d2975a838a070a84bca31593dc0b80f8cc3db6e/packages/input-group-react/src/index.ts#L2) så tenker det uansett er like ryddig at vi deklarerer det som en type i utgangspunktet.

fix: switch from exporting interfaces to exporting types

---

packages/combobox-react/src/Combobox.tsx

This makes it possible for a keyboard user to navigate past the Combobox without having to select an item
ISSUES CLOSED: #3858

fix: using tab with focus on an option no longer selects that option

---

packages/tabs-react/documentation/Example.tsx
packages/tabs-react/documentation/NavTabsExample.tsx
packages/tabs-react/src/NavTabs.tsx

Previously the NavTabs component only considered location.path which does not work with hash URLs
If you are not providing aria-selected to the active tab, either because you silenced the TS warning or are not using TS the active component will no longer have an underline
ISSUES CLOSED: #3863

fix: navTabs uses aria-selected to find active tab

---

packages/file-input-react/documentation/FileInputExample.tsx
packages/file-input-react/src/File.tsx
packages/file-input/_file.scss
packages/file-input/file-input.scss

First make sure that the layout remains correct when a File has the path prop set. Secondly, change the DOM structure so that the close icon that is present when onRemove prop is set can be interacted with. This means that now only the filename itself becomes a click target when the file has a path to avoid having nested interactive elements.
ISSUES CLOSED: #3891

fix: handle Files with path set better

---

packages/datepicker-react/src/DatePicker.test.tsx
packages/input-group-react/documentation/InputGroupExample.tsx
packages/input-group-react/src/SupportLabel.tsx

SupportLabel uses flexbox to neatly display the text content next to the icon. This fix wraps the supplied label in a div to avoid having it participate in the parents flex layout
ISSUES CLOSED: #3892

fix: handle inline elements in support labels

---

packages/button-react/documentation/Anchors.tsx
packages/button-react/documentation/ButtonExample.tsx
packages/button-react/documentation/Ghost.tsx
packages/button-react/documentation/Primary.tsx
packages/button-react/documentation/Secondary.tsx
packages/button-react/documentation/Tertiary.tsx
packages/button-react/documentation/buttons.mdx
packages/button-react/documentation/style.scss
packages/button-react/src/BaseButton.tsx
packages/button-react/src/Button.test.tsx
packages/button-react/src/Button.tsx
packages/button-react/src/index.ts
packages/button-react/src/types.ts
packages/button/button.scss
packages/card-react/src/Card.tsx
packages/contextual-menu-react/documentation/ContextualMenuExample.tsx
packages/core/src/index.ts
packages/core/src/polymorphism.ts

Ny knappekomponent, `GhostButton`
I tillegg til å legge til ny variant av knapper, er knappekomponenten bygget om med ny/endret funksjonalitet:
- **Polymorfisme**: Du kan nå bestemme hvilket element/hvilken komponent knappen skal rendres som. Trenger du en lenke? Det får du enkelt med prop-en `as="a"`.
- **Én komponent, flere varianter**: Knappene er nå én komponent, og du velger variant med en prop: `<Button variant="primary">Lagre</Button>`. (Du kan fortsatt bruke `PrimaryButton` etc. men de er bare snarveier til `Button`)
closes #3871 
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/respo …

Ny komponent: GhostButton ✨

---

packages/contextual-menu-react/documentation/ContextualMenuToggleSwitchExample.tsx
packages/contextual-menu-react/documentation/Example.tsx
packages/tooltip-react/src/TooltipTrigger.tsx

Sørger for at knappen som trigger Tooltip får riktig `aria-label` i alle tilfeller.
Bruker også Tooltip i eksempelet for ContextualMenu.

Fix tooltip trigger

---

packages/file-input-react/src/utils.ts

Gjør det mulig å sette HTTP-headere på opplastingen når du bruker `upload`-hjelpefunksjonen i `FileUpload`. Dette kan være nyttig for å f.eks. sende med CRFS-tokens.

feat: legg til mulighet for å sette headers på uploads

---

packages/text-input-react/src/index.ts

Sørger for å eksportere BaseTextArea og typer for props, på samme måte som for BaseTextInput

feat: eksporter base text area og typer

---

packages/cookie-consent-react/documentation/Example.tsx
packages/cookie-consent-react/src/CookieConsentModal.tsx

default type for buttons changed from "submit" to "button" so needs to be explicitly set now

fix: the button in the modal consent form submits again

---

packages/button-react/documentation/buttons.mdx
packages/button-react/src/Button.tsx

this is in line with how the default <button> element behaves

fix: no longer default button type to "button"

---

portal/src/layout/KBar.tsx

Gjennom søkeboksen (kbar) i portalen har vi definert noen tastatursnarveier for å gå til vanlige sider i portalen. Disse snarveiene er aktive også uten at søkeboksen er åpen. Siden snarveiene består av bokstaven "g" pluss en annen bokstav, f.eks. `g h`, er det veldig lett å trigge snarveiene ved uhell når man skriver inn tekst.
Denne PRen ~~endrer snarveiene til `⌘ + G` (`Ctrl + G` på Windows) pluss samme bokstav som tidligere~~ **fjerner snarveiene**.

fix: fjern problematiske tastatursnarveier i portalen

---

packages/hamburger-react/src/Hamburger.tsx
packages/hamburger/hamburger.scss

ISSUES CLOSED: #3948
Sørg for at `Hamburger`-komponenten er merket som deprecated i kode før vi fjerner den fra repet. Da blir det lettere å se at den ikke skal brukes. Når dette er merget, og siste versjon av pakken er publisert, kan vi slette komponenten fra repoet (se #3950).

docs: merk hamburger-komponenten som deprecated

---

packages/list-react/package.json
pnpm-lock.yaml

`list-react`-pakken avhenger av en gammel versjon av ikonene, noe som kan føre til konflikter dersom man bruker begge pakkene i samme prosjekt.

fix: oppdater til siste versjon av ikonene i list-react

---

packages/feedback-react/src/Feedback.test.tsx
packages/feedback-react/src/followup/Followup.tsx

Ensures that any UI state from e.g. textareas is cleared when the flow moves to a new step
Fixes #4001

fix: force remount of controls for new followups

---

packages/accordion/accordion.scss
packages/core/jkl/_motion.scss
packages/core/jkl/_ornaments.scss

- Legger til en hjelpe-mixin i `core` for å generere standardisert fokusindikator med `outline`
- Oppdaterer `Accordion` til å bruke nny fokusindikator
- Omrokkerer stiler i henhold til ny standard i Sass (closes #4020)

Oppdater fokusstiler i accordion

---

doc-utils/CodeBlock/CodeBlock.scss
doc-utils/component-example.scss
packages/expand-button/expand-button.scss
packages/radio-button/radio-button.scss
packages/select/select.scss

Motivation here being making it easier to track what is actually causing warnings when running the respective dev servers for other components
ISSUES CLOSED: #4017

fix: fix sass-order in components used by doc-utils

---

packages/contact-information-react/src/ContactInformation.tsx
packages/contact-information/contact-information.scss
packages/content-toggle-react/src/ContentToggle.tsx
packages/content-toggle/content-toggle.scss
packages/footer-react/src/Footer.tsx
packages/footer/footer.scss

ContactInformation, Footer og Content toggle markeres som deprecated.
Content Toggle blir kun brukt ét sted, og det er i hamburger som også har blitt fjernet :)

docs: marker komponenter som deprecated

---

packages/button/button.scss
packages/checkbox/checkbox.scss
packages/core/styles/_links.scss
packages/expand-button/expand-button.scss
packages/icon-button/icon-button.scss
packages/radio-button/radio-button.scss
packages/tabs/tabs.scss
packages/toast/toast.scss
packages/toggle-switch/toggle-switch.scss

Bruker den nye mixin-en `jkl.focus-outline` for å tegne fokusringer på komponentene som har det. Bytter også over til å bruke `:focus-visible`-selektoren [fra CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) i stedet for å sjekke `keyboard-navigation`-attributten vår.
Fikser også Sass-rekkefølge i de komponentene der det er gjort endringer.
closes #4027 
closes #4028 
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tast …

fix: bruk outline i stedet for box-shadow for fokusringer

---

packages/card-react/src/Card.tsx
packages/card-react/src/NavCard.tsx

Legger til aria-label på NavCard-komponenten, for å unngå at skjermlesere og andre støtteverktøy tar med alt innhold. I tillegg er det lagt til en tekst på clickable propen, siden det ikke er noen tittel på vanlig Card.
Lagde ikke noe issue, men det kunne jeg gjort.
-   [x] `pnpm build` og `pnpm ci:test` gir …

fix: legg til aria-label og tekst om skjermlesere på NavCard og Card

---

packages/accordion/accordion.scss
packages/core/jkl/_theme.scss

- Tar i bruk semantiske fargevariabler fra Jøkul i Accordion-komponenten
- Legger til nye mixins i core for å definere density-variabler _inne i_ klasser
- Flytter definisjonen av density-variabler i Accordion inn i klassen
**accordion.css**: 7,45 kB → 5,6 kB
**accordion.min.css**: 6,24 kB → 4,75 kB
closes #4053 

Bruk semantiske fargevariabler i Accordion

---

packages/list-react/documentation/LinkListExample.tsx
packages/list/_link-list.scss

Fikser en bug der hoverindikator  i LinkListble endret etter bytte til Material Symbols. Legger også til fokusring for elementene i LinkList.
closes #4057 

fix: riktig visning av hoverstate for linklist

---

packages/breadcrumb/breadcrumb.scss
packages/checkbox/checkbox.scss
packages/contextual-menu/_contextual-menu-divider.scss
packages/contextual-menu/_contextual-menu-item.scss
packages/contextual-menu/contextual-menu.scss
packages/core/jkl/_legacy-tokens.scss
packages/core/jkl/_tokens.scss
packages/core/src/tokens.ts
packages/core/styles/_color-tokens.scss
packages/core/styles/_legacy-tokens.scss
packages/core/styles/_tokens.scss
packages/core/tokens.less
packages/core/tokens/color/color.semantic.tokens.json
packages/expand-button/expand-button.scss
packages/feedback/feedback.scss
packages/file-input/file-input.scss
packages/input-group/_labels.scss
packages/message-box/message-box.scss
packages/modal/modal.scss
packages/progress-bar-react/package.json
packages/progress-bar/progress-bar.scss
packages/radio-button/radio-button.scss
packages/system-message/system-message.scss
packages/tabs/tabs.scss
packages/tag/tag.scss
packages/toast-react/src/Toast.tsx
packages/toast/toast.scss
packages/toggle-switch/toggle-switch.scss
packages/tooltip/tooltip.scss
pnpm-lock.yaml

- Legger til tre manglende semantiske fargevariabler, og retter opp verdien til én
- Bytter til å bruke semantiske variabler for farger i de fleste komponenter
Det er ikke byttet til semantiske variabler i
- utgående komponenter
- komponenter som bruker eller likner på TextInput (de er kompliserte nok til å ta i egen PR)

Bytt til semantiske fargevariabler i de fleste komponentene

---

packages/contact-information-react/src/ContactInformation.tsx
packages/contact-information/contact-information.scss
packages/content-toggle-react/src/ContentToggle.tsx
packages/content-toggle/content-toggle.scss
packages/footer-react/src/Footer.tsx
packages/footer/footer.scss

La merke til at noen av disse komponentene ikke ble merket som deprecated av VSCode, så har flyttet litt rundt på (og lagt til noen) warnings før vi sletter komponentene helt.

docs: flytt deprecation warnings så de synes i IntelliSense

---

packages/jokul/package.json

- Add publishConfig since scoped packages are private by default
- Add fields for homepage, repository and bugs
- Switch license from ISC to MIT
- Specify sideEffects

fix: add and fix package.json fields

---

packages/cookie-consent-react/documentation/CookieConsentModalExample.tsx
packages/cookie-consent-react/src/CookieConsentContext.test.tsx
packages/cookie-consent-react/src/CookieConsentContext.tsx
packages/cookie-consent-react/src/cookieConsentUtils.ts
packages/cookie-consent-react/src/types.ts

Fjerner unødvendige boolean-verdier i requirements. `convertBooleanToConsentValue` konverterer nå verdier korrekt.
[Issue](https://github.com/orgs/fremtind/projects/57/views/3?pane=issue&itemId=75509371)
closes #3935 

fix: rettet feil ved lagring av samtykker

---

packages/card-react/documentation/FakturainfoExample.tsx
packages/card-react/documentation/StatuskortExample.tsx
packages/card-react/src/Card.test.tsx
packages/card-react/src/Card.tsx
packages/card/card.scss

Justerer antall bakgrunnsfarger og spacinger til å matche oppdatert komponent i Figma
Fargene "inverted" og "subdued", samt spacingene "none" og "xs", er fjernet
ISSUES CLOSED: #4078

feat: oppdater card til å matche nyeste versjon i Figma

---

packages/file-input-react/src/internal/validateFile.ts

Har lagt til støtte for å ha mellomrom filtypene i accept på FileInput. Valideringa tolka `accept=".png .pdf"` og `accept=".png.pdf"` forskjellig, sjølv om nettlesaren tolker dei likt.
Denne er veldig enkelt å jobbe runudt ved å kutte ut mellomrom, men kanskje nokon andre slipper litt hodebry ein vakker dag på grunn av endringen.

fix: la til støtte for mellomrom mellom filtypene i accept strengen

---

packages/select-react/src/Select.tsx

Jeg er usikker på _hvorfor_ dette er tilfelle, men det ser ut som at TypeScript ikke liker typer som er unions av importerte typer og lokale typer. I alle fall endte Select opp med å importere typedefinisjoner med inline `import()`-statements.
Ved å endre typen for `SelectProps` tilbake til et interface ser det ut som den eksporterte typen blir riktig, med referanser til importene øverst i fila.

fix: sørg for at Select eksporterer riktige typedefinisjoner

---

packages/core/documentation/Link.mdx
packages/core/src/components/Link.tsx
packages/core/src/components/NavLink.test.tsx
packages/core/src/components/NavLink.tsx
packages/jokul/src/components/link/Link.tsx
packages/jokul/src/components/link/NavLink.test.tsx
packages/jokul/src/components/link/NavLink.tsx

Lar Link og NavLink rendres som andre HTML-elementer eller React-komponenter, som for eksempel en Link- komponent fra et routing-bibliotek.

feat: gjør Link og NavLink til polymorfe komponenter

---

packages/formatters-util/src/index.ts
packages/formatters-util/src/util/registerWithMask.ts

Bruker riktigere typer fra React Hook Form for å gi typer til hjelpefunksjonene for skjemafelter med maskering
Fjerner deprecated funksjoner for å registrere skjemafelt med maske
ISSUES CLOSED: #3763

fix: bruk bedre typer for maskeringsfunksjoner for skjema

---

packages/jokul/.eslintrc.cjs

Legger til en regel i ESLint for å catche importer av eksterne Jøkul-komponenter i `@fremtind/jokul`. De er lette å overse når man flytter kode, og kan komme seg gjennom bygget siden pakkene eksisterer lokalt i monorepoet.

chore: legg til lintregel for intern import i jokul

---

packages/file-input-react/src/File.tsx
packages/file-input-react/src/FileInput.test.tsx
packages/file-input-react/src/FileInput.tsx
packages/file-input-react/src/internal/Input.tsx
packages/file-input-react/src/internal/Thumbnail.tsx
packages/file-input-react/src/internal/fileInputContext.tsx
packages/file-input/_file.scss

fix(file-input): sync kode med figma design

---

packages/contextual-menu-react/package.json
packages/contextual-menu-react/src/ContextualMenu.tsx
packages/jokul/package.json
packages/jokul/src/components/tooltip/Tooltip.test.tsx
packages/jokul/src/components/tooltip/TooltipContent.tsx
packages/tooltip-react/package.json
packages/tooltip-react/src/Tooltip.test.tsx
packages/tooltip-react/src/TooltipContent.tsx
pnpm-lock.yaml

Bruk lazy innlasting, og en modulær versjon av `motion`-biblioteket fra Framer Motion for å redusere bundle-størrelse i komponentne som bruker dette. Tar utangspunkt i [guiden](https://www.framer.com/motion/guide-reduce-bundle-size/) på Framer sine sider.
En rask test med et tomt Vite-prosjekt ga ca. 40 kB besparelse i ferdig bundle etter endringene (før gzip)!
Legger også til støtte for flere versjoner av Framer Motion, for å unngå konflikter dersom konsumenten allerede bruker Framer Motion andre steder. Har ikke testet alle versjoner, men har testet med både laveste og høyeste tillatte versjon og det fungerer fint. Det er ingen breaking changes i API-ene som brukes mellom disse versjonene.
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) …

Reduser bundle-størrelse for Framer Motion

---

packages/jokul/src/components/tooltip/styles/tooltip.scss
packages/tooltip/tooltip.scss

ISSUES CLOSED: #4107
Legger til en utvidet trykkflate rundt ikonet til `PopupTip` som oppfyller tilgjengelighstekrav

fix: gi ikonet til PopupTip stor nok trykkflate

---

packages/contextual-menu-react/documentation/ContextualMenuExample.tsx
packages/contextual-menu-react/src/ContextualMenuItem.tsx
packages/contextual-menu/_contextual-menu-item.scss

Vi trenger mulighet for lenker i contextual menu i teamet. Har lagt til mulighet for både to og href, i tilfelle noen trenger eksterne lenker også 😺 
Lenker putta i menyen burde kanskje egentlig havne i lenkemenyen for skjermlesere, men såvidt jeg skjønner støtter kanskje ikke floating-portal det?
-   [x] …

feat: legg til mulighet for lenker i contextual menu

---

packages/button-react/documentation/ButtonExample.tsx
packages/button-react/documentation/Example.tsx
packages/button-react/documentation/Ghost.tsx
packages/button-react/documentation/Primary.tsx
packages/button-react/documentation/Secondary.tsx
packages/button-react/documentation/Tertiary.tsx
packages/button-react/documentation/buttons.mdx
packages/button-react/src/Button.test.tsx
packages/button-react/src/Button.tsx
packages/button-react/src/types.ts
packages/button/button.scss
packages/jokul/src/components/button/Button.test.tsx
packages/jokul/src/components/button/Button.tsx
packages/jokul/src/components/button/styles/button.scss
packages/jokul/src/components/button/types.ts
packages/jokul/src/core/jkl/_theme.scss
portal/src/layout/header/MainMenu.tsx

APIet til knappene er nå likere mellom kode og skisser, som forberedelse til Figma Code Connect. Gammel måte å legge til ikoner på er deprecated, men fungerer fortsatt.
`button.min.css`: ~~6,82 kB~~ -> **4,66 kB** 🎉

feat: forenkle stil og struktur i knapper og endre API

---

packages/jokul/src/components/select/Select.test.tsx
packages/jokul/src/components/select/Select.tsx
packages/jokul/src/components/tooltip/PopupTip.tsx
packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx
packages/tooltip-react/src/PopupTip.tsx

Fixes a bug where tabbing backwards out of a Select with an open listbox and a tooltip did not close the listbox
ISSUES CLOSED: #4134

fix: close Select's listbox when tooltip trigger receives focus

---

packages/jokul/src/components/accordion/styles/_index.scss
packages/jokul/src/components/button/styles/_index.scss
packages/jokul/src/components/card/styles/_index.scss
packages/jokul/src/components/combobox/styles/_index.scss
packages/jokul/src/components/cookie-consent/styles/_index.scss
packages/jokul/src/components/datepicker/styles/_index.scss
packages/jokul/src/components/expander/styles/_index.scss
packages/jokul/src/components/feedback/styles/_index.scss
packages/jokul/src/components/icon/styles/_index.scss
packages/jokul/src/components/input-group/styles/_index.scss
packages/jokul/src/components/link-list/styles/_index.scss
packages/jokul/src/components/link/styles/_index.scss
packages/jokul/src/components/modal/styles/_index.scss
packages/jokul/src/components/radio-button/styles/_index.scss
packages/jokul/src/components/select/styles/_index.scss
packages/jokul/src/components/system-message/styles/_index.scss
packages/jokul/src/components/table/styles/_index.scss
packages/jokul/src/components/table/styles/table.scss
packages/jokul/src/components/tag/styles/_index.scss
packages/jokul/src/components/text-input/styles/_index.scss
packages/jokul/src/components/toast/styles/_index.scss
packages/jokul/src/components/toggle-switch/styles/_index.scss
packages/jokul/src/components/toggle-switch/styles/toggle-switch.scss
packages/jokul/src/components/tooltip/styles/_index.scss

Legger til stiler for avhengigheten til de forskjellige komponentene i `_index.scss`-filene. Da holder det å importere f.eks. `@fremtind/jokul/styles/accordion` hvis man bare skal bruke den ene komponenten, og Sass drar automatisk inn de andre stilene dersom de ikke allerede er lastet inn annet et sted.
Har sjekket, og dette påvirker ikke felles stilark. Sass er smart nok til å inkludere stilene bare én gang når man bruker `@use` 😊
La også til manglende index-filer og stilark.

feat: inkluder stiler for avhengigheter i sass-index

---

packages/jokul/.gitignore
utils/vite/index.html
utils/vite/index.ts
utils/vite/main.tsx
utils/vite/setup-dev.ts

Legger til vite-plugin i config så man slipper å lage nye kopier av index-fila og main-fila hver gang.
Trenger da følgende `vite.dev.config.ts`
```typescript
import react from "@vitejs/plugin-react-swc";
import { resolve } from "path";
import { defineConfig } from "vite";
import { copyJklFonts, setupDev } from "../../../../../../utils/vite";
export default defineConfig({
plugins: [react(), copyJklFonts(resolve(__dirname, "public", "fonts")), setupDev(__dirname)],
});
```
På sikt tenker jeg at det skal gå å fjerne behovet for denne også, men vil prioritere å bare pløy gjennom resten av pakkene og få på plass dev-servere.

chore: helper for launching dev-servers

---

packages/jokul/src/components/flex/Flex.tsx
packages/jokul/src/components/flex/documentation/Example.tsx
packages/jokul/src/components/flex/documentation/FlexExample.tsx
packages/jokul/src/components/flex/documentation/index.html
packages/jokul/src/components/flex/documentation/main.tsx
packages/jokul/src/components/flex/documentation/vite.dev.config.ts
packages/jokul/src/components/flex/index.ts
packages/jokul/src/components/index.ts

En veldig enkel utgave av en `Flex`-komponent for enklere layout. Komponenten er polymorf.
Følgende `flex`-egenskaper er implementert:
- flex-direction
- flex-wrap
- gap
- column-gap
- row-gap
- align-items
- align-content
- justify-content
- justify-items
Gap-egenskapene godtar verdier fra spacingskalaen vår, bortsett fra `0` (som er det samme som å ikke sette verdi). Her hadde det vært fint med noen semantiske spacing-variabler på toppnivå ✨
Foreløpig ligger denne bare i `@fremtind/jokul`. Følte at det ikke ga helt mening å gå gjennom alt arbeidet med å opprette en ny pakke hvis vi uansett snart håper å være helt over på allpakka?

feat: ny nyttekomponent Flex

---

packages/button/button.scss
packages/core/jkl/_typography.scss
packages/icons/icons.scss
packages/jokul/src/components/button/styles/button.scss
packages/jokul/src/components/icon/styles/icon.scss
packages/jokul/src/core/jkl/_typography.scss

Fikser en bug der knappene hadde for stor tekst- og ikonstørrelse i kompakt modus.
Legger også til en generell tilknytning mellom tekststilene våre og ikonstørrelse (dersom størrelse ikke er satt på ikonet med props).

Riktig tekst- og ikonstørrelse på kompakte knapper

---

packages/jokul/src/components/datepicker/DatePicker.tsx

Flyttet action-proppen til å være den første i komponenten, slik at den ikke overskriver onClick-events og andre props som kommer senere.

fix: flytt action prop på topp for å unngå overskriving av props

---

packages/datepicker-react/src/DatePicker.tsx

Flytter på action prop for å unngå overskriving av props i datepicker-react pakken.

fix: flytt action prop for å unngå overskriving av props

---

packages/jokul/vite.build.config.mjs

The dts plugin has for unknown reasons suddenly decided to dump the generated files in a different subtree. This happens even with the exact same configuration and the exact same resolved version from npm so the only remaining explanation I can think of is that the amount of generated files prompted the plugin to change the output path. I can find no obvious way of telling it to do otherwise and I don't like this structure so for the time being this is a workaround

chore: copies .d.ts files to where we expect them to be

---

packages/jokul/src/components/tooltip/Tooltip.tsx

Denne fikser feilene/advarslene vi får under bygg om `useTooltip`. TL;DR: Vi burde alltid eksplisitt definere returtyper av funksjoner vi eksporterer ut fra biblioteket.

fix: definer riktig returtype for useTooltip

---

portalen/apps/cms/package.json
portalen/apps/cms/src/collections/BlogPosts.ts
portalen/apps/server/package.json
portalen/apps/web/app/entry.client.tsx
portalen/apps/web/app/entry.server.tsx
portalen/apps/web/app/root.tsx
portalen/apps/web/app/routes/$.tsx
portalen/apps/web/app/routes/_index.tsx
portalen/apps/web/app/routes/blogg.$slug.tsx
portalen/apps/web/app/routes/blogg._index.tsx
portalen/apps/web/app/routes/preview.$collection.$id.($tab).tsx
portalen/apps/web/app/routes/social-preview.tsx
portalen/apps/web/app/routes/soek.tsx
portalen/apps/web/package.json
portalen/apps/web/remix.config.js
portalen/pnpm-lock.yaml

- Oppgradert Remix til versjon 2.
- Justert bygg-oppsettet til å bruke tsc fra node_modules i root-mappen (portalen) for å sikre bruk av TypeScript versjon 5.4.5, som er nødvendig for kompatibilitet med prosjektet.

Oppgrader remix til v2

---

packages/button/button.scss
packages/jokul/src/components/button/styles/button.scss

This ensures the text stays centered even if the button is very very wide
ISSUES CLOSED: #4259

fix: button labels have the same width as the button

---

packages/jokul/src/hooks/useScreen/useScreen.ts

Ser ut som om medium og large device ikke fungerer i useScreen. 
Har ikke fått testet denne fordi det er noe som tryner under bygg lokalt, så fint om noen kan teste denne før den merges inn

fix: fikset medium og large device i useScreen

---

packages/core/jkl/_theme.scss
packages/jokul/src/core/jkl/_theme.scss

Fikser en bug der mixins for layout-density måtte angis i en spesifikk rekkefølge
closes #4277

fix: sørg for riktig spesifisitet i density-mixins

---

packages/jokul/src/components/tooltip/Tooltip.tsx
packages/jokul/src/components/tooltip/TooltipTrigger.tsx
packages/tooltip-react/src/Tooltip.tsx
packages/tooltip-react/src/TooltipTrigger.tsx

Gjør det mulig å interagere med innholdet i `PopupTip` når det er åpent. Gjør det også mulig å lukke `PopupTip` ved å klikke på spørsmålstegnet.

fix: la bruker interagere med åpent PopupTip

---

packages/jokul/src/hooks/useScreen/useScreen.ts

En ekstra parantes gjorde at ikke smallScreen fungerte

fix: fjernet ekstra parantes

---

packages/jokul/src/components/tooltip/PopupTip.tsx
packages/jokul/src/components/tooltip/Tooltip.tsx
packages/jokul/src/components/tooltip/documentation/TooltipExample.tsx
packages/tooltip-react/documentation/TooltipExample.tsx
packages/tooltip-react/src/PopupTip.tsx
packages/tooltip-react/src/Tooltip.tsx

- Eksponer `onOpenChange`-funksjonen fra FloatingUI i `Tooltip` som en prop.
- Fiks en bug introdusert i #4280 der `PopupTip` sitt ikon forble bold når man lukket tipset ved klikk på ikonet

Eksponer onOpenChange-funksjon for Tooltip

---

packages/tooltip-react/src/Tooltip.tsx

Glemte å faktisk bruke denne prop-en i den gamle React-pakka av Tooltip 😅

fix: utfør innsendt onOpenChange ved endring

---

package.json
packages/core/jkl/_convert.scss
packages/jokul/src/core/jkl/_convert.scss
pnpm-lock.yaml

Erstatter noen utdaterte, globale Sass-funksjoner med funksjoner fra de nue innebygde modulene.
closes #4300 

Erstatt bruk av utdaterte Sass-funksjoner

---

.github/workflows/pull_request.yml
package.json
packages/jokul/vite.build.config.mjs
packages/jokul/vite.test.config.mjs

Sørger for at vi kjører enhetstestene i `@fremtind/jokul`-pakkene også i actions.

Inkluder testene i jokul-pakka i GitHub Actions

---

packages/jokul/build-styles.mjs
packages/jokul/src/components/expander/styles/_index.scss

Fikser en bug der mappestrukturen inne i `styles`-mappa i komponentene i `jokul` ble fjernet når man bygget stiler. Dermed blir f.eks. `components/expander/styles/deprecated/expander.scss` flyttet til `styles/components/expander/expander.scss`, noe som vil kunne ødelegge relative importer innad i Sass-filene.

fix: sørg for at vi tar med undermapper når vi bygger stiler

---

packages/jokul/src/components/select/styles/select.scss
packages/select/select.scss

Temporarily switches back to old deprecated mixins for density as they handle cascading better
Relates to #4340

fix: makes cascading of layout density work again

---

portalen/apps/cms/src/database/postgresAdapter.ts

Det virker som Docker-miljøet ikke liker node-imports på formen `node:fs`. Forsøker å endre til kun `fs`, etc.

chore: endre import for fs og path

---

packages/datepicker-react/src/DatePicker.tsx
packages/datepicker-react/src/types.ts
packages/jokul/src/components/datepicker/DatePicker.tsx
packages/jokul/src/components/datepicker/types.ts

It's now possible to use `textInputProps` on `DatePicker` to send props directly to the component's inner `TextInput` component.

feat: allows sending props to inner TextInput

---

.github/workflows/monthly.yml

Denne har feilet siden 1. oktober 2023
https://github.com/fremtind/jokul/actions/workflows/monthly.yml
All den tid ingen har savnet den kan man jo undres på om det er verdt å fikse det men gjør det likevel :)

chore: fix list of assignees for monthly github action

---

packages/combobox-react/README.md
packages/combobox-react/documentation/Combobox.mdx

docs: fjern referanser til Tag i dokumentasjon for Combobox

---

packages/jokul/README.md
packages/jokul/package.json
packages/jokul/src/core/jkl/_convert.scss

Dette gjør det mulig å finne disse filene for bundlers som bruker `package.json`-fila for å resolve Sass-importer, som f.eks. Vite 6.
closes #4378 

Eksponer index-filer for alle stilpakkene i exports-feltet i package.json

---

packages/jokul/src/components/text-input/BaseTextInput.tsx

docs: documents limitation with maxLength on android

---

packages/jokul/src/components/select/Select.test.tsx
packages/jokul/src/components/select/Select.tsx
packages/select-react/src/Select.test.tsx
packages/select-react/src/Select.tsx

fix: returns focus to main element after selection

---

packages/jokul/src/components/table/Table.tsx
packages/jokul/src/components/table/TableHead.tsx
packages/jokul/src/components/table/tableContext.tsx
packages/table-react/src/Table.tsx
packages/table-react/src/TableHead.tsx
packages/table-react/src/tableContext.tsx

Without tab-index set somewhere meaningful on a table with a sticky header and scrollable content that content is inaccessible to users navigation with a keyboard
CLOSES #4389

fix: tables with a sticky header has tabindex

---

packages/file-input-react/documentation/FileInputExample.tsx
packages/jokul/src/components/file-input/documentation/FileInputExample.tsx

Sørg for å markere riktige filer som ferdig opplastet i eksemplet dersom noen av filene har feil eller er for store

docs: marker riktige filer som opplastet i eksemplet for filopplaster

---

packages/expandable-react/src/ExpandablePanel.tsx
packages/expandable-react/src/types.ts
packages/jokul/src/components/expander/ExpandablePanel.tsx
packages/jokul/src/components/expander/types.ts

Legger til defaultOpen, som eksisterte i Accordion

feat: legg til defaultOpen som prop i ExpandablePanel

---

packages/jokul/src/components/menu/MenuItem.tsx
packages/jokul/src/components/menu/documentation/MenuExample.tsx
packages/menu-react/documentation/MenuExample.tsx
packages/menu-react/src/MenuItem.tsx

Oppdatert ikoner, med nye eksempler for å vise dem i bruk. Det var tidligere ikke noen eksempler på nested menu.

style: Menu bruker nå Material Icons, istedenfor egne ikoner

---

packages/jokul/src/components/modal/styles/modal.scss
packages/modal/modal.scss

Having several actions (e.g. buttons) shown next to each other inside the ModalActions component is unlikely to work well on small screens, therefore they are now shown as a column on small screens and a row on medium and larger screens

fix: actions in a modal stack on small screens

---

packages/core/src/tailwind/tailwindPreset.ts
packages/jokul/src/tailwind/tailwindPreset.ts

Det viser seg at man aktivt må [deaktivere innebygde stiler/presets](https://v3.tailwindcss.com/docs/presets#disabling-the-default-configuration) fra Tailwind, selv når man bruker et custom preset som vårt. Det kan heldigvis gjøre fra inne i preset-et. Denne endringen sørger for at det gjøres.
Vi har allerede gått ut fra at dette skjedde, så ingen dokumentasjon trenger å oppdateres.

fix: deaktiver innebygde tailwind-tema i vår preset

---

packages/contextual-menu-react/package.json
packages/menu-react/package.json
pnpm-lock.yaml

Having it as a peer-dependency didn't work quite as expected and there was a chance of ending up with version 19, which does not work with React 18.
Closes #4514

fix: adds react-is as a direct dependency

---

ny-portal/package.json
ny-portal/src/app/(payload)/admin/importMap.js
ny-portal/src/collections/ComponentPages/index.ts
ny-portal/src/fields/slug/SlugComponent.tsx
ny-portal/src/fields/slug/formatSlug.ts
ny-portal/src/fields/slug/index.scss
ny-portal/src/fields/slug/index.ts
pnpm-lock.yaml

Legger til et litt mer fancy `slug`-felt hentet fra Payload sin website template, og tar det i bruk på komponentsidene.
- Genererer automatisk slug fra `title`-feltet
- Kan låses opp for å endre slug manuelt
- Sørger for unike slugs innad i en collection

Fancy slug-felt i ny portal

---

packages/jokul/src/components/table/Table.tsx
packages/jokul/src/components/table/TableHead.tsx
packages/jokul/src/components/table/tableContext.tsx
packages/table-react/src/Table.tsx
packages/table-react/src/TableHead.tsx
packages/table-react/src/tableContext.tsx

TableHead was calling a context callback during render that caused Table to update and change a state variable. Make sure this does not happend for any value of the "sticky" prop
Closes #4522

fix: no longer updates Table while rendering TableHead

---

ny-portal/src/components/Navigation/Navigation.tsx
ny-portal/src/components/Navigation/NavigationMenuButton.tsx
ny-portal/src/components/Navigation/NavigationMenuContext.tsx

Next.js klager på at en klientkomponent blir brukt på serveren når Jøkul-pakken importeres, noe som fører til feil. Oppdaterer importene for å sikre riktig bruk og forhindre krasj.

Oppdater import for å unngå feil i Next.js

---

packages/cookie-consent-react/documentation/CookieConsent.mdx
packages/cookie-consent-react/documentation/CookieConsentModalExample.tsx
packages/cookie-consent-react/src/CookieConsent.tsx
packages/cookie-consent-react/src/CookieConsentContext.tsx
packages/cookie-consent-react/src/cookieConsentUtils.ts
packages/cookie-consent-react/src/types.ts
packages/jokul/src/components/cookie-consent/CookieConsent.tsx
packages/jokul/src/components/cookie-consent/CookieConsentContext.tsx
packages/jokul/src/components/cookie-consent/cookieConsentUtils.ts
packages/jokul/src/components/cookie-consent/development/CookieConsentModalExample.tsx
packages/jokul/src/components/cookie-consent/types.ts

By using the `cookiePath` prop on `CookieConsentProvier` it is now possible to control what path the resulting cookie is saved on.
Closes #4544

feat: supports setting cookie path for cookie-consent

---

packages/jokul/build-styles.mjs

Sørger for å fjerne /styles-mappe fra importstiene til komponenter som bruker delte stiler som ligger i "shared"-mappa

fix: import av stiler i text-input og noen andre komponenter

---

packages/core/src/components/Link.tsx
packages/core/styles/_links.scss
packages/jokul/src/components/link/Link.tsx
packages/jokul/src/components/link/styles/link.scss
packages/jokul/src/components/nav-link/styles/nav-link.scss

- Sørger for at understreken oppfører seg som forventet dersom lenketeksten går over flere linjer
- Plasserer ikonet riktig (inline, etter teksten) for både Link og NavLink dersom teksten går over flere linjer
closes #4569 

Fiks plassering av understrek og ikon for lenker

---

packages/expandable-react/src/Expander.tsx
packages/jokul/src/components/expander/Expander.tsx

Fixes an error that would sometimes get thrown if the element we tried to read the height from was no longer in the DOM.

fix: checks if element exists before reading height

---

.storybook/main.ts
.storybook/preview-body.html
.storybook/preview.tsx
.storybook/theme.tsx

Legger til muligheten for å velge fargetema i Storybook-eksemplene. Legger også til mulighet for å velge bakgrunnsfarge på siden, hvor man kan velge blant fargerollene våre for bakgrunner.
https://github.com/user-attachments/assets/6abc0c16-2f7d-4694-acc5-0d2fa179649c

docs: legg til mulighet for å velge fargetema i Storybook

---

ny-portal/sanity.config.ts
ny-portal/src/app/studio/Studio.tsx
ny-portal/src/app/studio/[[...index]]/page.tsx
ny-portal/src/sanity/client.ts

- Oppdatert StudioPage (app/studio/page.tsx) til å hente disse variablene på serversiden før NextStudio rendres.
- Sørget for at sanity.config.ts forblir synkron ved å sende variabler som props til Studio.tsx.
ISSUES CLOSED: #4647

feat: legg til støtte for runtime environment variabler

---

packages/jokul/src/components/table/stories/table.stories.tsx

Utkast på ét eksempel på table stories, men ser at den henter ikke riktig styling fra sine props som f.eks fullWidth.
Work in progress :)

docs: table stories

---

.github/workflows/build-and-deploy-portal.yml

Forenkler workflowen ved å bruke GitHub Actions innebygde paths-filter i stedet for vår paths-filter implementasjon, siden paths-filter ikke støtter on: push.

 Forenklet GitHub Actions-workflow ved å bruke paths i stedet for paths-filter

---

.github/workflows/build-and-deploy-portal.yml
ny-portal/src/components/Navigation/NavigationMenu.tsx
ny-portal/src/components/Navigation/NavigationMenuGroup.tsx

- Endret title til name i NavigationMenu for å samsvare med oppdatert Sanity-query.
- La til `\` i curl-kommandoen i deploy-workflow. Nødvendig for å fortsette kommandoen på flere linjer og sikre at `-d` flagget tolkes riktig.

fix: endre title til name i navigationmenu

---

ny-portal/src/sanity/types.ts

Genererer manglende Sanity-typer. Typegen må også kjøres ved endringer i GROQ-spørringer.

fix: generer sanity typer

---

packages/file-input-react/src/File.tsx
packages/jokul/src/components/file-input/File.tsx
packages/jokul/src/components/file-input/styles/_index.scss

- Lar File-komponenten ta inn attributtene til elementet den rendres som (`div`)
- Legger til manglende stilavhengigheter for `file-input` i `jokul`-pakken
closes: #4685 

Legg til attributter fra div på File-komponenten

---

packages/checkbox/checkbox.scss
packages/jokul/src/components/checkbox/styles/checkbox.scss
packages/jokul/src/components/radio-button/styles/radio-button.scss
packages/radio-button/radio-button.scss

When using tab to navigate to a radio/checkbox that is below the viewport most browsers will scroll untill the input-control itself is in view and call it a day. In this case, that means it makes more sense to keep the hidden input control next to the visible label instead of above it.
ISSUES CLOSED: #4649
- …

fix: tabbing to radio/checkbox now scrolls it into view

---

packages/button-react/src/Button.tsx
packages/button/button.scss
packages/jokul/src/components/button/Button.tsx
packages/jokul/src/components/button/styles/button.scss

- Flytter touch-animasjon på knappene fra et pseudoelement til en gradient
- Flytter hovereffekt på knappene fra et pseudoelement til en gradient
- Fjern klasse for touch-animasjon ved animationEnd i stedet for hardkodet tid

refactor: bruk moderne CSS for animasjon og hover i knapper

---

packages/file-input-react/src/File.tsx
packages/jokul/src/components/file-input/File.tsx

Hadde glemt å spreade props på elementet. Nå tar `File` faktisk inn alle props som `div` kan ta.

fix: la File-komponenten ta inn props for div-elementet

---

ny-portal/src/components/portable-text/PortableText.tsx
ny-portal/src/components/portable-text/storybook-story/Storybook.tsx

Dette gjør forhåpentligvis at env-variabelen for Storybook-eksemplene blir plukket opp ved rendring i test- og prodmiljøene

Sørg for at Storybook-eksemplene vises i test- og prodmljøene

---

ny-portal/src/components/portable-text/PortableText.tsx
ny-portal/src/components/portable-text/code-block/CodeBlock.tsx
ny-portal/src/components/portable-text/code-block/code-block.module.scss
ny-portal/src/components/portable-text/code-block/fremtindTheme.ts
ny-portal/src/components/portable-text/code-block/fremtindThemeDark.ts
ny-portal/src/components/portable-text/code-block/index.ts
ny-portal/src/components/portable-text/link/Link.tsx
ny-portal/src/components/portable-text/list/ListItem.tsx
ny-portal/src/components/portable-text/list/OrderedList.tsx
ny-portal/src/components/portable-text/list/UnorderedList.tsx
ny-portal/src/components/portable-text/list/index.ts
ny-portal/src/components/portable-text/typography/Typography.tsx
ny-portal/src/components/portable-text/typography/typography.module.scss
ny-portal/src/sanity/extract.json
ny-portal/src/sanity/schemas/codeBlock.ts
ny-portal/src/sanity/schemas/component.ts
ny-portal/src/sanity/schemas/index.ts
ny-portal/src/sanity/types.ts

Utvider PortableText-komponenten med støtte for følgende innholdstyper:
- Typografi: legger til støtte for InlineCode og CodeBlock
- Lister: håndterer både uordnede og nummererte lister med egendefinerte komponenter
- Lenker: rendrer link-merker som egne komponenter

docs: legg til typografi, lister, lenker og kode i PortableText

---

ny-portal/src/app/(frontend)/komponenter/[slug]/component.tsx
ny-portal/src/app/(frontend)/komponenter/[slug]/components/ComponentEmptyState.tsx
ny-portal/src/app/(frontend)/komponenter/[slug]/components/ComponentFooter.tsx
ny-portal/src/app/(frontend)/komponenter/[slug]/components/ComponentHeaderLink.tsx
ny-portal/src/components/portable-text/code-block/CodeBlock.tsx
ny-portal/src/components/portable-text/link/Link.tsx
ny-portal/src/components/portable-text/list/ListItem.tsx
ny-portal/src/components/portable-text/list/OrderedList.tsx
ny-portal/src/components/portable-text/list/UnorderedList.tsx
ny-portal/src/components/site-header/menu/HamburgerButton.tsx

1. Rydder opp i en del tilfeller der vi importerer Jøkul-komponenter fra rot slik at klientsidekode blir med og skaper feil under bygg av portalen
2. Setter `use client`-direktiv på en komponent som ikke kan rendres på server
Ingen dokumentasjonsendring kreves

fix: unngå å importere klientsidekode i serverkomponenter

---

actions/paths-filter/src/main.ts

1. Fikser en import i `paths-filter` som GitHub klager over i alle PR-ene våre 😅

refactor: importer jsyaml.load som named import

---

.storybook/preview-body.html
packages/jokul/src/components/list/styles/list.scss
packages/list/list.scss

Korrigerer en layout-regresjon i \`CheckListItem\`-komponenten.
Fikser opp i layout issue i CheckListItem-komponenten. Når tekst i et listepunkt gikk over flere linjer, startet de påfølgende linjene feilaktig helt til venstre (under ikonet).
ISSUES CLOSED: #4673

fix: sikre korrekt innrykk for tekst i checklistitem

---

packages/jokul/src/components/icon-button/styles/icon-button.scss
packages/jokul/src/components/text-area/styles/text-area.scss
packages/jokul/src/components/text-input/BaseTextInput.tsx
packages/jokul/src/components/text-input/development/TextInputExample.tsx
packages/jokul/src/components/text-input/styles/text-input.scss
packages/jokul/src/shared/input/styles/shared-input-styles.scss
packages/text-input-react/src/BaseTextInput.tsx
packages/text-input/text-input.scss

Bruker semantiske fargevariabler fra core for alle farger i `text-input` og `text-area`.
Fikser også en bug der teksten i feltet hadde feil farge når feltet er ugyldig
CLOSES: #4687
Ingen dokumentasjonsendring nødvendig

refactor: bruk semantiske fargevariabler i inputfelter

---

Dockerfile

1. Nok et forsøk på fiks av Docker-fila. Definerer miljøvariabler spesifikt ut fra bygg-argumentene med `ENV`.
~~Lokalt får jeg nå en feil der `.next`-mappa ikke blir kopiert over fra byggsteget, slik at containeren feiler når den kjører opp, men det er verdt et forsøk å se om det funker på CI-serveren.~~ Dette var pga en feil i dockerfila som er fikset nå.

chore: bruk mer spesifikke env-variabler i Dockerfile

---

packages/chip-react/src/Chip.tsx
packages/jokul/src/components/chip/Chip.tsx
packages/jokul/src/components/chip/types.ts

1. Setter type="button" på Chip sin interne knapp. 
2. Oppdaterer type-definisjonen for komponenten for at TypeScript skal gi riktig autocomplete og validering av props som faktisk er gyldige for en button element.

fix: type="button" på chip sin interne knapp

---

packages/datepicker-react/src/DatePicker.tsx
packages/datepicker/datepicker.scss
packages/jokul/src/components/datepicker/DatePicker.tsx
packages/jokul/src/components/datepicker/styles/datepicker.scss
packages/jokul/src/shared/input/styles/shared-input-styles.scss
packages/text-input/text-input.scss

1. Legg til rette for å styre omriss på `text-input` fra utsiden uten å måtte gjette på variabelnavn
2. Gjør så inputfeltet i `datepicker` ikke mister omriss når datovelgeren er åpen
closes: #4750 

fix: sørg for at datepicker beholder omriss med åpen velger

---

ny-portal/src/app/(frontend)/global.scss
ny-portal/src/app/(frontend)/layout.tsx
ny-portal/src/components/site-header/SiteHeader.module.scss

1. Introdusert padding rundt hovedmenyens container og individuelle
`li`-elementer. Dette gir nødvendig luft slik at fokus-outline
blir fullt synlig og ikke kuttet av når brukeren navigerer
med tastatur.
2. Introdusert en ny `div` med klassen `.jkl-portal-layout` rett
innenfor `<body>` for å håndtere hovedlayouten. Layout-spesifikke
CSS-regler er flyttet fra `body` til denne containeren.

4752 fiks hovedlayout

---

ny-portal/src/app/(frontend)/komponenter/ComponentCard.tsx

Faller tiilbake til å bruke placeholder-bilder for komponentene i portalen mens vi finner ut hva vi gjør med Figma-bildene. Disse har feilet under bygg, slik at vi ikke har fått ut nye versjoner av portalen i test.

Fall tilbake til placeholder-bilder for komponentene i portalen

---

ny-portal/src/components/portable-text/PortableText.tsx
ny-portal/src/components/portable-text/typography/Typography.tsx

1. Fikser opp noen typefeil som krasjet byggsteget i GitHub Actions.
2. Rydder litt i kodestruktur

fix: rett opp i typer for portable text-blokker

---

ny-portal/src/components/portable-text/code-example/CodeExample.tsx
ny-portal/src/components/portable-text/props-documentation/PropsDocumentation.tsx

1. Fjern uriktig `FC`-type fra `CodeExample`- og `PropsDocumentation`-komponentene

fix: bruk riktig type for CodeExample-komponenten

---

ny-portal/next.config.mjs
ny-portal/src/app/(frontend)/page.tsx

1. Litt usikker på om jeg har løst oppgaven som tenkt – enten 1) komponentoversikten rendres på "forsiden" (det er dette jeg har gjort) eller 2)url'en skal være /komponentoversikt når siden lastes inn
2. Og så er jeg usikker på om det er en annen måte å få PortalLayout for komponentoversikten inn, uten å importere PortalLayout. Det er jo en annen layout som ligger i layout.tsx for forsiden

feat: pek på komponentoversikt på "forsiden"

---

package.json
pnpm-lock.yaml

1. Unngå typefeil fra ny React inntil videre

chore: overstyr React-versjoner for å bli kvitt typefeil

---

ny-portal/src/app/(frontend)/komponenter/ComponentGallery.tsx

1. Bruker `localStorage` for å huske foretrukket visning i komponentoversikten

feat: husk foretrukket visning i komponentoversikten

---

ny-portal/src/app/(frontend)/komponenter/komponenter.module.scss

ISSUES CLOSED: #4782
1. Fjernet knapp i listevisningen på komponentoversikten
2. Sikret at kort beskrivelse-teksten ikke forsvinner

fix: fjern knapp i listevisning på komponentoversikt

---

packages/jokul/src/components/tabs/NavTab.tsx
packages/jokul/src/components/tabs/types.ts
packages/tabs-react/src/NavTab.tsx
packages/tabs-react/src/types.ts

1. NavTab-komponenten er gjort polymorfisk slik at den støtter egendefinerte komponenter som f.eks. Link fra react-router-dom, next/link eller andre lenkekomponenter. Dette gjør det mulig for brukeren å bestemme hvilken komponent som skal rendres, og gir bedre fleksibilitet ved integrasjon i ulike rammeverk og applikasjoner.
- component-propen er fjernet og erstattet med as, som gir bedre typesikkerhet og autocompletion basert på komponenten du sender inn
- componentProps er fjernet. Bruk heller vanlige props direkte på NavTab når du bruker as.
ISSUES CLOSED: #4801
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell …

feat: gjør navtab polymorf

---

packages/jokul/src/components/table/DataTable.tsx
packages/jokul/src/components/table/ExpandableTableRow.test.tsx
packages/jokul/src/components/table/Table.tsx
packages/jokul/src/components/table/development/ActionTableExample.tsx
packages/jokul/src/components/table/development/ClickableTableExample.tsx
packages/jokul/src/components/table/development/ExpandableTableExample.tsx
packages/jokul/src/components/table/development/HeadlessTableExample.tsx
packages/jokul/src/components/table/development/MobileListTableExample.tsx
packages/jokul/src/components/table/development/MobileScrollTableExample.tsx
packages/jokul/src/components/table/development/PaginatedTableExample.tsx
packages/jokul/src/components/table/development/SortableTableExample.tsx
packages/jokul/src/components/table/development/StickyTableExample.tsx
packages/jokul/src/components/table/development/TableExample.tsx
packages/jokul/src/components/table/stories/table.stories.tsx
packages/jokul/src/components/table/types.ts
packages/table-react/documentation/ActionTableExample.tsx
packages/table-react/documentation/ClickableTableExample.tsx
packages/table-react/documentation/ExpandableTableExample.tsx
packages/table-react/documentation/HeadlessTableExample.tsx
packages/table-react/documentation/MobileListTableExample.tsx
packages/table-react/documentation/MobileScrollTableExample.tsx
packages/table-react/documentation/PaginatedTableExample.tsx
packages/table-react/documentation/SortableTableExample.tsx
packages/table-react/documentation/StickyTableExample.tsx
packages/table-react/documentation/TableExample.tsx
packages/table-react/src/DataTable.tsx
packages/table-react/src/ExpandableTableRow.test.tsx
packages/table-react/src/Table.tsx
portal/src/components/TypograhyTable/TypographyTable.tsx
portal/src/pages/kom-i-gang/utvikling.tsx

Prop caption er nå required i Table, på grunn av tilgjengelighetsforbedringer.

feat: gjort caption required i Table

---

.github/workflows/pull_request_close.yml

1. Workflowen for lukking av pull requests bruker et utdatert/avviklet runner-image fra GitHub. Denne PRen oppdaterer det til siste versjon.

chore: oppdater Ubuntu-versjon i runner for en GitHub Action

---

.storybook/density.tsx
.storybook/preview.tsx

ISSUES CLOSED: #4846
1. Legger til decorator i storybook for kontroller av density.
-   [x] Teksten i portalen er oppdatert med endringene i [Sanity](https://jokul-portal.app.devaws.fremtind.no/studio)
-   [x] [Figma-komponentene](https://www.figma.com/files/784861794507029203/project/52944370/Designsystemet?fuid=1253605757836779042) er oppdatert, og eksempler er lagt til dersom det trengd
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell utforming](https://jokul.fremtind.no/universell-utforming/testguide) …

feat: gjør det mulig å endre density i storybook

---

packages/combobox/combobox.scss
packages/jokul/src/components/combobox/styles/combobox.scss
packages/jokul/src/components/select/styles/select.scss
packages/jokul/src/shared/input/styles/shared-input-styles.scss
packages/select/select.scss
packages/text-input/text-input.scss

ISSUES CLOSED: #4837
1. Fjerner egen bakgrunnsfarge `::selection`
-   [x] Teksten i portalen er oppdatert med endringene i [Sanity](https://jokul-portal.app.devaws.fremtind.no/studio)
-   [x] [Figma-komponentene](https://www.figma.com/files/784861794507029203/project/52944370/Designsystemet?fuid=1253605757836779042) er oppdatert, og eksempler er lagt til dersom det trengd
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell utforming](https://jokul.fremtind.no/universell-utforming/testguide) …

style: fjerne egenvalgt selection-farge i input-felter

---

packages/jokul/src/components/icon/styles/_base-styles.scss
packages/jokul/src/components/icon/styles/icon.scss
packages/jokul/src/components/link/Link.tsx
packages/jokul/src/components/link/styles/link.scss

1. Trekker ut basestilene til `Icon`-komponenten i en egen mixin for enklere gjenbruk
2. Endrer ikonet for eksterne lenker til en inline-variant som knekker sammen med siste ord i lenken
**NB!** Endringene er _kun_ gjort i `@fremtind/jokul`-pakken. Lenkene fra `@fremtind/jkl-core` oppfører seg fremdeles som før.

Fiks ikon som knekker feil i eksterne lenker

---

packages/jokul/src/components/tabs/TabList.tsx
packages/jokul/src/components/tabs/stories/Tabs.stories.tsx
packages/jokul/src/components/tabs/styles/tabs.scss

Tabs tar ikke lenger bredden på innholdet, men 100% av containeren den står i, og tabs-list scroller
igjen.
ISSUES CLOSED: #4171

fix: fiks scroll i tab-list

---

packages/jokul/src/components/toast/development/ToastExample.tsx
packages/jokul/src/components/toast/toastContext.tsx
packages/jokul/src/components/toast/types.ts
packages/toast-react/src/toastContext.tsx

Adds option to programmatically close an open toast before its
timer expires or the user closes it manually. To do this, use
the `close` function from the `useToast` hook and provide the key
that was returned by `add` when the toast was created.
ISSUES CLOSED: #4869

feat: adds option to programmatically close toasts

---

packages/jokul/src/components/tabs/TabList.tsx
packages/jokul/src/components/tabs/styles/tabs.scss

Tidligere ville den aktive tabben få indikator basert på dom-logikk i react. Denne ville feile ved
overflow etter #4879 fordi left ble kalkulert feil.
Denne logikken er derfor fjernet til fordel
for en ren CSS løsning med bruk av anchor positioning. Denne har relativt god støtte, men det er
lagt inn en @supports sjekk, hvor fallback er at den aktive tabben får en tilsvarende indikator, men
som ikke er animert.
ISSUES CLOSED: #4881
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell utforming](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), …

refactor: erstatt aktiv tab indikator i react med css

---

packages/jokul/src/components/tabs/styles/tabs.scss
packages/stylelint-config-jkl/rules/at-rule.js

Legger til et unntak i stylelint for å støtte @ supports bedre i css. 
Et perfekt scenario her ville vært at stylelint så hvilken property som ble sjekka og gjorde et unntak for den. 
Siden det ikke var noen funksjonalitet for det (såvidt vi så) er det derfor heller gjort unntak for hele scopet i en @ supports sjekk.

chore: legg til stylelint regel for @supports

---

.github/workflows/release.yml
package.json

1. La `prepare`-scriptet returnere `true` hvis husky ikke kjører, som under CI

chore: oppdater prepare-script til ikke å feile uten husky

---

.github/workflows/monthly.yml
.github/workflows/release.yml

ISSUES CLOSED: #4810
1. Fjerner gammel build and deploy workflow

chore: fjern gammel build and deploy workflow

---

.github/workflows/pull_request.yml

1. Bygger en statisk versjon av Storybook som publiseres under en adresse på jokul.fremtind.no vha GitHub pages. Dette vil slutte å funke når vi peker om jokul.fremtind.no til ny portal, men da kan vi evt. lage en ny adresse vi kan bruke til previews (eller finne en helt annen løsning).

chore: preview av endringer i PR gjennom storybook

---

packages/jokul/src/components/toast/Toast.tsx
packages/jokul/src/components/toast/stories/ToastInCotext.stories.tsx
packages/jokul/src/components/toast/styles/_index.scss

1. Legg til story for toast i kontekst
2. Eksponerer toastprops fra toast.tsx

docs: Toast in context story

---

portal/src/components/portable-text/link/Link.tsx

1. Gjør at lenker i rik tekst i portalen rendres riktig.
NB! Dette gjelder _ikke_ #4800, som blir fikset i en egen PR

fix: sørg for at lenker i portable tekst rendres riktig

---

.github/workflows/release.yml

1. Sørg for å kjøre pnpm setup-action før vi forsøker å la changesets lage pr for release av pakker.

chore: la changeset bruke pnpm under release

---

.changeset/eager-trains-rule.md
packages/jokul/src/components/message/types.ts

1. Message-komponenten er forbedret til å ta imot standard HTML-attributter.
ISSUES CLOSED: #4935 

Message med støtte for flere native HTML-props

---

package.json
packages/jokul/dev-server.mjs
packages/jokul/src/components/breadcrumb/stories/Breadcrumb.stories.tsx
packages/jokul/src/components/button/stories/Button.visual.stories.tsx
playwright.config.ts
visual-regression/utils.ts
visual-regression/visual.spec.ts

1. Legger til mulighet for å gjøre visuell regresjonstesting med stories fra Storybook.

Visuell regresjonstesting med Storybook

---

.changeset/purple-rockets-see.md
portal/src/app/(frontend)/blog/ArticleCard.tsx
portal/src/app/(frontend)/blog/blog.module.scss

1. Artiklene i portalen (under punktet "Artikler") vises nå uten omriss, og med litt bedre kontroll over størrelse og avstand mellom hver artikkel i listen.

fix: litt bedre visning av artikler i portalen

---

.changeset/quiet-bats-fetch.md
packages/jokul/src/components/datepicker/internal/Calendar.tsx
packages/jokul/src/components/datepicker/stories/Datepicker.stories.tsx
packages/jokul/src/components/datepicker/styles/_index.scss

Retter en feil der man ikke kunne klikke seg til første eller siste tillatte måned i kalenderen i datovelgeren.

fix: knapper for valg av måned i kalender fungerer som forventet

---

portal/src/app/(frontend)/komponenter/ComponentCard.tsx
portal/src/app/(frontend)/komponenter/ComponentGallery.tsx

1. Reduser antall steder vi leser og setter cookies for å lagre visning i komponentoversikten.
2. Fjerner også ubrukt logikk fra komponentkortet.

fix: forenkle logikk for lagring av visning for komponenter

---

.changeset/dry-spies-greet.md
packages/jokul/src/components/link/stories/Link.stories.tsx
packages/jokul/src/components/link/styles/link.scss

1. Legger til bedre støtte for download attributten ved å vise et ikon ved siden av lenken på samme måte som external
2. Bedre alt-text på eksterne lenker ved å skrive (Åpnes i ny fane) ved siden av lenken i accessibility treet

feat: bedre støtte for nedlastingslenker

---

.changeset/rotten-groups-lick.md
packages/jokul/src/components/segmented-control/SegmentedControl.tsx
packages/jokul/src/components/segmented-control/stories/segmentedControl.stories.tsx
packages/jokul/src/components/segmented-control/styles/_index.scss
packages/jokul/src/components/segmented-control/styles/segmented-control.scss
packages/jokul/src/components/segmented-control/types.ts

Segmented Control gjør det ToggleSwitch noen ganger gjorde.
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell utforming](https://jokul.fremtind.no/universell-utforming/testguide) …

feat: ny komponent - segmented control

---

portal/src/app/(frontend)/komponenter/[slug]/component.module.scss

Fjerner listepunkter i listen med relaterte komponenter på komponentsiden
**før**
**etter**

rett opp styling på liste av relaterte komponenter

---

package.json
pnpm-lock.yaml
server.js

Ble krøll med å bruke samme logger for Next-appen og Express-serveren, så legger til en egen for serveren.

fix: bruk egen logger for express-server

---

.storybook/preview.tsx

Sørger for å initiere tablistener fra Jøkul, slik at fokusringer kun vises ved tastaturnavigasjon, ikke ved hvert klikk.
-   Closes #4788

fix: bruk tablistener i storybook for fokushåndtering

---

packages/jokul/src/components/autosuggest/stories/Autosuggest.stories.tsx

Endringen sørger for at egendefinerte verdier i `Autosuggest`-storyen blir værende etter at feltet mister fokus. Løste dette med å gjeninnfører logikken fra tidligere fungerende eksempel fra gamle portalen ved å koble `onChange` og `onInputValueChange` til en useState hook.
Ikke helt sikker på rotårsaken, men problemet ser ut til å være knyttet til hvordan Storybook håndterer tilstanden for kontrollerte komponenter. Fiksen løser iallefall symptomet og oppfører seg mer som normalt nå.
-   Closes #5163

Forhindre at Autosuggest nullstiller egendefinert verdi i stories

---

Dockerfile

Dette fikser (forhåpentligvis) bugen der ikonene ikke vises i Storybook i test og prod

fix: tilgjengeliggjør public-mappe for Storybook i prod og test

---

.storybook/global.scss
.storybook/preview-head.html

Går tilbake til gammel innlasting av ikonfonten i Storybook midlertidig slik at ikonene vises i eksemplene igjen.

fix: fiks manglende innlasting av fonter i Storybook

---

.changeset/shy-socks-travel.md
packages/jokul/src/components/image/Image.tsx

Dobbelt opp med bilder med alt-tekst = unødvendig når det er samme bilde

fix: fjerner alt-tekst fra placeholder-bilde etter innlasting

---

.changeset/famous-eels-divide.md
packages/jokul/src/components/button/Button.tsx
packages/jokul/src/components/button/stories/Button.stories.tsx
packages/jokul/src/components/button/types.ts
packages/jokul/src/components/icon-button/IconButton.tsx

- Merker IconButton og egne komponenter for Primary, Secondary, Tertiary og Ghost button som deprecated. 
- Legger også til en tekst om at Tertiary-varianten er tenkt fjernet i fremtinden fordi den ligner veldig på en lenke.

fix?: deprecation notation
