fremtind/jokul

- packages/button/example/index.tsx
- packages/footer/example/index.html
- packages/footer/example/index.tsx
- packages/header/example/index.html
- packages/header/example/index.tsx
- packages/radio-button/example/index.tsx
- packages/radio-button/package.json
- packages/text-field/example/index.tsx
- packages/text-field/package.json
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
-   [ ] I have read the [CONTRIBUTING]() doc
-   [ ] Lint and unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged …
> fix(all): various build and import errors

- package.json
Fix linting order to ensure it actually happens
> chore: fix lint order

- README.md
- packages/dropdown/dropdown.scss
- packages/dropdown/example/index.html
- packages/dropdown/example/index.tsx
- packages/dropdown/package.json
- yarn.lock
affects: @fremtind/jkl-dropdown
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
-   [ ] I have read the [CONTRIBUTING]() doc
-   [ ] Lint and unit tests pass locally with my changes
-   [ ] Any …
> feat(dropdown): adding jokul dropdown

- packages/card-react/src/Card.stories.tsx
affects: @fremtind/jkl-card-react
Update docs for Card
> docs(card-react): update card stories with more correct information

- README.md
- packages/dropdown/README.md
- packages/dropdown/dropdown.scss
- packages/dropdown/example/index.tsx
- packages/dropdown/package.json
- yarn.lock
affects: @fremtind/jkl-dropdown
ISSUES CLOSED: #31
Cleanup from hackaton, setup with downshift with inital design. Will need to move the downshift dependency, and setup pure html example and create react-wrapper in next iteration.
-   [ ] I have read the [CONTRIBUTING]() doc
-   [ ] Lint and unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules
Should we use downshift? And as a general rule, how should we approve new dependencies. And should there be a native dropdown?
> feat(dropdown): clean up from hackaton

- packages/accordion-react/example/index.html
- packages/accordion-react/example/index.tsx
- packages/accordion-react/src/Accordion.tsx
- packages/accordion-react/src/index.ts
- packages/accordion/README.md
- packages/accordion/accordion.scss
- packages/accordion/example/index.tsx
- packages/accordion/package.json
- packages/card-react/src/Card.stories.tsx
Start cleanup of code from hackathon: Refactor scss files and use more accessible elements for the react component.
More work is needed on this
> Accordion 1

- .travis.yml
- README.md
- package.json
ISSUES CLOSED: #2
add travis config file
> feat(ci): activate travis

- README.md
> docs(readme): fix build badge

- .all-contributorsrc
- README.md
Update the all-contributors badge to use rounded corners. This better matches the rest of them 😎
> docs(readme): update contributor badge

- packages/accordion-react/src/Accordion.test.tsx
- packages/accordion-react/src/Accordion.tsx
- packages/accordion-react/src/AccordionItem.test.tsx
- packages/accordion-react/src/AccordionItem.tsx
Add basic tests of `Accordion` and `AccordionItem` components
> Add tests to accordion-react

- packages/loader/README.md
- packages/loader/example/index.html
- packages/loader/example/index.tsx
- packages/loader/inline-loader.scss
- packages/loader/package.json
Added animated inline loader style. 
React wrapper is not implemented yet.
> Inline loader

- .travis.yml
- StoryTemplate.tsx
- package.json
- packages/accordion-react/src/Accordion.stories.tsx
- packages/button-react/src/Button.stories.tsx
- packages/card-react/src/Card.stories.tsx
- packages/core/package.json
- packages/divider-line-react/src/DividerLine.stories.tsx
- packages/footer-react/src/Footer.stories.tsx
- packages/footer/package.json
- packages/header-react/src/Header.stories.tsx
- packages/logo-react/src/Logo.stories.tsx
- packages/radio-button-react/src/RadioButton.stories.tsx
- packages/radio-button/package.json
- packages/storybook/tsconfig.json
- packages/text-input-react/src/TextArea.stories.tsx
- packages/text-input-react/src/TextField.stories.tsx
- packages/typography-react/src/Typography.stories.tsx
- packages/utils/package.json
- tsconfig.json
Fix deterministic build order
Move StoryTemplate to root since it will be removed
> fix(build): fix deterministic build order

- portal/package.json
> fix(portal): use --prefix-path for building gatsby docs

- gulpfile.js
- packages/accordion/accordion.scss
- packages/bullet-list/bullet-list.scss
- packages/button/button.scss
- packages/card/card.scss
- packages/checkbox/checkbox.scss
- packages/core/example/style.scss
- packages/core/mixins/_all.scss
- packages/datepicker/datepicker.scss
- packages/dropdown/dropdown.scss
- packages/footer/footer.scss
- packages/header/header.scss
- packages/radio-button/radio-button.scss
- packages/text-input/text-input.scss
- portal/src/components/Example.scss
-   [ ] I have read the [CONTRIBUTING]() doc
> Fix sass imports

- .github/pull_request_template.md
- packages/core/README.md
- packages/core/package.json
- yarn.lock
remove normalize dependecy, as we no longer use it.
> fix(core): remove dependency we no longer use, add to readme

- packages/accordion/accordion.scss
- packages/accordion/chevron-bold.svg
- packages/accordion/chevron.svg
affects: @fremtind/jkl-accordion
Update accordion style to better match sketches and generally behave better
> feat(accordion): consolidate style with sketches and remove unused svgs

- guides/GettingStarted.md
- packages/accordion-react/README.md
- packages/accordion/README.md
- portal/README.md
- portal/src/components/Menu.tsx
- portal/src/pages/components/button.tsx
- portal/src/pages/developer/contribute.tsx
- portal/src/pages/developer/getting-started.tsx
- portal/src/presentation/markdownRenderer.ts
affects: @fremtind/jkl-accordion-react, @fremtind/jkl-accordion, @fremtind/portal
add getting stared guide
add readme framework for accordion
> feat(portal): add getting started guide

- packages/datepicker-react/package.json
Specify entry points so package can be imported properly
> fix(datepicker-react): specify entry points for the package

- packages/loader-react/README.md
- packages/loader-react/example/index.html
- packages/loader-react/example/index.tsx
- packages/loader-react/package.json
- packages/loader-react/src/Loader.test.tsx
- packages/loader-react/src/Loader.tsx
- packages/loader-react/src/index.ts
- packages/loader-react/tsconfig-for-declarations.json
- packages/loader/example/index.tsx
- packages/loader/inline-loader.scss
- packages/loader/loader.scss
affects: @fremtind/jkl-loader-react, @fremtind/jkl-loader
Add React wrapper to loader.  Add negative state to loader.
Closes: #161 
> feat(loader): add react loader

- packages/loader-react/src/Loader.test.tsx
affects: @fremtind/jkl-loader-react
Add test
> test(loader): add inline test

- README.md
> docs(snyk): add badge

- .travis.yml
Notification on build posted to slack
> chore(build): add slack travis integration

- packages/dropdown/dropdown.scss
- packages/header/header.scss
- packages/text-input/text-input.scss
affects: @fremtind/jkl-dropdown, @fremtind/jkl-header, @fremtind/jkl-text-input
> fix(css): fixed import

- packages/accordion-react/README.md
- packages/accordion/README.md
- packages/browserslist-config-jkl/README.md
- packages/bullet-list-react/README.md
- packages/bullet-list/README.md
- packages/button-react/README.md
- packages/button/README.md
- packages/card-react/README.md
- packages/card/README.md
- packages/checkbox-react/README.md
- packages/checkbox/README.md
- packages/core/README.md
- packages/datepicker-react/README.md
- packages/datepicker/README.md
- packages/divider-line-react/README.md
- packages/divider-line/README.md
- packages/loader-react/README.md
- packages/loader/README.md
- packages/logo-react/README.md
- packages/logo/README.md
- packages/message-box-react/README.md
- packages/message-box/README.md
- packages/radio-button-react/README.md
- packages/radio-button/README.md
- packages/text-input-react/README.md
- packages/text-input/README.md
- packages/typography-react/README.md
affects: @fremtind/jkl-accordion-react, @fremtind/jkl-accordion, @fremtind/browserslist-config-jkl,
@fremtind/jkl-bullet-list-react, @fremtind/jkl-bullet-list, @fremtind/jkl-button-react,
@fremtind/jkl-button, @fremtind/jkl-card-react, @fremtind/jkl-card, @fremtind/jkl-checkbox-react,
@fremtind/jkl-checkbox, @fremtind/jkl-core, @fremtind/jkl-datepicker-react,
@fremtind/jkl-datepicker, @fremtind/jkl-divider-line-react, @fremtind/jkl-divider-line,
@fremtind/jkl-loader-react, @fremtind/jkl-loader, @fremtind/jkl-logo-react, @fremtind/jkl-logo,
@fremtind/jkl-message-box-react, @fremtind/jkl-message-box, @fremtind/jkl-radio-button-react,
@fremtind/jkl-radio-button, @fremtind/jkl-text-input-react, @fremtind/jkl-text-input,
@fremtind/jkl-typography-react
Update all readmes to better structure and …
> docs(readme): update all readmes

- packages/core/mixins/_all.scss
- packages/core/mixins/_motion.scss
ISSUES CLOSED: #35
Lightweight version of IBM carbons motion implementation
> feat(motion): add motion to core

- packages/checkbox-react/example/index.tsx
- packages/checkbox-react/src/Checkbox.test.tsx
- packages/checkbox-react/src/Checkbox.tsx
- packages/checkbox/checkbox.scss
- packages/checkbox/example/index.tsx
- packages/toggle-switch-react/example/index.tsx
- packages/toggle-switch-react/src/ToggleSwitch.test.tsx
- packages/toggle-switch-react/src/ToggleSwitch.tsx
- portal/src/examples/CheckboxExample.tsx
- portal/src/examples/ToggleSwitchExample.tsx
affects: @fremtind/jkl-checkbox-react, @fremtind/jkl-checkbox, @fremtind/portal
ISSUES CLOSED: #148
Now it works on Firefox 60. Should also work on most other older browser(within reason)
> fix(checkbox): fix style for older browser, add onchange handler

- packages/accordion-react/example/index.tsx
- packages/accordion/accordion.scss
> fix(accordion): make accordion 100% width

- packages/message-box-react/example/index.tsx
- packages/message-box-react/src/MessageBox.test.tsx
- packages/message-box-react/src/MessageBox.tsx
- packages/message-box-react/src/index.ts
- packages/message-box/message-box.scss
- portal/src/components/Info/WebComponentInfo.tsx
- portal/src/components/Info/style.scss
- portal/src/examples/MessageBoxExample.tsx
- portal/src/pages/components/accordion.tsx
- portal/src/pages/components/datepicker.tsx
- portal/src/pages/components/dropdown.tsx
affects: @fremtind/jkl-message-box-react, @fremtind/jkl-message-box, @fremtind/portal
- add warning level to messagebox
- add fullwidth style for messagebox with lots of content
- add documentation for it
- add web components polyfill info to portal
> feat(messagebox): add warning msgbox, add wc info in portal

- packages/datepicker-react/example/index.html
- packages/datepicker/datepicker.scss
- packages/text-input-react/example/index.scss
- packages/text-input-react/example/index.tsx
- packages/text-input-react/src/TextArea.tsx
- packages/text-input-react/src/TextField.tsx
- packages/text-input/text-input.scss
Update style of text inputs according to latest sketches
> feat(text-input): update style according to sketches

- packages/core/README.md
Clean up language a bit in core documentation. We should probably add quite a bit more information here.
> docs(core): fix typos and rephrase passages

- packages/hamburger-react/example/index.tsx
- packages/hamburger/hamburger.scss
affects: @fremtind/jkl-hamburger-react, @fremtind/jkl-hamburger
Add focusring
> fix(hamburger): add focusring on keynav

- portal/src/components/Menu/links.ts
> Typograpfi -> Typografi i venstremeny

- portal/src/texts/designer/gettingStarted.md
> Header "om jøkul"

- packages/text-input-react/src/TextArea.test.tsx
- packages/text-input-react/src/TextArea.tsx
- packages/text-input-react/src/TextField.test.tsx
- packages/text-input-react/src/TextField.tsx
- packages/text-input/text-input.scss
- Set correct total height
- Get rid of rounded corners on mobile Safari
- Add inline version
> Fix issues with text field

- portal/src/texts/core/elevation.md
> docs: clarify section about contrasting size

- packages/bullet-list/README.md
> Mer tekst, inkludert forklaring av innrykk

- packages/divider-line/README.md
> La til tekst på delelinje

- packages/accordion/README.md
Oppdatert tekst på accordions, lagt til eksempler og standarisert struktur (beskrivelse + eksempler - kan hende vi skal ha do's & dont's men har ikke det som egen header i andre komponenter)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …
> Oppdatert tekst på accordions, lagt til eksempler

- packages/checkbox/README.md
> Oppdatert tekst inkl bruk som samtykkekomponent

- packages/loader/README.md
> Tekst inkl eksempler

- packages/logo/README.md
> Mini-tweak av tekst

- packages/radio-button/README.md
> Format på tekst, kort eksempel

- packages/text-input/README.md
> Formattering, tekst og eksempler

- packages/toggle-switch/README.md
> La til tekst

- rollup.config.js
> feat(all): packages should not be inlined into each other

- packages/dropdown/README.md
> Tekst og eksempler

- packages/message-box/README.md
Endret teksten betydelig siden den ikke beskrev komponenten slik den står i dag (dette er meldingsbokser og har ikke støtte for å være midlertidige eller tidsavgrensede varsler per nå). Kan hende gammel tekst må tilbake når komponentens funksjonalitet utvides senere.
If this is a relatively large …
> Meldingsbokser

- packages/text-input-react/example/index.tsx
- packages/text-input-react/src/TextArea.tsx
- packages/text-input/text-input.scss
* Disable resize ability
* Add prop for specifying expanded rows
* Fix correct parameter type for onBlur function prop
> feat(text-input): clean up text-input

- packages/radio-button-react/example/index.html
- packages/radio-button-react/example/index.tsx
- packages/radio-button-react/src/RadioButton.tsx
- packages/radio-button/example/index.html
- packages/radio-button/radio-button.scss
> Fix radio button

- packages/dropdown-react/src/Dropdown.tsx
- packages/dropdown-react/src/Select.tsx
- packages/dropdown/dropdown.scss
Fix spacing and checvron for dropdown
> fix(dropdown): use correct chevron and fix spacing

- gulpfile.js
- portal/src/pages/components/index.tsx
> Various fixes

- packages/core/form-support-text.scss
- packages/core/headings.scss
- packages/core/mixins/_ornaments.scss
* change rotation origin for chevron
* fix correct line height and font size for support text
* fix correct font weight for H4
> Core sizing fixes

- packages/checkbox-react/example/index.tsx
- packages/checkbox-react/src/Checkbox.tsx
- packages/checkbox/checkbox.scss
- packages/checkbox/example/index.tsx
*  fix correct spacing and font sizes for checkbox
* refactor css to use class name instead of input selector
> fix(checkbox): fix correct spacing and font sizes for checkbox

- packages/message-box-react/example/index.tsx
- packages/message-box-react/src/MessageBox.tsx
- packages/message-box/message-box.scss
> fix(message-box): fix component spacing and clean up css

- packages/accordion-react/example/index.tsx
- packages/accordion-react/src/AccordionItem.tsx
- packages/accordion/accordion.scss
* Add focus state 
* Fix correct font-sizes and spacing in accordion
* Fix correct accordion placement
* Clean up and simplify css
* add initTabListener to example
> feat(accordion): add focus state to accordion

- packages/button/button.scss
- packages/card/card.scss
- packages/checkbox/checkbox.scss
- packages/core/example/style.scss
- packages/core/links.scss
- packages/core/variables/_colors.scss
- packages/datepicker/datepicker.scss
- packages/dropdown/dropdown.scss
- packages/hamburger/hamburger.scss
- packages/loader/loader.scss
- packages/logo/logo.scss
- packages/message-box/message-box.scss
- packages/radio-button/radio-button.scss
- packages/text-input/text-input.scss
- packages/toggle-switch/toggle-switch.scss
- portal/src/components/Example/Example.scss
- portal/src/components/Footer/Footer.scss
- portal/src/components/Menu/Menu.scss
- portal/src/components/icons/style.scss
- portal/src/pages/developer/contribute.scss
- portal/src/pages/profile/colors.scss
- portal/src/pages/style.scss
> chore: change norwegian letters in scss

- packages/radio-button-react/example/index.tsx
- packages/radio-button-react/package.json
- packages/radio-button-react/src/RadioButton.tsx
- packages/radio-button-react/src/RadioButtonChoice.tsx
- packages/radio-button/radio-button.scss
- portal/src/examples/RadioButtonExample.tsx
affects: @fremtind/jkl-radio-button-react, @fremtind/jkl-radio-button, @fremtind/portal
Adds error state to radiobutton
CLOSES: #341
> feat(radiobutton): add error state to radio button

- packages/datepicker-react/src/DatePicker.tsx
> feat(jkl-datepicker-react): fix loss of focus when opening datepicker

- packages/core/core.scss
- packages/table-react/CHANGELOG.md
- packages/table-react/README.md
- packages/table-react/example/index.html
- packages/table-react/example/index.scss
- packages/table-react/example/index.tsx
- packages/table-react/package.json
- packages/table-react/src/Table.tsx
- packages/table-react/src/TableData.tsx
- packages/table-react/src/TableRow.tsx
- packages/table-react/src/index.ts
- packages/table-react/tsconfig-for-declarations.json
- packages/table/README.md
- packages/table/example/index.html
- packages/table/example/index.scss
- packages/table/gulpfile.js
- packages/table/package.json
- packages/table/table.scss
- portal/src/components/Menu/links.ts
- portal/src/examples/AnchorTableExample.tsx
- portal/src/examples/TableExample.tsx
- portal/src/examples/index.ts
- portal/src/pages/components/index.tsx
- portal/src/pages/components/table.tsx
This introduces a new table component.
As a first version it is meant only as a simple data table, with support to have a row act as a link.
> New table component

- packages/accordion-react/package.json
- packages/dropdown-react/package.json
- yarn.lock
Move some dependencies from dev to normal in `dropdown` and add a missing one in `accordion`
> Fix dependencies in dropdown and accordion

- packages/table-react/example/index.tsx
- packages/table-react/src/Table.tsx
affects: @fremtind/jkl-table-react
ISSUES CLOSED: #377
Add possibility to pass classname to table component.
> feat(table-react): add className to table

- packages/button/button.scss
Changed the cursor-style from default to pointer. Closes #380 
> feat(button): change cursor from default to pointer

- packages/accordion/accordion.scss
- packages/accordion/example/index.tsx
affects: @fremtind/jkl-accordion
See #323 . This PR contains style changes to display regular page component.
-   [not appropriate] I have added tests that prove my fix is effective or that my feature works
-   [not appropriate] I have added necessary documentation (if appropriate)
I chose not to start on a full width component, because that will likely require changes in jkl-accordion-react.
> feat(accordion): implement new design for regular page component

- packages/browserslist-config-jkl/index.js
affects: @fremtind/jkl-accordion-react, @fremtind/jkl-accordion, @fremtind/browserslist-config-jkl,
@fremtind/jkl-bullet-list-react, @fremtind/jkl-bullet-list, @fremtind/jkl-button-react,
@fremtind/jkl-button, @fremtind/jkl-card-react, @fremtind/jkl-card, @fremtind/jkl-checkbox-react,
@fremtind/jkl-checkbox, @fremtind/jkl-core, @fremtind/jkl-datepicker-react,
@fremtind/jkl-datepicker, @fremtind/jkl-divider-line-react, @fremtind/jkl-divider-line,
@fremtind/jkl-dropdown-react, @fremtind/jkl-dropdown, @fremtind/jkl-field-group-react,
@fremtind/jkl-field-group, @fremtind/jkl-hamburger-react, @fremtind/jkl-hamburger,
@fremtind/jkl-loader-react, @fremtind/jkl-loader, @fremtind/jkl-logo-react, @fremtind/jkl-logo,
@fremtind/jkl-message-box-react, @fremtind/jkl-message-box, …
> feat(browserslist): update to a more sensible browserslist config

- .github/workflows/test.yml
first setup to use GitHub actions instead of Travis ci for our CI needs
> feat(ci): add GitHub action for lint and test

- .github/workflows/test.yml
The branch filter in the CI GitHub action did not work, so the action never ran. Add quotes to make it work!
> chore(ci): fix branch filter on CI action

- packages/button-react/example/index.html
- packages/button-react/example/index.scss
- packages/button-react/example/index.tsx
- packages/button-react/src/Button.test.tsx
- packages/button-react/src/Button.tsx
- packages/button/button.scss
Implement ability to force compact mode on buttons.
affects: @fremtind/jkl-button-react, @fremtind/jkl-button
> feat(button): implement forceCompact on buttons

- guides/TestGuide.md
Remove documentations about test types that we no longer have implemented.
Closes #467
> docs(portal): remove info about deleted tests

- packages/core/font.scss
explicitly set font fallback strategy to secure consistency across browsers
ISSUES CLOSED: #464
> feat(core): specify font fallback strategy

- packages/divider-line-react/package.json
- packages/dropdown-react/package.json
- yarn.lock
Upgrade `nanoid` to version v2.1.6 to avoid issues with v2.1.5. Closes #475
> Greenkeeper/default/nanoid 2.1.6

- packages/core/src/index.ts
- packages/core/src/utils/getValuePair.test.ts
- packages/core/src/utils/getValuePair.ts
- packages/core/src/utils/index.ts
- packages/dropdown-react/src/Dropdown.tsx
- packages/dropdown-react/src/Select.tsx
- packages/dropdown-react/src/SelectValuePair.ts
- packages/radio-button-react/README.md
- packages/radio-button-react/example/index.html
- packages/radio-button-react/example/index.tsx
- packages/radio-button-react/src/RadioButton.test.tsx
- packages/radio-button-react/src/RadioButton.tsx
- packages/radio-button-react/src/RadioButtonChoice.tsx
- packages/radio-button-react/src/RadioButtonOption.test.tsx
- packages/radio-button-react/src/RadioButtonOption.tsx
- packages/radio-button-react/src/RadioButtons.test.tsx
- packages/radio-button-react/src/RadioButtons.tsx
- packages/radio-button-react/src/index.ts
- packages/radio-button/example/index.html
- packages/radio-button/radio-button.scss
- portal/src/examples/RadioButtonExample.tsx
This PR should satisfy all points in, and close #388, thus making `jkl-radio-button` and `jkl-radio-button-react` ready for version 1.0.0
> Make radio button ready for v1

- packages/core/labels.scss
- packages/toggle-switch-react/README.md
- packages/toggle-switch-react/example/index.tsx
- packages/toggle-switch-react/package.json
- packages/toggle-switch-react/src/ToggleSwitch.test.tsx
- packages/toggle-switch-react/src/ToggleSwitch.tsx
- packages/toggle-switch/toggle-switch.scss
- packages/typography-react/src/SupportLabel.tsx
- portal/src/components/Menu/Menu.tsx
affects: @fremtind/jkl-toggle-switch-react, @fremtind/jkl-toggle-switch
ISSUES CLOSED: #450
Add disabled state for the toggle-switch component.
Prepare the component for v1 as per #450
> feat(toggle-switch-react): add disabled state

- packages/toggle-switch-react/package.json
affects: @fremtind/jkl-toggle-switch-react
Fixes the `jkl-typography-react` dependency so the package will build for future versions
> fix(toggle-switch-react): update dependencies

- packages/field-group-react/README.md
affects: @fremtind/jkl-field-group-react
Make the `FieldGroup` component ready for v1
closes #391
> docs(field-group-react): document usage of react component

- .github/workflows/test.yml
- .travis.yml
Furute-proofing the CI script
-   [-] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONTRIBUTING.md) doc
-   [-] `yarn build` works locally with my changes
-   [-] I have added tests that prove my fix is effective or that my feature works
-   [-] I have added necessary documentation (if appropriate)
> feat(ci): do not run CI tests on feature/release branches

- .github/workflows/deploy.yml
We'll try this again. Add a GitHub Actions workflow for deploying the portal on pushes to master.
> feat(ci): add github action for deploying the portal

- packages/accordion/accordion.scss
- packages/button/button.scss
- packages/card/card.scss
- packages/checkbox/checkbox.scss
- packages/core/mixins/_helpers.scss
- packages/core/normalize.scss
- packages/datepicker/datepicker.scss
- packages/field-group/field-group.scss
- packages/hamburger/hamburger.scss
- packages/radio-button/radio-button.scss
- packages/select/select.scss
- packages/text-input/text-input.scss
- packages/toggle-switch/toggle-switch.scss
closes #386
Remove outline reset from normalization to a mixin. Implement it on the correct components
> Focus-outline fix

- packages/core/mixins/_motion.scss
- packages/datepicker/datepicker.scss
ISSUES CLOSED: #420
Add focus state on selected day inside datepicker.
> (datepicker-react) feat: add keyboard focus state on selected day

- MIGRATION.md
Enkel dokumentasjon av påkrevde endringer for migrering til v1 av Jøkul-komponentene.
> docs: document breaking changes in v1 to ease migration

- .github/workflows/canary.yml
- .github/workflows/deploy.yml
- lerna.json
Bruker samme action som depolyer portalen til å release master til npm. Lagt under @next tagen nå så vi kan teste at vi får forventende releaser. Må byttes ut med fremtind-bot github bruker før vi kan ta inn denne PRen.
CLOSES: #351 
CLOSES: #454
> feat(release): setup release of master to next tag

- packages/accordion/accordion.scss
- packages/button/button.scss
- packages/checkbox/checkbox.scss
- packages/core/headings.scss
- packages/core/labels.scss
- packages/core/paragraphs.scss
- packages/core/variables/_font-size.scss
- packages/datepicker/datepicker.scss
- packages/radio-button/radio-button.scss
- packages/select/select.scss
- packages/table/table.scss
- packages/text-input/text-input.scss
- packages/toggle-switch/toggle-switch.scss
- packages/typography-react/example/index.tsx
- packages/typography-react/src/Typography.tsx
- packages/typography-react/src/index.ts
ISSUES CLOSED: #589
As copied from the issue, here is a screenshot of the values before and after. "Nov/Des" is the new ones.
> refactor(core): refactor to new font styles

- .github/workflows/deploy.yml
- lerna.json
> Lfbergee patch 1

- package.json
Use our fancy label with emoji (🌱 greenkeeper) instead of standard greenkeeper label
> chore(greenkeeper): use fancy label ofr greenkeeper issues/commits

- packages/accordion-react/documentation/accordion.mdx
- packages/button-react/documentation/Example.tsx
- packages/button-react/documentation/buttons.mdx
- packages/button-react/documentation/index.scss
- packages/card-react/documentation/Example.tsx
- packages/checkbox-react/documentation/Checkbox.mdx
- packages/datepicker-react/documentation/Datepicker.mdx
- packages/divider-line-react/documentation/Dividerline.mdx
- packages/field-group-react/documentation/FieldGroup.mdx
- packages/list-react/documentation/List.mdx
- packages/loader-react/documentation/Loader.mdx
- packages/logo-react/documentation/Logo.mdx
- packages/message-box-react/documentation/Example.tsx
- packages/message-box-react/documentation/MessageBox.mdx
- packages/progress-bar-react/documentation/Example.tsx
- packages/progress-bar-react/documentation/ProgessBar.mdx
- packages/radio-button-react/documentation/RadioButton.mdx
- packages/select-react/documentation/Example.tsx
- packages/select-react/documentation/Select.mdx
- packages/select-react/documentation/index.scss
- packages/table-react/documentation/Table.mdx
- packages/text-input-react/documentation/Example.tsx
- packages/text-input-react/documentation/TextInput.mdx
- packages/toggle-switch-react/documentation/ToggleSwitch.mdx
Move component documentation from the style packages to the new documentation API in the react packages.
> Migrate component documentation

- .github/workflows/pullrequest.yml
- .github/workflows/triage.yml
Fix typo in issue triage action, add triage action for pull requests
> chore(ci): add triage action for pull requests

- .github/labels.yml
- .github/workflows/pullrequest.yml
> chore(ci): move label defs to own file

- .github/labeler.yml
- .github/labels.yml
- .github/workflows/test.yml
Make sure PRs generated after release trigger all checks, and stop them from getting the `📚 documentation` tag.
> CI improvements

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/feilmelding.md
- .github/ISSUE_TEMPLATE/funksjonalitets-nske.md
Translate and update issue templates to lower treshold for using them. Also adds correct labels.
> chore(project): update issue templates

- packages/core/variables/_font-size.scss
closes #612 
Remove font-weight specification in core to make text bold in compact mode.
> fix(core): remove font-weight

- packages/button/button.scss
closes: #645 
Sett minimumsbredde på knappene til 104px (mobil/kompakt) eller 128px (desktop)
> feat(button): set minimum width for buttons

- packages/accordion-react/documentation/index.tsx
- packages/core/mixins/_motion.scss
closes #633 
Swap ease-in & ease-out
> Fix reversed timing in motion mixin

- packages/divider-line-react/package.json
- packages/divider-line-react/src/DividerLine.tsx
- packages/react-hooks/README.md
- packages/react-hooks/documentation/Example.tsx
- packages/react-hooks/documentation/IntersectionObserverExample.tsx
- packages/react-hooks/documentation/hooks.mdx
- packages/react-hooks/documentation/index.scss
- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useIntersectionObserver/useIntersectionObserver.ts
Abstraheret ut intersectionObserver inn til en egen hook, og tar den ibruk i divider line.
> Use intersection observer

- packages/react-hooks/documentation/ClickOutsideExample.tsx
- packages/react-hooks/documentation/index.scss
Løser problem i clickoutside eksemplet der referansen til click objektet ble skrevet over. Oversatt til norsk, og gjort et lite hakk penere.
> fix(react-hooks): fix click outside example

- packages/select-react/src/Select.tsx
Fikser et problem der `Select` ikke hadde initiell verdi dersom `items`-prop-en ikke var tilstede ved første render.
Closes: #693
> fix(select-react): make select set selectedValue if items change

- packages/react-hooks/README.md
Link var feil, nå er den ikke feil
> docs(react-hooks): fixed link to portal

- portal/src/texts/FrontPage.md
- portal/src/texts/frontpage/Hero.md
En forenkling av forsiden på portalen.
> Forsøk på forenkling

- portal/src/texts/profile/colors.md
> fix color code for "advarsel" in profile/colors

- packages/button-react/src/Button.test.tsx
Add missing a11y-test
Testet med VoiceOver samtidig
> test(button-react): add a11y-test

- packages/card-react/src/Card.test.tsx
affects: @fremtind/jkl-card-react
Add missing a11y-tests
> test(card-react): add a11y-tests

- packages/checkbox-react/src/Checkbox.test.tsx
affects: @fremtind/jkl-checkbox-react
> test(checkbox-react): add a11y-tests

- packages/field-group-react/src/FieldGroup.test.tsx
affects: @fremtind/jkl-field-group-react
Add a11y tests
Tested med VoiceOver
> test(field-group-react): add a11y-tests

- packages/hamburger-react/src/Hamburger.test.tsx
affects: @fremtind/jkl-hamburger-react
Add missing a11y test
Testet med VoiceOver.
> test(hamburger-react): add a11y-test

- packages/list-react/src/List.test.tsx
affects: @fremtind/jkl-list-react
> test(list-react): add a11y-tests

- packages/message-box-react/src/MessageBox.test.tsx
affects: @fremtind/jkl-message-box-react
> test(message-box-react): add a11y-tests

- packages/radio-button-react/src/RadioButtons.test.tsx
affects: @fremtind/jkl-radio-button-react
> test(radio-button-react): add a11y-tests

- packages/table-react/src/Table.test.tsx
affects: @fremtind/jkl-table-react
Add missing a11y test
> test(table-react): add a11y-test

- package.json
> chore: remove unused mkdirp dependency

- packages/button-react/documentation/Example.tsx
> fix(button-react): fix toggle-switch pressed state in button example

- package.json
- yarn.lock
GreenKeeper was having issues upgrading. I've updated yarn.lock, and tested locally. The code seems to build and test fine.
> Greenkeeper/dart sass 1.25.0

- package.json
- yarn.lock
Update jest-dom to version 5.1.1 via greenkeeper
> Greenkeeper/@testing library/jest dom 5.1.1

- package.json
- yarn.lock
Update @types/jest to 25.1.1 via greenkeeper
> Greenkeeper/@types/jest 25.1.1

- packages/button-react/src/Button.tsx
- packages/button/button.scss
La `onClick` være en valgfri prop på knappene. Legger også til muligheten for å spesifisere `type` til en av "button", "reset" eller "submit". Dette vil lette bruken av knapper både i og utenfor skjemaer.
Closes #759 
> Button fixes

- packages/core/MIGRATION.md
> docs(core): update migration guide with colors

- packages/accordion/package.json
- packages/button/package.json
- packages/card/package.json
- packages/checkbox/package.json
- packages/datepicker/package.json
- packages/divider-line/package.json
- packages/field-group/package.json
- packages/hamburger/package.json
- packages/list/package.json
- packages/loader/package.json
- packages/logo/package.json
- packages/message-box/package.json
- packages/progress-bar/package.json
- packages/radio-button/package.json
- packages/select/package.json
- packages/table/package.json
- packages/text-input/package.json
- packages/toggle-switch/package.json
affects: @fremtind/jkl-accordion, @fremtind/jkl-button, @fremtind/jkl-card, @fremtind/jkl-checkbox,
@fremtind/jkl-datepicker, @fremtind/jkl-divider-line, @fremtind/jkl-field-group,
@fremtind/jkl-hamburger, @fremtind/jkl-list, @fremtind/jkl-loader, @fremtind/jkl-logo,
@fremtind/jkl-message-box, @fremtind/jkl-progress-bar, @fremtind/jkl-radio-button,
@fremtind/jkl-select, @fremtind/jkl-table, @fremtind/jkl-text-input, @fremtind/jkl-toggle-switch
Export `.scss`-files with npm packages for more versatility.
-   [x] I have added necessary documentation (if …
> feat: export scss files with style pkgs

- packages/webfonts/webfonts.scss
affects: @fremtind/jkl-webfonts
closes #789 
> refactor(webfonts): remove local font from src

- packages/text-input-react/documentation/Example.tsx
- packages/text-input-react/src/Icons/IconClear.tsx
Tweak size of "clear" icon on the `ActionTextInput` and fix toggle switches in example.
> Text input tweaks

- portal/src/texts/profile/tone.md
FRA MARKED (+ tekst som er lagt til):
Hei!
Jeg kom på én ting mht innholdet i Designsystemet.
«stil og tone» er navnet på tone of voice i Sparebank 1. Fremtinds tone of voice heter «Stemmen vår». Jeg ønsker derfor at vi hele tiden bruker «Stemmen vår».  
Vi har i tillegg hatt et tekstløft på prinsippene i Stemmen vår.
> Stemmen Vår

- packages/core/links.scss
Add an arrow indicator to external links and links opening in a new tab or window. Also adds support for global dark theme.
> feat(links): add indicator for external links

- packages/react-hooks/src/useScreen/state.ts
> fix(react-hooks): fix check for window object in useScreen

- portal/src/components/Header/Header.tsx
- portal/src/components/Header/Header2.tsx
> Fix portal

- packages/core/core.scss
Turn off all transitions and animations when the user prefers reduced motion
> feat(core): add support for prefers-reduced-motion

- packages/logo-react/package.json
- packages/logo-react/src/Logo.tsx
affects: @fremtind/jkl-logo-react
Add missing dependency (`nanoid`) to `jkl-logo-react`
> chore(logo-react): add missing nanoid dependency

- .gitignore
Ignore IntelliJ project file when committing/pulling
> chore: add IntelliJ project file to .gitignore

- portal/src/texts/profile/picture.md
Har spisset teksten betydelig og myket opp ganske mye der jeg føler vi gikk lengre enn vi hadde bakgrunn for.
Denne teksten vil fortsatt trenger en del bildeeksempler - men tok for meg tekst nå i første omgang.
> Bildetekst

- packages/accordion-react/package.json
- packages/button-react/package.json
> Add watch to dev style

- portal/src/texts/profile/colors.md
Tweak - basert på Joachims kommentarer på Teams
(Gråvalører og bakgrunn)
> Fargetweak

- packages/button/button.scss
Fix button sizing
Closes: #842
> fix(button): use correct sizes for compact buttons

- portal/src/texts/getstarted/GettingStartedDev.md
> docs(portal): Fix minor textual errors.

- packages/datepicker/datepicker.scss
> refactor(datepicker): remove redundant width

- packages/button/button.scss
* Use correct height for normal sized buttons
* Use normal sized buttons on small screens
> fix(button): correct height for normal size button

- packages/webfonts/README.md
Clarify instructions for using compiled CSS-files.
> docs: update webfonts readme

- .eslintrc.js
- package.json
- packages/react-hooks/src/animation.tsx
- packages/react-hooks/src/useIntersectionObserver/useIntersectionObserver.ts
- packages/react-hooks/src/useKeyListener.ts
- packages/react-hooks/src/useMutationObserver/useMutationObserver.ts
- packages/select-react/src/Select.tsx
- packages/select-react/src/useListNavigation.ts
- packages/text-input-react/src/TextArea.test.tsx
- packages/text-input-react/src/TextArea.tsx
- portal/src/components/Delaytext/DelayText.tsx
- portal/src/components/Header/Header.tsx
- portal/src/components/VisibleDetector/VisibleDetector.tsx
- portal/src/contexts/themeContext.tsx
- yarn.lock
Fixes some unsafe or possibly buggy uses of hooks, and adds linting rules for hooks.
> Fix React hooks and add linting

- babel.config.js
Use new babel feature to create smaller bundles
https://babeljs.io/blog/2020/03/16/7.9.0
> feat: use new babel feature

- packages/logo-react/documentation/LogoExample.scss
- packages/logo-react/documentation/LogoExample.tsx
- packages/logo/logo.scss
> fix(logo): add width and height to jkl-logo

- packages/react-hooks/src/animation.tsx
Makes sure the animation does not play on the first render
Closes #868
> fix(animation): ensure correct behavior on first load

- packages/datepicker-react/src/DatePicker.tsx
> fix(datepicker-react): use new Date instead of undefined

- packages/datepicker-react/src/DatePicker.test.tsx
- packages/datepicker-react/src/DatePicker.tsx
> fix(datepicker-react): use effect for initialDate

- portal/src/texts/profile/tone.mdx
Fiks listeformatering i "stil og tone"-seksjonen.
> docs(profile): fix incorrect list formatting

- portal/src/texts/getstarted/PortalGuide.mdx
Oppdater dokumentasjon av hvordan man skriver dokumentasjon til portalen 🙃
> Update portal guide

- packages/select-react/documentation/Example.tsx
- packages/select/select.scss
affects: @fremtind/jkl-select-react, @fremtind/jkl-select
removed animation on the select and added more options on the example
ISSUES CLOSED: #713
I added more options to example to more clearly see a difference between selected, unselected and hover
> refactor(minor change): removed animation on the select

- packages/select-react/src/Select.tsx
Revert an undocumented breaking change in the onChange handler, to avoid errors when upgrading to latest version.
> fix(changehandlers): revert undocumented breaking change

- guides/CodeGuide.md
- portal/src/texts/getstarted/CodeGuide.mdx
> feat(added documenation): added documenation for css methodology

- packages/text-input-react/MIGRATION.md
Add migration guide from `@fremtind/jkl-text-input-react@2.x.x` to `@fremtind/jkl-text-input-react@3.x.x`
> docs(migration): document upgrade of text input components

- packages/icon-button/package.json
Vi flyttet browsers-list til rot, men ser ut til at denne glapp.
> Fjerner browsers-list

- packages/checkbox/checkbox.scss
- packages/core/labels.scss
- packages/radio-button/radio-button.scss
Adjust label spacings based on newest design changes
Closes: #893, closes: #900
> fix: adjust label spacings

- packages/datepicker-react/documentation/Datepicker.mdx
- packages/datepicker-react/documentation/Example.tsx
- packages/datepicker-react/documentation/index.tsx
- packages/datepicker-react/package.json
- packages/datepicker-react/src/Calendar.tsx
- packages/datepicker-react/src/DatePicker.test.tsx
- packages/datepicker-react/src/DatePicker.tsx
- packages/datepicker-react/src/dateFunctions.test.ts
- packages/datepicker-react/src/dateFunctions.ts
- packages/datepicker/datepicker.scss
- packages/text-input-react/src/TextInput.tsx
- yarn.lock
Oppdater Datepicker til nytt design og implementer dark mode i henhold til skisser.
Closes #854, closes #925
> Nytt utseende på DatePicker

- packages/select/select.scss
- packages/text-input/text-input.scss
Bruk riktig farge på rammene til select og text inputs
Closes #943
> Fix input border color

- .github/workflows/release.yml
Nok et forsøk på continuous release! Har litt trua denne gangen, ettersom denne versjonen har med noen triks vi ikke har prøvd før. Er testa helt frem til den faktiske release-kommandoen (`yarn release`) uten å kræsje, som så vidt jeg kan forstå betyr at vi klarer å snakke med både NPM og GitHub som @fremtind-bot  🎉
Har gitt @fremtind-bot admin-tilgang, så får vi se om det funker når dette dras inn 🤞
> chore(ci): add continuous release action

- .github/workflows/release.yml
Stop release action from triggering after a release (check for" ci skip release" in commit msg)
> chore(ci): remove infinite release loop

- packages/accordion-react/package.json
- packages/datepicker-react/package.json
- packages/select-react/package.json
Lock NRK core components to different versions to avoid a bug where they are registered to the
browser with the same name. See https://github.com/nrkno/custom-element-to-react/issues/29 
affects: @fremtind/jkl-accordion-react, @fremtind/jkl-datepicker-react, @fremtind/jkl-select-react
> chore: update nrk core dependencies to avoid bugs

- packages/datepicker/datepicker.scss
ensure calendar is shown at correct z-index
> fix(datepicker): add z-index to datepicker wrapper

- .github/workflows/release.yml
- package.json
only run the release script when there are changes from last release tag. This avoids unnecessary builds and saves time.
> feat(ci): add check for changes before running release script

- packages/core/documentation/Mixins/Mixins.scss
- packages/core/documentation/Mixins/Motion.tsx
- packages/core/documentation/mixins.mdx
Legg til dokumentasjon av mixins og funksjoner i Sass
> docs(core): add documentation of sass mixins

- .github/workflows/cypress.yml
- .gitignore
- cypress/support/checkPortalPage.js
- cypress/support/index.js
- package.json
- portal/integration/frontpage.spec.js
- portal/integration/gettingStarted.spec.js
- portal/integration/profile.spec.js
- portal/src/pages/index.tsx
- portal/src/texts/frontpage/Hero.md
- yarn.lock
> test(portal): add integration test

- portal/src/components/Layout/Layout.scss
Fixes background regression after merge of menu
> docs: fix bg regression for ff

- portal/src/components/Header/components/FullScreenMenuItem.scss
- portal/src/components/Header/header.scss
- portal/src/components/Layout/Layout.scss
Oppdatertil mer fornuftige marginer på mobil
> fix(portal): adjust margins and font sizes on mobile

- packages/core/src/components/Label.tsx
Åpne opp for å sette klasse på label komponenten
> fix(label): add classname prop

- portal/src/components/Documentation/Typography/TypograhyTable/ExampleRow.tsx
- portal/src/components/Documentation/Typography/TypograhyTable/TableCell.tsx
- portal/src/components/Documentation/Typography/TypograhyTable/TableHeader.tsx
- portal/src/components/Documentation/Typography/TypograhyTable/TypographyTable.scss
- portal/src/components/Documentation/Typography/TypograhyTable/index.tsx
- portal/src/texts/profile/typography.mdx
Oppdatert typografi under profilen vår med ny visning og tekst
Closes: #1014
> docs: add typography section in portal

- packages/portal-components/src/FlowExample.tsx
affects: @fremtind/jkl-portal-components
Fikser en liten advarsel i lint som har irritert meg 😅
> fix(flow-example): add missing dependency to callback

- packages/validations-util/README.md
- packages/validations-util/documentation/Example.tsx
- packages/validations-util/documentation/IsValidChassisnummerExample.tsx
- packages/validations-util/documentation/IsValidEpostExample.tsx
- packages/validations-util/documentation/IsValidRegistreringsnummerExample.tsx
- packages/validations-util/documentation/IsValidTelefonnummerExample.tsx
- packages/validations-util/documentation/index.html
- packages/validations-util/documentation/index.tsx
- packages/validations-util/documentation/validators.mdx
- packages/validations-util/package.json
- packages/validations-util/src/index.ts
- packages/validations-util/src/isValidChassisnummer/isValidChassisnummer.test.ts
- packages/validations-util/src/isValidChassisnummer/isValidChassisnummer.ts
- packages/validations-util/src/isValidEpost/isValidEpost.test.tsx
- packages/validations-util/src/isValidEpost/isValidEpost.ts
- packages/validations-util/src/isValidRegistreringsnummer/isValidRegistreringsnummer.test.ts
- packages/validations-util/src/isValidRegistreringsnummer/isValidRegistreringsnummer.ts
- packages/validations-util/src/isValidTelefonnummer/isValidTelefonnummer.test.tsx
- packages/validations-util/src/isValidTelefonnummer/isValidTelefonnummer.ts
- packages/validations-util/tsconfig-for-declarations.json
- portal/gatsby-node.js
affects: @fremtind/jkl-validators-util, @fremtind/portal
> feat(a validators utils package): a validators utils package

- packages/core/documentation/Typography/Typography.scss
- packages/core/documentation/Typography/Typography.tsx
fix table showing typography mixins/classes
> docs(core): fix table showing typography mixins/classes

- .github/workflows/cypress.yml
- .github/workflows/portal.yml
- cypress.json
- package.json
- portal/package.json
> chore: add yarn cache to cypress and portal action

- packages/checkbox-react/documentation/Example.tsx
- packages/checkbox-react/src/Checkbox.test.tsx
- packages/checkbox-react/src/Checkbox.tsx
- packages/checkbox/checkbox.scss
- packages/radio-button-react/documentation/Example.tsx
- packages/radio-button-react/src/RadioButtonOption.tsx
- packages/radio-button-react/src/RadioButtons.test.tsx
- packages/radio-button/radio-button.scss
affects: @fremtind/jkl-checkbox-react, @fremtind/jkl-checkbox, @fremtind/jkl-radio-button-react,
@fremtind/jkl-radio-button
ISSUES CLOSED: #986, #985
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you …
> feat(responsive radio/checkbox label): better responsive labels

- cypress/support/checkPortalPage.js
- portal/src/components/CodeBlock/CodeBlock.scss
- portal/src/components/CodeBlock/CodeBlock.tsx
- portal/src/texts/profile/picture.mdx
- portal/src/texts/profile/principle.mdx
Aktiver tester for tilgjengelighet via `cypress-axe` i portalens integrasjonstest. PRen fikser også noen små feil for å få testene til å passere.
> Tilgjengelighetstester i portalen

- portal/src/components/Documentation/Colors/ColorDescription.scss
- portal/src/components/Documentation/Colors/Colors.scss
- portal/src/components/Documentation/Colors/Colors.tsx
- yarn.lock
Use the new color util-classes in the color documentation
> docs(profile): update color docs to use new util classes

- portal/package.json
- portal/src/components/Layout/Layout.tsx
- yarn.lock
> chore: update react-helmet

- portal/integration/gettingStarted.spec.js
- portal/src/texts/getstarted/MobileGuide.mdx
> docs(mobile docs): mobile docs break-points responsive mm

- portal/integration/frontpage.spec.js
should make the tests a bit more stable
> test: add timeout to front page test

- portal/src/texts/blog/iePlussJokulErlikSant/iePlussJokulErlikSant.mdx
Jeg har prøvd å samle det vi lærte fra å få BM til å støtte IE 11 i en bloggpost. Pls give feedback
> IE 11 bloggpost

- portal/src/components/Delaytext/DelayText.tsx
- portal/src/components/VisibleDetector/VisibleDetector.tsx
- portal/src/pages/index.tsx
Fix types in portal front page components to increase type safety and appease the linter
> refactor(portal): add correct types to portal fromt page components

- portal/src/components/Header/useNavigationLinks.tsx
- portal/src/pages/index.tsx
Sørge for at siste blogpost blir listet på forsiden, og at menyen og sidemenyen lister postene i riktig rekkefølge.
> docs(portal): make sure blog is ordered by date

- portal/src/texts/blog/updates/august2020.mdx
> docs: add summer of 2020 blog post

- packages/react-hooks/src/useScreen/state.ts
> chore: export interface for useScreen

- packages/accordion/accordion.scss
affects: @fremtind/jkl-accordion
Fjerner den lille bouncen ved klikk og farge transisjonen på pila (som jeg fortsatt ikke forstår at du klarer å se @Steinop )
> fix(accordion): remove active bounce

- packages/core/documentation/Example.tsx
- packages/core/links.scss
Oppdatering av designet på lenkene i henhold til nye skisser.
> Oppdatert design på lenker

- package.json
- packages/accordion-react/package.json
- packages/select-react/package.json
- patches/@nrk+core-datepicker+3.0.8.patch
- patches/@nrk+core-toggle+3.0.7.patch
- patches/@nrk+core-toggle+3.0.8.patch
- rollup.config.js
- yarn.lock
Patcher noen av bugsa i `core-components` vha. [`patch-package`](https://github.com/ds300/patch-package). Dette betyr også at disse avhengighetene igjen må inlines i koden, slik at vi får noe større pakker i de komponentene det er snakk om.
Foreløpig fikset:
- ✅ Komponentene får nå riktige tagnavn (f.eks. `<core-toggle>`) selv i produksjon (https://github.com/nrkno/custom-element-to-react/pull/176)
- ✅ Man kan nå bruke `data-for`-attributten på en knapp for å kontrollere en `core-toggle` (https://github.com/nrkno/core-components/pull/484)
- ✅ Man kan nå navigere til en måned i Datepicker der det er disabled noen datoer (#772, https://github.com/nrkno/core-components/pull/391)
-   [x] …
> Patch NRK core components

- package.json
- portal/package.json
- portal/static/CNAME
Fix integration tests, and add CNAME file to hopefully fix redirects
> Fixes to new build process

- packages/text-input-react/documentation/Autosuggest.mdx
- packages/text-input-react/documentation/AutosuggestExample.tsx
- packages/text-input-react/documentation/index.tsx
- packages/text-input-react/package.json
- packages/text-input-react/src/autosuggest/Autosuggest.test.tsx
- packages/text-input-react/src/autosuggest/Autosuggest.tsx
- packages/text-input-react/src/autosuggest/BaseAutosuggest.tsx
- packages/text-input-react/src/autosuggest/ControllerButton.tsx
- packages/text-input-react/src/autosuggest/Menu.tsx
- packages/text-input-react/src/autosuggest/index.ts
- packages/text-input-react/src/autosuggest/utils.ts
- packages/text-input-react/src/index.ts
- packages/text-input/autosuggest.scss
- packages/text-input/text-input.scss
- portal/gatsby-browser.js
- portal/src/components/Experimental/Experimental.tsx
- portal/src/components/Typography/FormatProvider.tsx
- rollup.config.js
- yarn.lock
affects: @fremtind/jkl-autosuggest-react, @fremtind/jkl-autosuggest, @fremtind/portal
Løftet ut autosuggest av klient. Implementer med downshift. Oppdaterte til nyeste downshift, men har ikke tatt i bruk alle de nye kule hooksa.
> feat(autosuggest): add autosuggest component

- portal/src/texts/blog/updates/september2020.mdx
> September update post

- jest/jest.core.js
- package.json
- packages/accordion-react/package.json
- packages/datepicker-react/package.json
- packages/select-react/package.json
- patches/@nrk+core-datepicker+3.0.8.patch
- patches/@nrk+core-toggle+3.0.8.patch
- rollup.config.js
Make sure we actually bundle NRK Core Components, with our patches, in the exported code.
affects: @fremtind/jkl-accordion-react, @fremtind/jkl-datepicker-react, @fremtind/jkl-select-react
> fix: actually bundle nrk core components

- packages/text-input-react/src/autosuggest/BaseAutosuggest.tsx
- packages/text-input-react/src/autosuggest/ControllerButton.tsx
- packages/text-input/autosuggest.scss
uses search icon and moves the menu list above help text
> fix(text-input): uses search icon

- packages/hamburger/README.md
Min største commit hittil.
jlk --> jkl
> Update readme for jkl-hamburger

- codeql-analysis.yml
Enable Githubs CodeQL to analyze our code for errors and potential security issues
For now its just a test to see if this does something useful for us.
> chore: add code quality check

- portal/src/texts/blog/updates/october2020.mdx
> Oppdateringspost

- portal/src/components/Documentation/Colors/ColorTable.tsx
- portal/src/components/Documentation/Colors/Colors.tsx
- portal/src/components/Documentation/Typography/TypograhyTable/ExampleRow.tsx
- portal/src/texts/profile/colors.mdx
- portal/src/utils/getComputedProperty.ts
changed from hardcoded color to picking out the color using getComputedProperty
ISSUES CLOSED: #1399
> docs(colors): get color from element

- portal/src/components/Documentation/Colors/ColorTable.tsx
- portal/src/components/Documentation/Colors/Colors.tsx
Bruk utregnede verdier i stedet for hardkodete i fargetabellene i portalen.
ISSUES CLOSED: #1433
> docs(colors): change color tables to use computed color values

- packages/react-hooks/src/useClickOutside.ts
- packages/react-hooks/src/useFocusOutside.ts
- packages/react-hooks/src/useScrollIntoView/useScrollIntoView.tsx
A more readable code since you're using a newer typescript version.
> refactor(hooks): use optional chaining

- packages/text-input/README.md
> docs: update text-input header

- portal/src/components/Layout/Layout.tsx
probably a regression from when we changed to use the old style of layout
> fix(portal): fix title

- packages/constants-util/README.md
- packages/constants-util/documentation/Constants.mdx
- packages/constants-util/documentation/Example.tsx
- packages/constants-util/documentation/index.html
- packages/constants-util/documentation/index.tsx
- packages/constants-util/documentation/style.scss
- packages/constants-util/package.json
- packages/constants-util/src/index.ts
- packages/constants-util/src/unicode.ts
- packages/constants-util/tsconfig-for-declarations.json
- portal/src/components/Card/Card.tsx
✨ Constant pakke
Per nå en del nyttige unicode verdier, kan utvides med mer senere.
affects: @fremtind/jkl-constants-util, @fremtind/portal
ISSUES CLOSED: #1499
> feat(constants): add constants package

- packages/constants-util/src/unicode.ts
affects: @fremtind/jkl-constants-util
Lagt til pil venstre, opp og ned.
> feat: add more arrows

- .codesandbox/ci.json
Dagens sandbox har veldig lite innhold, og dermed veldig liten verdi. Ny sandboks inneholder en god del flere kompnenter, flere kommer fortløpende. På sikt vil også flere props være overstyrbare, så man kan feks sjekke kompnentene i darkmode. Alle disse forbedringene kan gjøres forløpende i sandboxen, uten at det må gjøres endringer i jøkul
> chore: add more complete codesandbox example

- .github/workflows/cypress.yml
> chore(cypress): update cypress action

- portal/src/texts/blog/updates/november2020.mdx
> docs(blog): november update

- packages/datepicker-react/src/Calendar.tsx
- packages/select-react/src/NativeSelect.tsx
- packages/select-react/src/Select.tsx
- (feat) Add width prop to NativeSelect
- (fix) Move `style={{ width }}` to correct div in Select
- (fix) Add `width="auto"` to NativeSelect in datepicker
> (feat): nativeselect width, (fix): calendar nativeselect width, (fix): select width

- portal/src/components/DownloadAsset/DownloadAsset.tsx
- portal/src/texts/profile/logo.mdx
Fikser lenkene for nedlasting av logo (ble lastet ned som tekstfiler med filnavnet).
> fix(portal): fix logo download links

- portal/src/texts/getstarted/TestGuideUU.mdx
fix wrong shortcut in screen reader guide
> docs: fix shortcut

- packages/core/documentation/Example.tsx
- packages/core/documentation/Link/NavLinkExample.tsx
- packages/core/links.scss
- packages/core/src/components/NavLink.tsx
Some cases it makes sense the arrow points to the left.
> feat(core): add back nav link

- packages/core/documentation/Link.mdx
Glemte å oppdatere bruksdokumentasjonen. Lagt til her.
> docs(core): add missing nav documentation

- portal/src/texts/profile/tone.mdx
> docs(tone): add read more section

- portal/package.json
- yarn.lock
closes open security risk with axios
> chore(portal): update gatsby

- packages/webfonts/README.md
explain how to use with use syntax
> fix: update webfonts doc

- packages/accordion-react/package.json
- packages/alert-message-react/package.json
- packages/button-react/package.json
- packages/card-react/package.json
- packages/checkbox-react/package.json
- packages/content-toggle-react/package.json
- packages/core/package.json
- packages/datepicker-react/package.json
- packages/feedback-react/package.json
- packages/field-group-react/package.json
- packages/hamburger-react/package.json
- packages/icon-button-react/package.json
- packages/icons-react/package.json
- packages/image-react/package.json
- packages/list-react/package.json
- packages/loader-react/package.json
- packages/logo-react/package.json
- packages/message-box-react/package.json
- packages/portal-components/package.json
- packages/progress-bar-react/package.json
- packages/radio-button-react/package.json
- packages/react-hooks/package.json
- packages/select-react/package.json
- packages/summary-table-react/package.json
- packages/table-react/package.json
- packages/text-input-react/package.json
- packages/toggle-switch-react/package.json
- packages/typography-react/package.json
affects: @fremtind/jkl-accordion-react, @fremtind/jkl-alert-message-react,
@fremtind/jkl-button-react, @fremtind/jkl-card-react, @fremtind/jkl-checkbox-react,
@fremtind/jkl-content-toggle-react, @fremtind/jkl-core, @fremtind/jkl-datepicker-react,
@fremtind/jkl-feedback-react, @fremtind/jkl-field-group-react, @fremtind/jkl-hamburger-react,
@fremtind/jkl-icon-button-react, @fremtind/jkl-icons-react, @fremtind/jkl-image-react,
@fremtind/jkl-list-react, @fremtind/jkl-loader-react, @fremtind/jkl-logo-react,
@fremtind/jkl-message-box-react, @fremtind/jkl-portal-components, @fremtind/jkl-progress-bar-react,
@fremtind/jkl-radio-button-react, @fremtind/jkl-react-hooks, @fremtind/jkl-select-react,
@fremtind/jkl-summary-table-react, @fremtind/jkl-table-react, @fremtind/jkl-text-input-react, …
> fix: add react 17 types as valid peerdep

- portal/src/texts/blog/scss.mdx
Legger til litt mer bakgrunn for endringer som kommer. Også dokumentert i webfonts readme.
> docs(blog): add scss blog

- portal/src/texts/blog/updates/january2021.mdx
> docs(blog): add january post

- package.json
affects: @fremtind/jkl-icons-react
Husky fikser git add selv nå.
> fix: remove unnessesary git add

- portal/src/components/Documentation/Spacing/SpacingTable.tsx
Legg til `layout-spacing-xs` i dokumentasjonen av spacing-skala under Profil i portalen
Closes: #1788
> docs(spacing): document layout-spacing-xs under profile

- portal/src/texts/universell-utforming/Contact.mdx
- portal/src/texts/universell-utforming/ScreenReader.mdx
- portal/src/texts/universell-utforming/TestGuideKeyboard.mdx
- portal/src/texts/universell-utforming/TestGuideUU.mdx
Kom gjerne med forslag til tekstlige endringer. Lagt til en underside for tilbakemelding på UU. Trenger vi å si mer/mindre der?
> docs(uu): add feedback page, minor clarifications

- packages/text-input/text-input.scss
Legg til ordentlig fokusramme på handlingsknappen under tastaturnavigasjon
> fix(text-input): add better keyboard focus to action

- portal/src/texts/blog/updates/february2021.mdx
> docs(blog): february update

- portal/src/texts/universell-utforming/Roller.mdx
Updated the first bullet point in the list of expectations for a tester.
Find it necessary to update/clarify the list of expectations for the test role.
> docs(uu): update uu roles for test

- packages/datepicker-react/src/DatePicker.tsx
> Use forward ref on datepicker

- .github/workflows/cypress.yml
Try to fix issue with first run of cypress
> fix: remove token from cypress

- .github/workflows/cypress.yml
> Revert "fix: remove token from cypress"

- .github/workflows/cypress.yml
> chore(ci): update cypress token

- packages/checkbox-react/package.json
- packages/datepicker-react/package.json
- packages/feedback-react/package.json
- packages/logo-react/package.json
- packages/portal-components/package.json
- packages/radio-button-react/package.json
- packages/select-react/package.json
- packages/text-input-react/package.json
- packages/toggle-switch-react/package.json
- portal/package.json
- yarn.lock
> chore(deps): update snyk and nanoid

- README.md
Fjerner badge for sårbarheter fra README. Det har ikke stemt på lenge, siden vi ikke bruker Snyk, og er kanskje uansett ikke noe vi vil vise frem.
closes #1993
> docs: remove vulnerabilities badge from README

- .github/workflows/cypress.yml
> chore: remove token from cypress workflow

- portal/src/pages/index.tsx
Det er visstnok flere g-er som må til.
Fikse stavefeil.
> docs: fikse feilstavelse

- packages/loader-react/README.md
- packages/loader-react/src/Loader.tsx
affects: @fremtind/jkl-loader-react
ISSUES CLOSED: #2058
Lagt til aria-live og politeness prop som tar "polite" eller "assertive".
> feat(loader-react): add aria-live and politeness prop

- packages/hamburger-react/documentation/index.html
- packages/hamburger/hamburger.scss
affects: @fremtind/jkl-hamburger
Closes #1969 
Oppdater animasjon og stil på hamburgerkomponent ihht #1969.
> feat(hamburger): update animation for hamburger component

- packages/hamburger-react/README.md
- packages/hamburger-react/documentation/Example.tsx
- packages/hamburger-react/src/Hamburger.test.tsx
- packages/hamburger-react/src/Hamburger.tsx
- packages/hamburger/hamburger.scss
- portal/src/components/Header/components/FullScreenMenu.tsx
- portal/src/components/Header/components/MainMenu.tsx
affects: @fremtind/jkl-hamburger-react, @fremtind/jkl-hamburger
in stead of being uncontrolled, the component is simplified and all
logic is moved outside the component. this is to fix issues where
external factors may have to alter the state of the hamburger component
API is changed to be controlled
Closes #1164 
> feat(hamburger): make hamburger controlled

- packages/cookie-consent/cookie-consent.scss
Faktisk fiks, siden den forrige var feil...
affects: @fremtind/jkl-cookie-consent
> fix: actually use correct bg in dark mode on cookie consent

- yarn.lock
> chore: upgrades dependencies

- packages/table-react/package.json
Other jkl-react-packages have a dependency on their styling counterpart package.
table-react should have such a dependency as well.
> fix: add missing dependency

- packages/feedback-react/src/FeedbackValues.tsx
En bitteliten fiks av språket.
> fix: improve language

- portal/src/components/Footer/Footer.scss
> fix: fixed font color in footer

- .codesandbox/ci.json
Use Node.js 14, and try out using the Portal as a sandbox
Dette fikser den feilende testen for CodeSandbox
> Update CodeSandbox CI

- portal/src/texts/profile/animation.mdx
To seksjoner hadde byttet om rekkefølgen
ISSUES CLOSED: #2082
> docs: rett opp eksempler på riktig og feil animasjon

- packages/button/button.scss
ISSUES CLOSED: #1593
Inverted er kanskje deprecated, men var en kjapp fix så 🤷‍♂️
> fix: retter strekfarge for invertert jkl-button--tertiary

- .github/pull_request_template.md
- .github/workflows/codeql-analysis.yml
- .github/workflows/cypress.yml
- .github/workflows/portal.yml
- .github/workflows/release.yml
- lerna.json
- portal/CHANGELOG.md
- portal/src/components/Layout/components/GitHubLinks.tsx
- portal/src/texts/blog/hvordanBlogge/hvordanBlogge.mdx
- portal/src/texts/getstarted/buildWithJkl.mdx
- portal/src/texts/getstarted/processGuide.mdx
- portal/src/texts/profile/typography.mdx
> chore: gi hovedbranchen et nytt navn

- packages/feedback-react/package.json
- portal/src/texts/getstarted/buildWithJkl.mdx
Legg til to manglende dependencies i `feedback-react`
-   [x] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) doc
> fix: add missing dependencies

- packages/select-react/src/Select.test.tsx
ISSUES CLOSED: #1135 
Tester #881
> chore: fjern regelendringer som ikke lenger trengs

- .github/workflows/release.yml
- package.json
Legg inn parallellpublisering av Jøkul-pakkene til GitHub packages. Er litt usikker på om det er riktig autentisering her, men det finner vi fort ut av ved merge 😅
-   [x] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) doc
> chore: publish packages to GitHub Packages in parallel

- .github/workflows/release.yml
Fiks et steg i release-workflowen som ikke var gyldig, ved å splitte det i to.
-   [x] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) doc
-   [x] I have added necessary documentation (if appropriate
> fix(ci): split invalid workflow step

- .github/workflows/external-contributions-sync.yml
ISSUES CLOSED: #2221
https://cli.github.com/manual/gh_api
https://docs.github.com/en/rest/reference/repos#merging
https://docs.github.com/en/actions/guides/using-github-cli-in-workflows
Eksempel på action run og merge-commit fra lekegrinda mi:
https://github.com/wkillerud/pr/actions/runs/1241696351
https://github.com/wkillerud/pr/commit/861a20fbb9307c3e4a29b37b225dcd035898e4c6
Actionen spytter ut en HTTP-respons med commit-detaljene. Fra hva jeg kan se skal det ikke være noe skummelt der.
> chore: bruk GitHub API og CLI for å gjøre branch sync

- .github/pull_request_template.md
- portal/src/texts/getstarted/PullRequestGuide.mdx
Vi har gått opp en løype for å motta bidrag fra forks og må dokumentere den. Samtidig tenkte jeg det var på tide å oversette PR-templaten til arbeidsspråket for repoet ellers.
> docs: dokumenter prosessen med PR fra forks

- packages/feedback-react/src/main-question/MainQuestion.tsx
Standardmeldingen etter innsending av Feedback var lik etter første spørsmål og etter oppfølgingsspørsmål. Oppdaterer meldingen etter første spørmål til noe mer fornuftig og mer i tråd med skissene.
> Fiks duplikat melding i Feedback

- yarn.lock
ISSUES CLOSED: #2229
Denne hopper over:
@nrk/core-dialog 3.0.7 -> 3.1.0 da den knakk bygg
Usikker på om denne er relatert til https://github.com/fremtind/jokul/issues/1215
@testing-library/dom 8.5.0 -> 8.6.0 da den knakk testene i feedback
Opprettet https://github.com/fremtind/jokul/issues/2251
> chore: oppdater minor og patch av dependencies og dev-dependencies

- packages/feedback-react/src/Feedback.test.tsx
- packages/select-react/src/Select.test.tsx
- patches/@nrk+core-dialog+3.1.0.patch
- yarn.lock
Fikser noen timingproblemer og act-varsler som ble avdekket
> chore: oppgrader avhengigheter

- portal/src/components/Header/components/FullScreenMenuItem.scss
- portal/src/components/Header/components/MainMenu.scss
Fikser litt rusk i størrelsesanvisningene, og justerer ned størrelsen litt (bruker samme fra medium og opp) siden vi har fått så mange komponenter :)
> Juster skriftstørrelse i portalmenyene

- .codesandbox/ci.json
De to sandboxene som brukes er enten utdaterte eller ikke-fungerende.
CodeSandbox kan vurderes som alternativ for #2278, men i dag gir den
ingen verdi som vi ikke allerede får gjennom GitHub Actions.
> Slett CodeSandbox CI

- packages/webfonts/README.md
Jeg brukte litt for lang tid på å feilsøke denne
> docs: legg inn et hint om jkl-klassen

- portal/src/texts/blog/bye-ie.mdx
- portal/src/texts/blog/iePlussJokulErlikSant/iePlussJokulErlikSant.mdx
- portal/src/texts/blog/jokul-dropper-ie-stotte.mdx
> docs: bloggpost om dropping av IE

- packages/accordion-react/documentation/AccordionExample.tsx
- packages/accordion-react/src/Accordion.tsx
- packages/accordion-react/src/AccordionItem.test.tsx
- packages/accordion-react/src/AccordionItem.tsx
- packages/accordion-react/src/index.ts
ISSUES CLOSED: #2515
docs(accordion): add example code of onClick prop
ISSUES CLOSED: #2515
refactor(accordion): export accordion/accordionItem props
ISSUES CLOSED: #2515
test(AccordionItem): test accordionItem's onClick prop
ISSUES CLOSED: #2515
-   [x] Jeg har lagt til tester som demonstrerer at feilen er rettet …
> feat(@fremtind/jkl-accordion-react): add onClick prop to AccordionItem

- portal/src/pages/index.tsx
Lenk til hvordan bygge _med_ Jøkul, ikke _for_ Jøkul
> docs: oppdater forsidekort

- portal/package.json
For å unngå versjonering i Lerna
ISSUES CLOSED: #2428
https://github.com/lerna/lerna/issues/1649#issuecomment-487883008
> chore: fjern versjon fra portalen

- portal/package.json
Reverts fremtind/jokul#2526
Dette brakk yarn install, som igjen brakk andre ting
> Revert "chore: fjern versjon fra portalen"

- packages/alert-message-react/documentation/AlertMessageExample.tsx
- packages/message-box-react/documentation/MessageBox.mdx
- packages/message-box-react/documentation/MessageBoxExample.tsx
- packages/message-box-react/src/MessageBox.tsx
- packages/message-box-react/src/index.ts
- Eksporter props fra Message box og refactor for bedre props-tabell i portalen
- Utvid komponentdokumentasjon med må-krav
ISSUES CLOSED: #2524 
> Komponentdok for Message box

- portal/src/components/UU/UU.tsx
- portal/src/components/UU/uu.scss
Bare litt dogfooding! Bruker Tag-komponenten i UU-guiden i portalen i stedet for suctom "tags"
> feat: bruk Tag i uu-guiden i portalen

- packages/checkbox/checkbox.scss
- packages/datepicker/datepicker.scss
- packages/radio-button/radio-button.scss
- packages/select/select.scss
- packages/text-input/text-input.scss
affects: @fremtind/jkl-checkbox, @fremtind/jkl-datepicker, @fremtind/jkl-radio-button,
@fremtind/jkl-select, @fremtind/jkl-text-input
ISSUES CLOSED: #2531
> fix: animasjonsfix for Safari

- .github/workflows/weekly-tasks.yml
La det være opp til kjerneteamet pluss opt-in
**Vil du være med i rotasjonen? Legg deg til i en PR!**
> chore: endre mulige assignees i weekly

- doc-utils/ComponentExample.tsx
- doc-utils/ExampleBase.tsx
- doc-utils/index.ts
- portal/src/texts/getstarted/GettingStartedDev.mdx
- portal/src/texts/getstarted/gettingStartedDesign.mdx
- scripts/scaffold/templates/component-react/README.md
- scripts/scaffold/templates/component-react/documentation/Scaffold.mdx
- scripts/scaffold/templates/component-react/documentation/ScaffoldExample.tsx
- scripts/scaffold/templates/component/README.md
Som diskutert i #2500 
ISSUES CLOSED: #2534
> Dokumenter minstekrav til dokumentasjon

- packages/select-react/documentation/Select.mdx
> docs: komponentdok for Select

- packages/icons-react/documentation/AnimatedIconsExample.tsx
- packages/icons-react/documentation/Icons.mdx
- packages/icons-react/documentation/IconsExample.tsx
- portal/src/texts/profile/icon.mdx
Utvid dokumentasjonen rundt ikoner med lenker til eksempler på bruk i Jøkul, og en setning eller to om animasjon og fargebruk.
Legg til noen kodeeksempler på komponentsiden, men henvis til profildokumentasjonen for det viktigste.
ISSUES CLOSED: #2580
> docs: kodeeksempler og mer utfyllende ikondokumentasjon

- portal/static/googled9beb0ffe5fd21db.html
-   [ ] Jeg har lest [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) og dokumentasjon det henvises til
-   [ ] Jeg har satt target branch til `main`, eller `external-contributions` dersom pull requesten kommer fra en fork
> chore: bekreft eierskap i Google Search Console

- .eslintrc.js
- packages/alert-message-react/documentation/AlertMessage.mdx
- packages/alert-message-react/documentation/AlertMessageExample.tsx
- packages/checkbox-react/documentation/Checkbox.mdx
- packages/content-toggle-react/documentation/ContentToggle.mdx
- packages/cookie-consent-react/documentation/CookieConsent.mdx
- packages/description-list-react/documentation/DescriptionList.mdx
- packages/field-group-react/documentation/FieldGroup.mdx
- packages/icon-button-react/documentation/IconButton.mdx
- packages/icon-button-react/documentation/IconButtonExample.tsx
- packages/icon-button-react/src/IconButton.tsx
- packages/icon-button-react/src/index.ts
- packages/icons-react/documentation/Icons.mdx
- packages/list-react/documentation/List.mdx
- packages/message-box-react/documentation/MessageBox.mdx
- packages/message-box-react/documentation/MessageBoxExample.tsx
- packages/radio-button-react/documentation/RadioButton.mdx
- packages/summary-table-react/documentation/SummaryTable.mdx
- packages/tag-react/documentation/Tag.mdx
- packages/text-input-react/documentation/Autosuggest.mdx
- packages/text-input-react/documentation/TextInput.mdx
- packages/toggle-switch-react/documentation/ToggleSwitch.mdx
- packages/toggle-switch-react/documentation/ToggleSwitchExample.tsx
> feat: eksporter typer for ikonknapp, dokumentasjon

- portal/src/components/Header/components/MainMenu.tsx
Tok ikke høyde for at også desktop hadde "nøstede" menypunkter
ISSUES CLOSED: #2425
> fix: gjenopprett React Hooks menypunkt

- packages/core/mixins/_screens.scss
- portal/src/texts/getstarted/MobileGuide.mdx
Relatert til #2557, men rører ikke breakpointverdiene i Jøkul. Noen forslag etter dagens forum. Kom gjerne med innspill både på dokumentasjonen og på Sass-funksjonene (navngiving, implementasjon).
- Forenkler å lage breakpoints for de som allerede kjenner til mixinene for small-device og så videre.
- Tydeliggjør friheten man har i teamene, og forventninger
-   [x] Jeg har …
> Dokumentasjon av responsiv design, hjelpeverktøy for media queries

- packages/field-group-react/documentation/FieldGroup.mdx
- packages/field-group-react/documentation/FieldGroupExample.tsx
- packages/field-group-react/src/FieldGroup.tsx
affects: @fremtind/jkl-field-group-react
Undeprecate to props som jeg var litt ivrig på å fjerne
ISSUES CLOSED: #2608
> docs: komponentdok for fieldgroup

- packages/accordion-react/documentation/AccordionExample.tsx
- packages/accordion-react/documentation/accordion.mdx
> docs: komponentdok for accordion

- packages/content-toggle-react/documentation/ContentToggle.mdx
- packages/content-toggle-react/documentation/ContentToggleExample.tsx
- packages/content-toggle-react/src/ContentToggle.test.tsx
- packages/content-toggle-react/src/ContentToggle.tsx
> fix: sett default aria-live til polite

- portal/gatsby-config.js
- portal/src/texts/getstarted/buildWithJkl.mdx
- portal/src/texts/getstarted/gettingStartedDesign.mdx
> chore: legg til ordet designsystem i title, endre sidetitler

- doc-utils/ExampleBase.tsx
Bare re-render om noen av propsene endres, ikke for eksempel når kodeeksempelet vises og skjules
-   [ ] Jeg har lest [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) og dokumentasjon det henvises til
-   [ ] Jeg har satt target branch til `main`, eller `external-contributions` dersom pull requesten kommer fra en fork
> chore: memo eksempelkomponenten

- packages/content-toggle-react/documentation/ContentToggle.mdx
- packages/react-hooks/documentation/AnimationExample.tsx
- packages/react-hooks/documentation/animation.mdx
> docs: pek på useAnimatedHeight og fiks en typo

- packages/validators-util/documentation/validators.mdx
- packages/validators-util/src/hasMinimumWords/hasMinimumWords.test.tsx
- packages/validators-util/src/hasMinimumWords/hasMinimumWords.ts
- packages/validators-util/src/index.ts
- packages/validators-util/src/isValidName/isValidName.test.tsx
- packages/validators-util/src/isValidName/isValidName.ts
affects: @fremtind/jkl-validators-util
> feat(validators): implemented hasMinimumWords / isValidName

- doc-utils/ExampleBase.tsx
This reverts commit 561d6f44f83a20e0408e6bdcbb32a3f12f09ae07.
ISSUES CLOSED: #2649
Fiks et problem hvor ContentToggle-eksempelet ikke animerte
> chore: revert memo eksempelkomponenten

- .github/workflows/pull_request.yml
Animasjoner skaper problemer i testene, og er uansett ikke noe vi snapshoter
-   [ ] Jeg har lest [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) og dokumentasjon det henvises til
-   [ ] Jeg har satt target branch til `main`, eller `external-contributions` dersom pull requesten kommer fra en fork
> chore: skru på prefers-reduced-motion i Cypress-tester

- packages/core/documentation/typography.mdx
- portal/src/texts/profile/typography.mdx
affects: @fremtind/jkl-core, @fremtind/portal
> docs: tydeliggjør at man står fritt til å velge

- .github/workflows/pull_request.yml
- portal/integration/portal-smoketest.spec.js
- portal/src/components/Header/components/MainMenu.tsx
- portal/src/components/Header/components/useFullScreenMenuAnimation.tsx
ISSUES CLOSED: #2672 
-   [x] Testdekningen er god nok (enhetstest, visuell regresjonstest)
> fix: sett hidden når tilstanden er _ikke_ åpen

- portal/src/texts/uu/kontrast.mdx
-   [X] Minstekrav til dokumentasjon er oppfyllt (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker)
-   [X] Testdekningen er god nok (enhetstest, visuell regresjonstest)
> fiks skrivefeil i lesbarhet

- .github/pull_request_template.md
"God nok" er skjønnsbasert, og vanskelig å forholde seg til - spesielt for nye. Fjern det, og etterspør heller tester ved code review.
> chore: forenkle PR-template

- packages/formatters-util/documentation/InputMaskExample.tsx
- packages/formatters-util/src/index.ts
- packages/formatters-util/src/util/registerWithMask.ts
Tok altså en halv dag før jeg fant et bedre API for masker i skjemafelter 😅 Er implementert uten breaking change for sikkerhets skyld.
> feat: legg til bedre hjelpefunksjoner for masker i skjemafelter

- portal/src/components/Header/components/MainMenu.tsx
- portal/src/components/Header/components/MainMenuItem.tsx
CoreToggle merket klikket og togglet vekk innholdet, men vi hadde ingen lytter som oppdaterte state.
Bare fjern den...
ISSUES CLOSED: #2496
> fix: klikk mellom menypunkter fjerner ikke innholdet lenger

- portal/src/texts/blog/updates/februar-2022.mdx
> legg til infomrasjon om select

- .github/workflows/release.yml
- portal/package.json
Manglet å kalle patch-package etter flytting av script i #2763
> fix: krasjende release-workflow

- .github/workflows/codeql-analysis.yml
- .github/workflows/pull_request.yml
> chore: dropp CodeQL på ci skip release

- packages/datepicker-react/src/Calendar.tsx
> fix: annonser endring av kalenderåret i datovelger

- packages/table-react/documentation/ExpandableTableExample.tsx
- packages/table-react/documentation/index.tsx
- packages/table-react/src/ExpandableTableRow.tsx
- packages/table-react/src/ExpandableTableRowController.tsx
- packages/table/table-cell.scss
> feat: add support for a callback when open state changes

- packages/table/table-row.scss
> feat: fix animation timing for expandable tablerow

- packages/card-react/src/NavCard.tsx
- packages/checkbox-react/src/Checkbox.tsx
- packages/field-group-react/src/FieldGroup.tsx
- packages/icon-button-react/src/IconButton.tsx
- packages/table-react/src/DataTable.tsx
- packages/table-react/src/Table.tsx
- packages/table-react/src/TableColumn.tsx
- packages/table-react/src/TableColumnGroup.tsx
- packages/table-react/src/TableHeader.tsx
- packages/tag-react/src/Tag.tsx
- packages/tag-react/src/index.ts
- packages/text-input-react/src/TextInput.tsx
> fix: bruk riktig React-interface som base for typer

- portal/src/texts/blog/infrastrukturen-til-jokul-2022.mdx
Fredagens fagtime i tekstformat
> docs: bloggpost om dagens infrastruktur

- packages/table-react/documentation/Table.mdx
- packages/table-react/src/TableHeader.tsx
- packages/table/table-header.scss
> feat: add support for left/right aligning table header

- portal/src/pages/index.scss
- portal/src/pages/kom-i-gang/deg-og-jokul.tsx
- portal/src/pages/kom-i-gang/hjelp.tsx
- portal/src/pages/kom-i-gang/utvikling.tsx
> docs: fiks småfeil etter ny onboarding

- portal/src/texts/guider/hvordanTesteLokaleEndringerEgetProsjekt.mdx
En fugl kvitret at en guide for dette hadde vært fint. 
Det var nyttig for meg å få testet selv. Lærte nye nytt om `npm link` – les guiden for å finne ut hva 😉
> docs: lag en guide for å teste endringer lokalt

- portal/src/texts/guider/hvordanTesteLokaleEndringerEgetProsjekt.mdx
Forklar problemet, legg ved eksempelconfig så ikke alle som bruker Webpack må finne ut av dette på egenhånd
> docs: dokumenter lessons learned med Webpack

- package.json
- yarn.lock
> chore: oppdater noen resolutions

- packages/core/package.json
> fix: pakk med all Sass-kildekoden

- .github/workflows/weekly-tasks.yml
- actions/changed-files/src/git.ts
- package.json
- yarn.lock
chore: oppdater resolutions og issue template for ukentlige oppdateringer
> chore: oppdater resolutions og issue template for ukentlige oppdateringer

- packages/formatters-util/documentation/FormattersExample.tsx
- packages/formatters-util/src/index.ts
- packages/formatters-util/src/organisasjonsnummer/formatOrganisasjonsnummer.test.ts
- packages/formatters-util/src/organisasjonsnummer/formatOrganisasjonsnummer.ts
- packages/validators-util/src/index.ts
- packages/validators-util/src/isValidOrganisasjonsnummer/isValidOrganisasjonsnummer.test.tsx
- packages/validators-util/src/isValidOrganisasjonsnummer/isValidOrganisasjonsnummer.ts
> feat: created formatter and validator for organisasjonsnummer

- packages/radio-button-react/src/RadioButton.tsx
> fix: ikke overskriv name med undefined fra context

- packages/radio-button-react/src/RadioButtonGroup.test.tsx
> test: regresjonstest for name satt på react-hook-form-måten

- packages/formatters-util/documentation/InputMaskExample.tsx
- packages/formatters-util/src/util/registerWithMask.ts
> feat: add orgnr to registerWithMasks

- packages/tag-react/documentation/Example.tsx
- packages/tag-react/documentation/Tag.mdx
- packages/tag-react/documentation/TagExample.tsx
- packages/tag-react/package.json
- packages/tag-react/src/Tag.test.tsx
- packages/tag-react/src/Tag.tsx
- packages/tag/tag.scss
- scripts/scaffold/templates/component-react/documentation/Example.tsx
could be used when for instance creating search filters with a chip pattern
> feat: add support for dismissable tag

- packages/table-react/README.md
Måtte grave litt da jeg skulle reprodusere #2965 i CodeSandbox
> docs: legg til import av underavhengigheter

- packages/validators-util/documentation/validators.mdx
- packages/validators-util/src/isValidOrganisasjonsnummer/isValidOrganisasjonsnummer.test.tsx
- packages/validators-util/src/isValidOrganisasjonsnummer/isValidOrganisasjonsnummer.ts
> fix: isValidOrganisasjonsnummer no longer returns null if length is not correct

- packages/core/styles/_reset.scss
> fix: legg inn en author style for hidden-attributtet

- portal/gatsby-ssr.js
- portal/package.json
- portal/src/components/Layout/Layout.tsx
- portal/src/components/seo/Seo.tsx
- portal/src/components/seo/index.ts
- portal/src/pages/blog.tsx
- portal/src/pages/eksempler/skjemavalidering.tsx
- portal/src/pages/index.tsx
- portal/src/pages/kom-i-gang/deg-og-jokul.tsx
- portal/src/pages/kom-i-gang/design.tsx
- portal/src/pages/kom-i-gang/hjelp.tsx
- portal/src/pages/kom-i-gang/introduksjon.tsx
- portal/src/pages/kom-i-gang/jobb-med-teamet.tsx
- portal/src/pages/kom-i-gang/slik-er-jokul-satt-sammen.tsx
- portal/src/pages/kom-i-gang/utvikling.tsx
- portal/src/templates/DocPageLayout.tsx
- yarn.lock
> chore: refactor ut react-helmet, anbefalt av Gatsby

- packages/datepicker-react/src/utils.ts
> fix: compare nodes instead of classList while checking the blur target

- packages/core/documentation/mixins.mdx
> docs: forny siden om Sass mixins

- packages/datepicker-react/src/utils.ts
> fix: use input wrapper div as onBlur root

- packages/card-react/src/Card.tsx
- packages/image-react/src/Image.tsx
- portal/src/components/Documentation/Picture/PictureBox.tsx
- portal/src/components/DownloadAsset/DownloadAsset.tsx
- portal/src/components/portal-image/AnimatedImage.tsx
> Bildeattributt

- packages/alert-message-react/documentation/AlertMessageExample.tsx
- packages/message-box-react/documentation/MessageBoxExample.tsx
- portal/src/components/Experimental/Experimental.tsx
- portal/src/pages/eksempler/feilmelding-500-med-melding.tsx
> docs: unngå at innhold leses opp av skjermleser uten kontekst

- packages/select-react/src/Select.tsx
> fix: navigasjon med piltast forbi skjulte elementer

- .github/workflows/issue_triage.yml
Gjør så vi slipper å glemme legge til issues i tavla vår
> chore: action for å legge til prosjektet automatisk

- packages/core/README.md
- packages/core/styles/_headings.scss
- packages/loader/loader.scss
> fix: rydd opp noen etternølere etter compact reboot

- package.json
- portal/src/texts/guider/hvordanTesteLokaleEndringerEgetProsjekt.mdx
- scripts/linker.js
> chore: legg til verktøy for å automatisk linke opp hele Jøkul

- doc-utils/ExampleBase.tsx
- doc-utils/component-example.scss
ISSUES CLOSED: #3119 
Eksempel: https://jokul.fremtind.no/preview/feat/link-til-eksempel/komponenter/textinput#text-area
> docs: legg til slug per komponenteksempel så vi kan linke rett til dem

- portal/src/layout/Layout.scss
- portal/src/layout/MainContent.tsx
- portal/src/pages/404.tsx
- portal/src/pages/blog.tsx
- portal/src/pages/eksempler/feilmelding-500-med-melding.tsx
- portal/src/pages/eksempler/feilmelding-500.tsx
- portal/src/pages/eksempler/skjemavalidering.tsx
- portal/src/pages/index.tsx
- portal/src/pages/kom-i-gang/deg-og-jokul.tsx
- portal/src/pages/kom-i-gang/design.tsx
- portal/src/pages/kom-i-gang/hjelp.tsx
- portal/src/pages/kom-i-gang/introduksjon.tsx
- portal/src/pages/kom-i-gang/jobb-med-teamet.tsx
- portal/src/pages/kom-i-gang/lekegrind.tsx
- portal/src/pages/kom-i-gang/slik-er-jokul-satt-sammen.tsx
- portal/src/pages/kom-i-gang/utvikling.tsx
- portal/src/templates/DocPageLayout.jsx
Legg til en komponent for å wrappe hovedinnhold i portalen, med riktige egenskaper for animasjon og en id som gjør at hopp til innhold fungerer.
ISSUES CLOSED: #3137
> fix: sørg for at hopp til innhold funker som forventet

- packages/tooltip-react/package.json
- packages/tooltip-react/src/Tooltip.tsx
- patches/@jest+environment+29.1.1.patch
- patches/gatsby+4.24.0.patch
- yarn.lock
> Oppdater ukens avhengigheter

- yarn.lock
Usikker på hvorfor denne ikke ble oppdatert riktig første gangen
> chore: oppdater lockfile

- doc-utils/ExampleBase.tsx
> docs: endre ikke-kompakt til Default i dokumentasjonen

- portal/src/components/Typography/Typography.tsx
- portal/src/components/delay-text/DelayText.tsx
- portal/src/layout/Layout.tsx
- portal/src/layout/header/ContentLink.tsx
- portal/src/pages/index.tsx
Følg anbefalingene til Gatsby:
https://www.gatsbyjs.com/blog/2019-07-11-user-testing-accessible-client-routing/
ISSUES CLOSED: #3138
> fix: flytt tastaturfokus ved sidenavigering

- portal/gatsby-node.js
- portal/src/components/Documentation/Picture/MediaBox.tsx
- portal/src/layout/Layout.tsx
> fix: skjul skip link ved navigering med peker, warnings fra Gatsby

- scripts/scaffold/templates/component-react/package.json
- scripts/scaffold/templates/component/package.json
> fix: core-versjon i scaffold

- jest.config.js
- portal/src/layout/header/Header.tsx
- portal/src/layout/header/PortalLogo.scss
- portal/src/layout/header/PortalLogo.test.tsx
- portal/src/layout/header/PortalLogo.tsx
- portal/src/layout/header/header.scss
Den viktigste endringen:
https://github.com/fremtind/jokul/pull/3205/files#diff-53475e8759ac1e7a5a7c461e44eee3b1c9a2f9ce1d32d7b0c39c84de1b72811bR14
> chore: refactor portallogoen

- packages/validators-util/src/isValidFodselsnummer/isValidFodselsnummer.test.tsx
- packages/validators-util/src/isValidFodselsnummer/isValidFodselsnummer.ts
> fix: only zeros is not valid fodselsnummer anymore

- doc-utils/component-example.scss
> docs: fikset kontrast på tekst i select for dark mode

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
> chore: hopp over unødvendig logout

- .github/workflows/release.yml
> chore: endre rekkefølge på actions

- .husky/commit-msg
- .husky/pre-commit
> fiks syntaksen i hooks

- package.json
> chore: fjern prepare-script som forvirret lerna

- .github/workflows/release.yml
- .github/workflows/release_portal.yml
> chore: workaround for begrenset paths-filter

- packages/tooltip-react/src/Tooltip.tsx
> fix: changed padding for tooltip arrow hence the design sketches

- portal/src/layout/header/PortalLogo.scss
> fix: rett opp farger i dark mode

- .github/workflows/release_portal.yml
> chore: legg til bygg/restore fra cache for pakker

- portal/.eslintignore
For å trigge et nytt bygg av portalen
> style: sorter alfabetisk

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- package.json
> chore: don't break my auth

- packages/alert-message-react/package.json
- packages/field-group-react/package.json
- packages/table-react/package.json
- packages/toggle-switch-react/package.json
- pnpm-lock.yaml
Core er en dependency, ikke devDependency
> fix: rett opp i feil rundt devDependencies

- .github/workflows/release.yml
> chore: sørg for at lerna ikke klager ved publish til GH

- packages/core/jkl/_index.scss
- packages/core/jkl/_spacing.scss
- packages/core/styles/_spacing.scss
Forslag basert på diskusjon i #3249
> Forslag til endringer i dynamisk spacing

- package.json
- patches/kbar@0.1.0-beta.39.patch
- pnpm-lock.yaml
- portal/package.json
> fix: uu-problem og escape-håndtering av kbar

- packages/expand-button/expand-button.scss
> fix: legg til manglende selector for animerte ikon

- packages/select-react/src/Select.tsx
> fix: fiks en overskriving av value med tom string i sjeldne tilfeller

- packages/accordion-react/documentation/accordion.mdx
- packages/alert-message-react/documentation/AlertMessage.mdx
- packages/breadcrumb-react/documentation/Breadcrumb.mdx
- packages/button-react/documentation/buttons.mdx
- packages/card-react/documentation/card.mdx
- packages/datepicker-react/documentation/Datepicker.mdx
- packages/expand-button-react/documentation/ExpandButton.mdx
- packages/field-group-react/documentation/FieldGroup.mdx
- packages/list-react/documentation/List.mdx
- packages/loader-react/documentation/Loader.mdx
- packages/logo-react/documentation/Logo.mdx
- packages/message-box-react/documentation/MessageBox.mdx
- packages/select-react/documentation/Select.mdx
- packages/summary-table-react/documentation/SummaryTable.mdx
- packages/table-react/documentation/Table.mdx
- packages/tabs-react/documentation/Tabs.mdx
- packages/text-input-react/documentation/TextInput.mdx
- packages/toggle-switch-react/documentation/ToggleSwitch.mdx
> docs: legg til flere nøkkelord for kbar

- portal/src/pages/kom-i-gang/design.tsx
- portal/src/pages/kom-i-gang/hjelp.tsx
- portal/src/pages/kom-i-gang/utvikling.tsx
- portal/src/texts/guider/hvordanEndreJokul.mdx
- Saks bort innhold som ikke gjelder lenger.
- Oppdater tid og sted for office hours.
- Ton ned ordlyden, ref større eierskap til plattformen.
- Fremhev Hvordan starte nytt prosjekt i Utvikler-delen.
Vi må få inn @fremtindelise på https://jokul.fremtind.no/kom-i-gang/hjelp også ser jeg! Nytt punkt i onboarding-rutinen @gbrownlee 😄 
Fixes #3358, fixes #3058 
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), …
> docs: oppdater kom i gang og Hvordan endre Jøkul

- packages/text-input/text-input.scss
> fix: tilbakefør animeringen av ekspandering

- packages/datepicker-react/src/DatePicker.test.tsx
- packages/datepicker-react/src/utils.ts
extend the supported date formats. this is to have a wider support for pasting dates from various inputs
> feat: extend supported date format variants

- packages/table-react/documentation/SortableTableExample.tsx
- packages/table-react/documentation/Table.mdx
> docs: add documentation for sortable table columns

- packages/table-react/package.json
- packages/table-react/src/TablePagination.tsx
- pnpm-lock.yaml
Unngå å få kryss-ikon i visse setups
> fix: oppdater icon-button i table

- packages/card-react/documentation/InfoCardExample.tsx
- packages/card-react/documentation/NavCardExample.tsx
> docs: endret kodeeksempel for bruk av image-prop

- packages/contextual-menu-react/src/ContextualMenu.tsx
- packages/contextual-menu/contextual-menu.scss
> fix: plasser submeny under på små skjermer

- .github/workflows/pull_request.yml
Se https://github.com/fremtind/jokul/actions/runs/4479699312/jobs/7874128355?pr=3469
> chore: unngå dobbeltkjøring av Cypress-tester

- actions/changed-files/build/main.js
- actions/paths-filter/build/main.js
> chore: commit updated built files for GitHub Actions

- portal/src/layout/header/PortalLogo.test.tsx
- portal/src/layout/header/PortalLogo.tsx
> fix: seasonal

- portal/src/texts/blog/updates/mars-2023.mdx
https://jokul.fremtind.no/preview/docs/mars/blog/updates/mars-2023/
> docs: bloggpost for mars

- SECURITY.md
Henvis til en ny feature, med dagens epostmetode som alternativ. Oversett til engelsk.
> docs: oppdater security.md

- .github/workflows/release.yml
Så portalbygget ikke feiler
https://github.com/fremtind/jokul/actions/runs/4913789162/jobs/8774355998
> chore: bygg pakker hvis det ikke var noen release

- .github/workflows/pull_request.yml
- package.json
- scripts/calculate-cypress-tests.js
Vil forhåpentligvis rette #3523
> chore: rigg om hvordan vi beregner Cypress-tester

- packages/formatters-util/src/telefonnummer/formatTelefonnummer.test.ts
- packages/formatters-util/src/telefonnummer/formatTelefonnummer.ts
> fix: endret formateringen til xx xx xx xx med unntak av 8xx-nummer

- packages/combobox-react/src/Combobox.tsx
> fix: la på onblur og fokus på onClick

- portal/src/layout/portal-footer/PortalFooter.tsx
- portal/src/layout/portal-footer/portal-footer.scss
> docs: høyrejuster stempel hvis nei til statistikk

- packages/combobox-react/src/Combobox.tsx
- packages/combobox/combobox.scss
> fix: skjul input felt visult når menyen er lukket

- packages/combobox-react/src/Combobox.tsx
> feat: la til muligheten for å fjerne valgte tags med backspace

- packages/combobox-react/documentation/ComboboxExample.tsx
> fix: oppdaterte eksempelet til å kunne vise empty state

- packages/modal/package.json
- pnpm-lock.yaml
- scripts/scaffold/templates/component-react/package.json
- scripts/scaffold/templates/component/package.json
> fix: rett feil dependency i modal-CSSen

- packages/toggle-switch-react/documentation/ToggleSwitchExample.tsx
> docs: oppdater kodeeksempel for slider

- packages/icons/icons.scss
Merker ikke som breaking, siden strukturendringen ble annonsert og merket breaking i #3412 
ISSUES CLOSED: #3581
> fix: gjenopprett animasjon av PlusRemoveAnimated

- lerna.json
- nx.json
- package.json
- pnpm-lock.yaml
- portal/package.json
- portal/src/texts/guider/hvordanKode.mdx
- scripts/calculate-cypress-tests.js
- scripts/scaffold/index.js
> Oppgrader til Lerna 7

- .github/workflows/release.yml
> chore: gjenopprett modules.yml etter registry switch

- packages/react-hooks/documentation/progressiveImg.mdx
- portal/src/texts/profil/farger.mdx
> Fjern setning om useProgressiveImg som er feil, dokumenter Fjellgrå

- packages/contextual-menu-react/src/ContextualMenu.tsx
- packages/toggle-switch-react/src/ToggleSwitch.test.tsx
- packages/toggle-switch-react/src/ToggleSwitch.tsx
> fix: send riktig pressed i onChange når kontrollert og default checked

- portal/src/components/APIDocumentation/APIDocumentation.tsx
- portal/src/components/form-components/FormComponentsExample.tsx
- portal/src/components/form-field-anatomy/FormFieldAnatomy.tsx
- portal/src/pages/blog.tsx
- portal/src/pages/demoer/skjemavalidering.tsx
- portal/src/pages/index.tsx
- portal/src/pages/kom-i-gang/lekegrind.tsx
Noen av endringene i portalen som ikke ble oppdatert etter PR-feedback
> fix: headingklasser som ble renamet underveis

- packages/modal/modal.scss
> fix: changed margin on jkl-modal for small devices

- portal/src/texts/profil/farger.mdx
> fix: fix color code for varde color

- packages/tabs/tabs.scss
> fix: changed padding on small screens

- packages/contextual-menu-react/documentation/ContextualMenuExample.tsx
- packages/contextual-menu-react/src/ContextualMenu.tsx
- packages/contextual-menu-react/src/ContextualMenuItem.tsx
* ✨ Legg til mulighet for å la menyen holde seg åpen ved klikk utenfor (behov fra Flyt)
* 🛠️ Gjør ikonet for ekstern lenke valgfritt igjen
> Ny feature og fiks i ContextualMenu

- portal/src/texts/profil/bilder.mdx
> docs: fikset skriveleif

- packages/input-group-react/src/FieldGroup.tsx
- packages/input-group-react/src/InputGroup.tsx
> fix: use ErrorIcon for errors

- packages/text-input-react/src/BaseTextInput.tsx
> feat: legg til støtte for type på action i textinput

- packages/table-react/documentation/Example.tsx
- packages/table-react/documentation/StickyTableExample.tsx
> docs: fix sticky header example for table

- packages/core/tokens/color/color.semantic.tokens.json
> fix: bruk riktig fargeverdi for interactive hover

- packages/core/jkl/_legacy-tokens.scss
- packages/core/jkl/_tokens.scss
- packages/core/src/tokens.ts
- packages/core/styles/_color-tokens.scss
- packages/core/styles/_legacy-tokens.scss
- packages/core/styles/_tokens.scss
- packages/core/tokens.less
> fix: genere riktige fargeverdier fra endrede tokens

- packages/expand-button-react/src/ExpandSection.test.tsx
- packages/expand-button-react/src/ExpandSection.tsx
> fix: revert commit 462cad439 to restore functionality in Safari/FF

- packages/logo-react/src/Logo.tsx
- packages/logo-react/src/LogoStamp.tsx
> feat: add TS support for inline-styles

- packages/select-react/src/Select.test.tsx
- packages/select-react/src/Select.tsx
> fix: instead of closing the modal, just ignore the key event

- portal/src/pages/kom-i-gang/hjelp.tsx
> docs: oppdaterte office hours

- packages/card-react/src/NavCard.tsx
- packages/card/_nav-card.scss
> feat: legg til støtte for å ha flere tags i navcard

- packages/combobox-react/src/Combobox.tsx
> fix: oppdatere state når man fjerner tags med keys

- packages/contextual-menu-react/src/ContextualMenu.tsx
> fix: remove superfluous div

- packages/modal-react/README.md
> docs: update Modal README file

- packages/combobox/combobox.scss
> fix: fjernet marked color fra selected options

- packages/combobox/combobox.scss
> fix: fjernet ubrukt variabel

- packages/icons-react/documentation/IconsExample.tsx
- packages/icons-react/src/icons/pen/PenIcon.tsx
- packages/icons-react/src/icons/pen/PenMedium.tsx
- packages/icons-react/src/icons/pen/PenMediumBold.tsx
- packages/icons-react/src/icons/pen/PenSmall.tsx
- packages/icons-react/src/icons/pen/PenSmallBold.tsx
- packages/icons-react/src/index.ts
> feat: add a "pen" icon

- packages/icons-react/src/icons/pen/PenMedium.tsx
- packages/icons-react/src/icons/pen/PenMediumBold.tsx
- packages/icons-react/src/icons/pen/PenSmall.tsx
- packages/icons-react/src/icons/pen/PenSmallBold.tsx
- packages/icons-react/src/icons/trash/TrashCanMedium.tsx
- packages/icons-react/src/icons/trash/TrashCanMediumBold.tsx
- packages/icons-react/src/icons/trash/TrashCanSmall.tsx
- packages/icons-react/src/icons/trash/TrashCanSmallBold.tsx
> fix: update pen and trash icons

- packages/feedback-react/documentation/FeedbackExample.tsx
- packages/feedback-react/documentation/feedbackExampleProps.ts
- packages/feedback-react/src/Feedback.tsx
- packages/feedback-react/src/feedbackContext.tsx
- packages/feedback-react/src/main-question/MainQuestion.tsx
- packages/feedback-react/src/presets.tsx
- packages/feedback-react/src/questions/AddonQuestion.tsx
- packages/feedback-react/src/questions/TextQuestion.tsx
- packages/feedback-react/src/utils.ts
- packages/text-input-react/src/BaseTextArea.tsx
- portal/src/layout/portal-footer/PortalFooter.tsx
> 3896 feedback textarea counter

- README.md
Legg til informasjon om bruk av corepack på nye Fremtind-Macer
> docs: oppdater readme om corepack

- packages/select-react/src/NativeSelect.tsx
> fix: sørg for at native select ikke viser første element som placeholder

- packages/table-react/documentation/PaginatedTableExample.tsx
- packages/table-react/documentation/SortableTableExample.tsx
- packages/table-react/src/TablePagination.tsx
> feat: optional props for custom labels for TablePagination

- portal/src/texts/profil/farger.mdx
Noen av fargene hadde feil HSL-verdi i oversikten i Profil-seksjonen av portalen. De er nå oppdatert.
> docs: oppdater hsl-verdier for noen av fargene

- packages/table-react/src/TableRow.tsx
> fix: gjør det mulig å bruke TableRow controlled

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- actions/paths-filter/README.md
> fix: oppdater pnpm/action-setup til fungerende versjon

- packages/tooltip-react/src/TooltipContent.tsx
> fix: duplicate key error with tooltip triggered by hover

- packages/text-input-react/src/BaseTextArea.tsx
- packages/text-input-react/src/TextArea.tsx
- packages/text-input/text-input.scss
> 3921 textarea counter

- doc-utils/ExampleBase.tsx
- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useLocalStorage/useLocalStorage.ts
> feat: added useLocalStorage hook

- packages/cookie-consent-react/documentation/CookieConsent.mdx
- packages/cookie-consent-react/documentation/CookieConsentModalExample.tsx
- packages/cookie-consent-react/src/CookieConsent.tsx
- packages/cookie-consent-react/src/CookieConsentContext.tsx
- packages/cookie-consent-react/src/CookieConsentModal.tsx
- packages/cookie-consent-react/src/consents/CustomConsents.tsx
- packages/cookie-consent-react/src/consents/DefaultConsents.tsx
- packages/cookie-consent-react/src/consents/RequirementCheckbox.tsx
- packages/cookie-consent-react/src/cookieConsentUtils.test.ts
- packages/cookie-consent-react/src/cookieConsentUtils.ts
> 3906 cookie consents refactor and stuff

- packages/icons-react/documentation/IconsExample.tsx
- packages/icons-react/src/icons/ThumbDownIcon.tsx
- packages/icons-react/src/icons/ThumbUpIcon.tsx
- packages/icons-react/src/index.ts
> feat: legg til ikoner for tommel opp og tommel ned

- packages/core/documentation/Mixins/Mixins.scss
- packages/core/documentation/Mixins/keyboard.scss
- packages/core/documentation/Spacing/Spacing.scss
- packages/core/documentation/Typography/Typography.scss
- packages/core/styles/_links.scss
> fix: følg ny konvensjon for sass i core

- packages/text-input/text-input.scss
> fix: restore padding to inputs

- .github/workflows/alpha-release.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
Sørg for at alle checks kjøres når PR-er blir lagt i merge queue, slik at ikke køen henger seg opp.
> chore: run checks in merge queue

- .github/workflows/pull_request.yml
> chore: skip changed-files in merge queue

- packages/card/card.scss
- packages/contextual-menu/_contextual-menu-item.scss
- packages/cookie-consent/cookie-consent.scss
- packages/feedback/feedback.scss
- packages/file-input/_file.scss
- packages/message-box/message-box.scss
- packages/table/_table-cell.scss
- packages/table/_table-pagination.scss
> Fiks Sass-rekkefølge i de siste komponentene

- .github/workflows/pull_request.yml
> chore: sørg for å kjøre pnpm install i alle steg

- packages/alert-message-react/src/AlertMessage.tsx
- packages/alert-message/alert-message.scss
> docs: marker alert message som deprecated

- packages/system-message-react/documentation/SystemMessage.mdx
> fix: fungerende dokumentasjon for system-message

- packages/list-react/documentation/LinkListExample.tsx
Glemte å legge til dette i den andre PRen. Bytter om eksemplene for ordered/unordered lenkeliste, slik vi har snakket om.
closes #4026
> docs: bytt om eksempler for lenkeliste

- packages/list-react/documentation/LinkListExample.tsx
Sørg for at vi ikke kaster brukeren tilbake til forsiden av portalen ved klikk på elementene i LinkList-eksemplene.
> docs: bli på siden ved klikk i LinkList-eksemplene

- packages/jokul/package.json
- packages/jokul/src/index.ts
Eksponer alle eksporter under rot i `fremtind/jokul` for enklere bruk.
> feat: eksporter alt i jokul-pakka fra rot

- packages/jokul/src/components/index.ts
> fix: add export for Image components

- packages/feedback-react/documentation/Feedback.mdx
- packages/feedback-react/src/Feedback.tsx
- packages/feedback-react/src/feedbackContext.tsx
- packages/feedback-react/src/followup/Followup.tsx
- packages/feedback-react/src/main-question/MainQuestion.tsx
- packages/feedback-react/src/main-question/useMainQuestion.ts
- packages/feedback-react/src/questions/ContactQuestion.tsx
- packages/feedback-react/src/types.ts
- packages/jokul/src/components/feedback/Feedback.tsx
- packages/jokul/src/components/feedback/feedbackContext.tsx
- packages/jokul/src/components/feedback/followup/Followup.tsx
- packages/jokul/src/components/feedback/main-question/MainQuestion.tsx
- packages/jokul/src/components/feedback/main-question/useMainQuestion.ts
- packages/jokul/src/components/feedback/questions/ContactQuestion.tsx
- packages/jokul/src/components/feedback/types.ts
> 4103 feedback use form

- packages/jokul/src/components/toggle-switch/documentation/Example.tsx
- packages/jokul/src/components/toggle-switch/documentation/ToggleSwitchExample.jsx
- packages/jokul/src/components/toggle-switch/documentation/index.html
- packages/jokul/src/components/toggle-switch/documentation/main.tsx
- packages/jokul/src/components/toggle-switch/documentation/vite.dev.config.ts
- packages/jokul/src/components/toggle-switch/styles/toggle-switch.scss
Tenkte det var greit å ha en dev-server for noe som bruker boolske options og, så det finnes et eksempel på hvordan det ser ut.
> chore: add dev-server for toggle-swithc

- packages/jokul/src/components/radio-button/styles/radio-button.scss
- packages/radio-button/radio-button.scss
> fix: radio-button has correct dot color in dark mode error state

- packages/accordion-react/documentation/AccordionExample.tsx
- packages/accordion-react/documentation/DevClient.tsx
- packages/accordion-react/documentation/DevServer.tsx
- packages/accordion-react/documentation/Example.tsx
- packages/accordion-react/documentation/accordion.mdx
Jeg trengte faktisk å se på hvordan vår accordion fungerer ifm med et a11y kurs jeg driver med
> docs: added missing Accordion docs

- packages/feedback-react/src/questions/SmileyQuestion.tsx
Trigget en event i sentry, så ryddet bare opp for å slippe å få det
> refactor: removed console log

- packages/datepicker-react/src/DatePicker.test.tsx
- packages/datepicker-react/src/DatePicker.tsx
- packages/jokul/src/components/datepicker/DatePicker.test.tsx
- packages/jokul/src/components/datepicker/DatePicker.tsx
> fix: fixes a bug where Datepicker would scroll the page when opened

- packages/jokul/README.md
> docs: oppdater README med dokumentasjon av nye stier for stilark

- packages/jokul/dev-server.mjs
- utils/dev-example/DevExample.tsx
> chore: fix the dev-server

- packages/jokul/README.md
- packages/jokul/package.json
> feat: specific exports for each component

- packages/jokul/src/components/index.ts
- packages/jokul/src/components/radio-panel/RadioPanel.tsx
- packages/jokul/src/components/radio-panel/documentation/ControlledExample.tsx
- packages/jokul/src/components/radio-panel/documentation/Example.tsx
- packages/jokul/src/components/radio-panel/documentation/UncontrolledExample.tsx
- packages/jokul/src/components/radio-panel/documentation/styles.scss
- packages/jokul/src/components/radio-panel/index.ts
- packages/jokul/src/components/radio-panel/styles/_index.scss
- packages/jokul/src/components/radio-panel/styles/radio-panel.scss
- packages/jokul/src/styles/styles.scss
> feat: new component: RadioPanel

- packages/jokul/src/components/modal/Modal.tsx
- packages/jokul/src/components/popover/Popover.tsx
- packages/modal-react/src/Modal.tsx
- packages/popover-react/src/Popover.tsx
> Plasser popover i kontekst nærmeste portal

- packages/datepicker-react/README.md
> docs: include popover css in datepicker readme

- packages/jokul/src/components/card/Card.tsx
- packages/jokul/src/components/card/CardImage.tsx
- packages/jokul/src/components/combobox/Combobox.tsx
- packages/jokul/src/components/datepicker/DatePicker.tsx
- packages/jokul/src/components/datepicker/internal/Calendar.tsx
- packages/jokul/src/components/expander/Expander.tsx
- packages/jokul/src/components/feedback/questions/ContactQuestion.tsx
- packages/jokul/src/components/flex/Flex.tsx
- packages/jokul/src/components/input-group/SupportLabel.tsx
- packages/jokul/src/components/link-list/LinkList.tsx
- packages/jokul/src/components/menu/MenuItem.tsx
- packages/jokul/src/components/menu/MenuItemCheckbox.tsx
- packages/jokul/src/components/message/DismissButton.tsx
- packages/jokul/src/components/message/Message.tsx
- packages/jokul/src/components/modal/Modal.tsx
- packages/jokul/src/components/pagination/Pagination.tsx
- packages/jokul/src/components/radio-panel/RadioPanel.tsx
- packages/jokul/src/components/select/NativeSelect.tsx
- packages/jokul/src/components/select/Select.tsx
- packages/jokul/src/components/system-message/common/DismissButton.tsx
- packages/jokul/src/components/system-message/common/MessageIcon.tsx
- packages/jokul/src/components/table/ExpandableTableRow.tsx
- packages/jokul/src/components/table/TableHeader.tsx
- packages/jokul/src/components/table/TablePagination.tsx
- packages/jokul/src/components/tag/Tag.tsx
- packages/jokul/src/components/text-input/BaseTextInput.tsx
- packages/jokul/src/components/toast/Toast.tsx
- packages/jokul/src/components/toggle-switch/ToggleSwitch.tsx
- packages/jokul/src/components/tooltip/PopupTip.tsx
Prøvde å sette opp den eslint-regelen men fikk den ikke til å melde fra om at noe var feil og dokumentasjon var fraværende så jeg ga opp.
> fix: remove remaining barrel imports

- packages/core/jkl/_legacy-tokens.scss
- packages/core/jkl/_tokens.scss
- packages/core/src/tokens.ts
- packages/core/styles/_color-tokens.scss
- packages/core/styles/_legacy-tokens.scss
- packages/core/styles/_tokens.scss
- packages/core/tokens.less
- packages/core/tokens/color/color.semantic.tokens.json
- packages/jokul/src/components/select/Select.tsx
- packages/jokul/src/components/select/styles/select.scss
- packages/jokul/src/components/text-input/styles/text-input.scss
- packages/jokul/src/core/jkl/_legacy-tokens.scss
- packages/jokul/src/core/jkl/_tokens.scss
- packages/jokul/src/core/styles/_color-tokens.scss
- packages/jokul/src/core/styles/_legacy-tokens.scss
- packages/jokul/src/core/styles/_tokens.scss
- packages/jokul/src/core/tokens.less
- packages/jokul/src/core/tokens.ts
- packages/jokul/src/core/tokens/color/color.semantic.tokens.json
- packages/select-react/src/Select.tsx
- packages/select/select.scss
- packages/text-input/text-input.scss
> fix: minor color fixes for error state

- README.md
Oppdaterer dokumentasjonen for multi-root workspaces i Visual Studio Code.
> Oppdater dokumentasjon: Multi-root workspaces i VS Code

- packages/jokul/package.json
- packages/jokul/src/components/menu/Menu.tsx
- packages/jokul/src/components/tooltip/Tooltip.tsx
- packages/jokul/src/components/tooltip/TooltipContent.tsx
- packages/jokul/src/components/tooltip/TooltipTrigger.tsx
- packages/jokul/src/components/tooltip/documentation/TooltipExample.tsx
- packages/jokul/src/components/tooltip/styles/tooltip.scss
- packages/tooltip-react/documentation/Example.tsx
- packages/tooltip-react/documentation/TooltipExample.tsx
- packages/tooltip-react/package.json
- packages/tooltip-react/src/Tooltip.tsx
- packages/tooltip-react/src/TooltipContent.tsx
- packages/tooltip-react/src/TooltipTrigger.tsx
- packages/tooltip/tooltip.scss
- pnpm-lock.yaml
Jeg vet at @Saegrov gjerne vil jobbe mer med dette under Jøkuluka, men dette var en stor nok forbedring i seg selv (for lite nok arbeid) til at jeg gjerne tar det inn i mellomtiden 😊
> Gå vekk fra Framer Motion for animasjoner i Tooltip

- packages/jokul/package.json
- packages/jokul/src/components/menu/Menu.tsx
- packages/jokul/vite.build.config.mjs
- pnpm-lock.yaml
Sørg for at riktige avhengigheter følger med når man bruker `@fremtind/jokul`, både i bygg og i test.
closes #4224
> fix: legg til react-dom som dependency og inline react-is

- packages/jokul/package.json
> fix: endret rekkefølge på default i Jokul pakken

- packages/jokul/src/components/feedback/main-question/MainQuestion.tsx
- packages/jokul/src/components/feedback/styles/feedback.scss
> fix: la til flex rundt feedback buttons

- packages/jokul/vite.build.config.mjs
> fix: inline downshift to try to work around module resolution issues

- packages/chip-react/README.md
- packages/chip-react/documentation/Chip.mdx
- packages/chip-react/documentation/ChipExample.tsx
- packages/chip-react/documentation/DevClient.tsx
- packages/chip-react/documentation/DevServer.tsx
- packages/chip-react/documentation/Example.tsx
- packages/chip-react/esbuild.dev.mjs
- packages/chip-react/esbuild.mjs
- packages/chip-react/esbuild.prod.mjs
- packages/chip-react/package.json
- packages/chip-react/src/Chip.test.tsx
- packages/chip-react/src/Chip.tsx
- packages/chip-react/src/index.ts
- packages/chip-react/tsconfig-for-declarations.json
- packages/chip/README.md
- packages/chip/_index.scss
- packages/chip/chip.scss
- packages/chip/gulpfile.js
- packages/chip/package.json
- packages/jokul/package.json
- packages/jokul/src/components/chip/Chip.test.tsx
- packages/jokul/src/components/chip/Chip.tsx
- packages/jokul/src/components/chip/documentation/ChipExample.tsx
- packages/jokul/src/components/chip/documentation/Example.tsx
- packages/jokul/src/components/chip/index.ts
- packages/jokul/src/components/chip/styles/_index.scss
- packages/jokul/src/components/chip/styles/chip.scss
- packages/jokul/src/styles/styles.scss
- pnpm-lock.yaml
- portal/gatsby-browser.tsx
> feat: chips

- packages/jokul/src/hooks/useScreen/useScreen.ts
> fix: en a som ikke skulle være der

- packages/jokul/src/components/system-message/styles/system-message.scss
- packages/jokul/src/core/jkl/_reset.scss
> fix: removes scss warnings about mixins

- .github/workflows/visual_regression_test.yml
> Kjør tester når utils-mappa har endringer

- .github/workflows/clean-cache.yml
Tatt fra https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
> chore: delete branch caches after merge

- .github/workflows/pull_request.yml
La være å lagre cache hvis man ikke bygger pakker
> chore: bedre cache-handling

- packages/accordion/accordion.scss
- packages/button/button.scss
- packages/chip/chip.scss
- packages/combobox/combobox.scss
- packages/datepicker/_calendar.scss
- packages/file-input/_file.scss
- packages/jokul/src/components/accordion/styles/accordion.scss
- packages/jokul/src/components/button/styles/button.scss
- packages/jokul/src/components/chip/styles/chip.scss
- packages/jokul/src/components/combobox/styles/combobox.scss
- packages/jokul/src/components/datepicker/styles/_calendar.scss
- packages/jokul/src/components/file-input/styles/_file.scss
- packages/jokul/src/components/tag/styles/tag.scss
- packages/jokul/src/components/tooltip/styles/tooltip.scss
- packages/jokul/src/core/jkl/_theme.scss
- packages/tag/tag.scss
- packages/tooltip/tooltip.scss
> 4340 revert to old mixins

- packages/core/src/components/Link.tsx
- packages/jokul/src/components/link/Link.tsx
- packages/jokul/src/components/link/documentation/LinkExample.tsx
> fix: lets screenreaders know if links are external

- packages/jokul/src/components/text-input/BaseTextInput.tsx
- packages/jokul/src/components/text-input/documentation/TextInputExample.tsx
- packages/jokul/src/components/text-input/styles/text-input.scss
- packages/text-input-react/MIGRATION.md
- packages/text-input-react/documentation/TextInputExample.tsx
- packages/text-input-react/src/BaseTextInput.tsx
- packages/text-input/text-input.scss
-   [x] Gamle features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
Closes #4301
> 4301 docs textinput

- packages/combobox-react/src/Combobox.tsx
- packages/jokul/src/components/combobox/Combobox.tsx
> fix: toggles open state on arrow button click

- packages/input-group-react/src/InputGroup.test.tsx
- packages/jokul/src/components/input-group/InputGroup.test.tsx
- packages/jokul/src/components/select/Select.test.tsx
- packages/jokul/src/components/tooltip/PopupTip.test.tsx
- packages/jokul/src/components/tooltip/PopupTip.tsx
- packages/jokul/src/components/tooltip/Tooltip.test.tsx
- packages/jokul/src/components/tooltip/Tooltip.tsx
- packages/jokul/src/components/tooltip/TooltipContent.tsx
- packages/jokul/src/components/tooltip/documentation/Example.tsx
- packages/jokul/src/components/tooltip/styles/_index.scss
- packages/jokul/src/components/tooltip/styles/popuptip.scss
- packages/select-react/src/Select.test.tsx
- packages/tooltip-react/src/PopupTip.tsx
- packages/tooltip-react/src/TooltipContent.tsx
> fix: makes sure SR announces popuptip content

- packages/card/card.scss
- packages/jokul/src/components/card/styles/card.scss
> fix: allows content to be interacted with

- packages/accordion-react/src/AccordionItem.tsx
- packages/accordion/accordion.scss
- packages/jokul/src/components/accordion/AccordionItem.tsx
- packages/jokul/src/components/accordion/styles/accordion.scss
> fix: riktig størrelse på pila i AccorionItem

- packages/button-react/documentation/Ghost.tsx
- packages/button-react/documentation/Primary.tsx
- packages/button-react/documentation/Secondary.tsx
- packages/button-react/documentation/Tertiary.tsx
- packages/button-react/documentation/buttons.mdx
- packages/button-react/src/Button.tsx
- packages/jokul/src/components/button/Button.tsx
- packages/jokul/src/components/button/documentation/ButtonExample.tsx
> 4352 accessible names

- packages/expandable-react/documentation/CustomWidgetExample.tsx
- packages/expandable-react/documentation/Expandable.mdx
- packages/expandable-react/package.json
- packages/expandable/expandable.scss
- packages/jokul/src/components/expander/styles/expandable.scss
- pnpm-lock.yaml
> docs: improve expander docs with example

- packages/combobox/combobox.scss
- packages/jokul/src/components/combobox/styles/combobox.scss
- packages/jokul/src/components/select/styles/select.scss
- packages/select/select.scss
> fix: no focus-outline when using mouse navigation

- packages/icon-button/icon-button.scss
- packages/jokul/src/components/icon-button/styles/icon-button.scss
- packages/jokul/src/components/text-input/styles/text-input.scss
- packages/text-input/text-input.scss
> fix: small improvements to forced colors mode

- packages/file-input-react/src/internal/validateFile.test.ts
- packages/file-input-react/src/internal/validateFile.ts
- packages/jokul/src/components/file-input/internal/validateFile.test.ts
- packages/jokul/src/components/file-input/internal/validateFile.ts
> fix: file validation is case insensitive

- .github/ISSUE_TEMPLATE/innspill-komponent.yml
- portal/src/components/SuggestionBlock/SuggestionBlock.tsx
- portal/src/components/SuggestionBlock/index.ts
- portal/src/components/SuggestionBlock/suggestion-block.scss
- portal/src/templates/DocPageLayout.jsx
Gjør det mulig for brukere av portalen til å gi tilbakemeldinger på komponenter.
#4357
> feat: innspill komponent

- .github/CODEOWNERS
Legg til Jøkul-teamet som codeowners for repoet, slik at vi får automatisk assignet reviewers
> chore: legg til Jøkul-teamet som codeowners

- packages/accordion-react/documentation/accordion.mdx
- packages/accordion-react/package.json
- pnpm-lock.yaml
> docs: mark accordion as deprecated

- packages/jokul/src/components/text-input/styles/text-input.scss
- packages/text-input/text-input.scss
> fix: only has focus style with keyboard-nav

- .github/workflows/close-no-repro.yml
> chore: cleans up older non-reprodusable issues

- packages/jokul/src/components/progress-bar/Countdown.test.tsx
- packages/jokul/src/components/progress-bar/documentation/CountdownExample.tsx
- packages/jokul/src/components/progress-bar/documentation/Example.tsx
- packages/progress-bar-react/src/Countdown.test.tsx
Tester for Countdown-komponenten for å sikre at nedtellingen fungerer som forventet.
> test: Countdown

- portal/src/templates/DocPageLayout.jsx
Justerer visningen av "innspill til komponenten" slik at den kun vises for relevante komponenter i portalen.
> Fiks: Innspill til komponent

- .github/workflows/pull_request.yml
> chore: trigger preview workflow on all src changes

- .github/workflows/visual_regression_test.yml
> chore: runs regression tests when tsx files change

- packages/cookie-consent-react/src/CookieConsent.tsx
- packages/file-input-react/documentation/FileInputExample.tsx
- packages/file-input-react/src/internal/Input.tsx
- packages/jokul/src/components/cookie-consent/CookieConsent.tsx
- packages/jokul/src/components/file-input/documentation/FileInputExample.tsx
- packages/jokul/src/components/file-input/internal/Input.tsx
This makes it easier for automatic tests to figure out if they can proceed or need to take action
Closes #4487 
Closes #4490
> Make adjustments for automatic tests

- packages/jokul/MIGRATION.md
- packages/jokul/README.md
> docs: adds a migration guide for jokul

- ny-portal/.env.example
- ny-portal/README.md
Oppdaterer README-filen i den nye portalen for å gi bedre instruksjoner for å komme i gang med lokal utvikling.
closes: #4447
> docs: lag bedre README for lokalt oppsett av ny portal

- packages/jokul/README.md
Liten endring i ordlegging om migrering til monopakke i README
> docs: oppdater info om migrasjon

- packages/jokul/src/components/index.ts
> fix: supports importing autosuggest and file-input from root path

- packages/toggle-switch-react/documentation/ToggleSwitch.mdx
- packages/toggle-switch-react/src/ToggleSlider.tsx
- Bedre merking av React-komponenten som deprecated
- Fjernet henvisninger til ToggleSlider fra portalsiden (bilder av bruk og React API)
> Bedre dokumentasjon av deprecation for ToggleSwitch

- ny-portal/src/app/(frontend)/komponenter/page.tsx
- ny-portal/src/payload-types.ts
- Oversiktssiden for komponenter har nå en klikkbar liste som tar deg rett til riktig komponent.
- Payload-typene er oppdatert.
Closes: #4498
> feat: side med oversikt over komponenter

- .prettierignore
- ny-portal/.eslintignore
- ny-portal/package.json
- ny-portal/src/components/rich-text/RichText.tsx
- pnpm-lock.yaml
Prøver å kjøre `pnpm build` i ny-portal mappa ifm endringer i Dockerfile men det feiler.
> docs: fix pnpm build of ny-portal

- Dockerfile
Starter ikke pga manglende env-variabler men den bruker i hvert fall ny directory-struktur og en ny nok versjon av node
> chore: update dockerfile for new portal

- packages/core/src/tailwind/tailwindPreset.ts
- packages/jokul/src/tailwind/tailwindPreset.ts
Legger tilbake innebygde presets fra Tailwind, som sørger for at stilene våre kan brukes ordentlig
> fix: sørg for at custom stiler funker med tailwind-preset

- packages/jokul/src/components/cookie-consent/styles/_index.scss
> fix: makes cookie-consent automatically pull in modal SCSS

- portal/src/pages/beta.tsx
> docs: remove redirect to old new portal

- .storybook/main.ts
- package.json
- La være å åpne nytt nettleservindu hver gang du starter Storybook lokalt
- Bruk moderne Sass-loader for å unngå forstyrrende advarsler i terminalen
> Quality of life-fixes for Storybook

- ny-portal/src/components/rich-text/RichText.tsx
> chore: fix rich-text rendering of examples

- packages/jokul/src/components/pagination/Pagination.tsx
> feat: pagination will use className if provided

- packages/jokul/src/components/pagination/stories/Pagination.stories.tsx
> feat: la til story for pagination

- ny-portal/package.json
- ny-portal/src/app/(frontend)/komponenter/[slug]/page.tsx
- ny-portal/src/app/api/component-folders/route.ts
- ny-portal/src/sanity/components/ComponentFolderInput.tsx
- ny-portal/src/sanity/extract.json
- ny-portal/src/sanity/schemas/componentPage.ts
- ny-portal/src/sanity/types.ts
- pnpm-lock.yaml
Implementert støtte for å vise prop-dokumentasjon per komponent.
ISSUES CLOSED: #4598
> Visning av prop-dokumentasjon for komponenter

- packages/jokul/src/components/progress-bar/stories/ProgressBar.stories.tsx
> feat: la til story for progressbar

- packages/jokul/src/components/text-input/stories/BaseTextInput.stories.tsx
- packages/jokul/src/components/text-input/stories/TextInput.stories.tsx
Har lagt dem i egne mapper for skjemaelementer, likte det ganske godt, men vet ikke med dere?
> docs: lagt til stories for textinput

- ny-portal/src/app/api/code-example-files/route.ts
- ny-portal/src/components/portable-text/PortableText.tsx
- ny-portal/src/components/portable-text/code-example/CodeExample.tsx
- ny-portal/src/components/portable-text/code-example/LivePreview.tsx
- ny-portal/src/components/portable-text/code-example/index.ts
- ny-portal/src/components/portable-text/props-documentation/PropsDocumentation.tsx
- ny-portal/src/sanity/components/CodeExampleInput.tsx
- ny-portal/src/sanity/extract.json
- ny-portal/src/sanity/schemas/codeExample.ts
- ny-portal/src/sanity/schemas/componentPage.ts
- ny-portal/src/sanity/schemas/componentProps.ts
- ny-portal/src/sanity/schemas/index.ts
- ny-portal/src/sanity/types.ts
Ny blokk-type for kodeeksempler i Sanity.
PS: Branchen er opprettet fra branch #4631
> 4597 code example block

- .github/workflows/build-and-deploy-portal.yml
Setter opp en bygg- og deploy-workflow for Portalen. Kjører ved push til main og gjør et GitHub API-kall for å trigge en workflow i repo [jokul-portal-deploy](https://github.com/fremtind/jokul-portal-deploy)
ISSUES CLOSED: #4645
> Opprett bygg- og deploy-workflow for Portalen

- .github/workflows/build-and-deploy-portal.yml
Lagt til -d med ref-property i kallet til GitHub API for å starte en workflow dispatch
> Oppdater build-and-deploy-portal.yml

- .github/workflows/visual_regression_test.yml
- .github/workflows/weekly.yml
- package.json
- pnpm-lock.yaml
Oppdaterer Playwright, og sørger for riktig uthentig av Playwright-versjon i test-action.
> Oppdater Playwright

- ny-portal/package.json
- pnpm-lock.yaml
Installerer manglende dompurify dependency i ny-portal
> fix: installer manglende dompurify dependency

- ny-portal/src/app/(frontend)/komponenter/page.module.scss
- ny-portal/src/app/(frontend)/komponenter/page.tsx
- ny-portal/src/sanity/extract.json
- ny-portal/src/sanity/queries/component.ts
- ny-portal/src/sanity/schemas/component.ts
- ny-portal/src/sanity/types.ts
> docs: sett opp oversiktsiden for komponenter

- .github/ISSUE_TEMPLATE/dokumentasjon
> Create dokumentasjon template

- ny-portal/src/app/(frontend)/komponenter/[slug]/component.module.scss
- ny-portal/src/app/(frontend)/komponenter/[slug]/component.tsx
- ny-portal/src/app/(frontend)/komponenter/komponenter.module.scss
- ny-portal/src/app/(frontend)/komponenter/navigation/NavigationMenu.scss
- ny-portal/src/app/(frontend)/layout.module.scss
- ny-portal/src/components/portable-text/storybook-story/storybook.module.scss
> docs: legg til footer i artikler

- ny-portal/package.json
- ny-portal/sanity.config.ts
- pnpm-lock.yaml
> feat: endre språk i sanity studio til norsk

- ny-portal/public/component_placeholder_dark.svg
- ny-portal/public/component_placeholder_light.svg
- ny-portal/src/app/(frontend)/komponenter/ComponentCard.tsx
- ny-portal/src/app/(frontend)/komponenter/[slug]/component.tsx
- ny-portal/src/app/(frontend)/komponenter/komponenter.module.scss
- ny-portal/src/app/(frontend)/komponenter/page.tsx
- ny-portal/src/sanity/extract.json
- ny-portal/src/sanity/queries/component.ts
- ny-portal/src/sanity/schemas/component.ts
- ny-portal/src/sanity/types.ts
- pnpm-lock.yaml
Legger til mulighet for å hente thhumbnails for komponentene fra Figma via deres API.
closes #4709
> feat: legg til mulighet for å hente thumbnails fra Figma

- .github/pull_request_template.md
- CONTRIBUTING.md
Endringer i PR-template og contributing fila for å henvise til nye måter å bidra på
> docs: endret hvordan bidra til jøkul 2025

- packages/jokul/src/components/logo/stories/Logo.stories.tsx
- packages/jokul/src/components/logo/stories/LogoStamp.stories.tsx
1.
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell utforming](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), …
> docs: la til story for logo og logostamp

- packages/jokul/src/components/text-area/stories/TextArea.stories.tsx
1.
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell utforming](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), …
> docs: la til story for textArea

- Dockerfile
- ny-portal/Dockerfile
1. Konfigurer Dockerfile for å håndtere nødvendige argumenter og hemmeligheter
> chore: Konfigurer Dockerfile

- ny-portal/src/app/(frontend)/komponenter/ComponentCard.tsx
1. Legg til bedre feilhådtering ved henting av thumbnails fra FIgma
> fix: håndter feil ved lasting av thumbnails fra Figma

- ny-portal/src/sanity/extract.json
- ny-portal/src/sanity/schemas/component.ts
- ny-portal/src/sanity/schemas/index.ts
- ny-portal/src/sanity/schemas/kortFortalt.ts
- ny-portal/src/sanity/types.ts
> feat: legg til kort fortalt i sanity

- Dockerfile
1. Endre sti for import av Docker-image for bygg av portalen
> chore: bruk riktig adresse for base docker image for portalen

- ny-portal/src/app/(frontend)/komponenter/[slug]/components/ComponentHeaderLink.tsx
1. la til target="_blank" så lenke åpnes i ny fane
> fix: la disse lenkene åpen i ny fane

- ny-portal/src/app/(frontend)/komponenter/ComponentCard.tsx
- ny-portal/src/app/(frontend)/komponenter/ComponentGallery.tsx
- ny-portal/src/app/(frontend)/komponenter/komponenter.module.scss
- ny-portal/src/app/(frontend)/komponenter/page.tsx
- ny-portal/src/sanity/extract.json
- ny-portal/src/sanity/queries/component.ts
- ny-portal/src/sanity/types.ts
ISSUES CLOSED: #4747
1. Legger tilrette for å kunne switche mellom list og grid view på komponentoversikt siden
> feat: legg tilrette for liste vs galleri view på komponentoversikt

- ny-portal/src/app/(frontend)/global.scss
- ny-portal/src/app/(frontend)/komponenter/[slug]/component.module.scss
- ny-portal/src/app/(frontend)/komponenter/[slug]/page.tsx
- ny-portal/src/components/portable-text/PortableText.tsx
- ny-portal/src/components/portable-text/kort-fortalt/KortFortalt.tsx
- ny-portal/src/components/portable-text/kort-fortalt/kortFortalt.module.scss
- ny-portal/src/components/site-header/SiteHeader.module.scss
- ny-portal/src/sanity/queries/component.ts
1. Viser nå kort fortalt i løpende tekst på siden
> Kort fortalt i portalen

- ny-portal/src/app/(frontend)/global.scss
- ny-portal/src/app/(frontend)/komponenter/ComponentCard.tsx
- ny-portal/src/app/(frontend)/komponenter/ComponentThumbnail.tsx
- ny-portal/src/app/(frontend)/komponenter/komponenter.module.scss
1. Bruk Card-komponenten for å vise thumbnails av komponenter i portalen
closes #4781
> Bruk Card-komponenten for å vise thumbnails av komponenter i portalen

- packages/jokul/src/hooks/useLocalStorage/useLocalStorage.ts
- packages/react-hooks/src/useLocalStorage/useLocalStorage.ts
1. Lar bruker oppdatere verdien i useLocalStorage basert på gammel verdi, på samme måte som man gjør med setState
> feat: la useLocalStorage ta inn setStateAction

- packages/datepicker-react/package.json
- packages/datepicker-react/src/internal/Calendar.tsx
- packages/jokul/src/components/datepicker/internal/Calendar.tsx
- pnpm-lock.yaml
> feat: byttet ut buttons i calendar navigation til ghostbuttons

- ny-portal/src/sanity/extract.json
- ny-portal/src/sanity/schemas/blogPost.ts
- ny-portal/src/sanity/schemas/index.ts
- ny-portal/src/sanity/types.ts
Legger til en generell dokumenttype. 
_Flaut hvor lang tid det tok meg å skjønne at det også bare er en schemaType på samme nivå som andre blocks_
> feat: ny generell dokumenttype i sanity

- packages/jokul/src/components/select/stories/select.stories.tsx
ISSUES CLOSED: #4861
1. Fikser storybook story for Select komponenten
> docs: fiks storybook story for select komponent

- ny-portal/src/app/(frontend)/blog/[slug]/blogpost.module.scss
- ny-portal/src/app/(frontend)/blog/[slug]/components/BlogHeader.tsx
- ny-portal/src/app/(frontend)/blog/[slug]/page.tsx
- ny-portal/src/components/portable-text/PortableText.tsx
- ny-portal/src/components/portable-text/link-card/LinkCard.tsx
- ny-portal/src/components/portable-text/link-card/linkCard.module.scss
- ny-portal/src/components/site-header/SiteHeader.module.scss
- ny-portal/src/components/site-header/menu/MenuItemList.tsx
- ny-portal/src/sanity/extract.json
- ny-portal/src/sanity/queries/blog.ts
- ny-portal/src/sanity/schemas/blogPost.ts
- ny-portal/src/sanity/schemas/index.ts
- ny-portal/src/sanity/schemas/linkCard.ts
- ny-portal/src/sanity/types.ts
- packages/jokul/src/components/table/stories/table.stories.tsx
> feat: satt opp midlertidig bloggpost-side

- ny-portal/src/sanity/schemas/kortFortalt.ts
ISSUES CLOSED: #4864
1. Fikser preview i Sanity hvor mangel på ikke bruk punkt gjorde at teksten ikke ble vist
> fix: fiks sanity preview av kort fortalt

- ny-portal/src/sanity/schemas/component.ts
ISSUES CLOSED: #4084
1. Legger til mulighet til å skrive stikkord til hver komponent, som senere kan bli brukt til søk eller lignende
> feat: legg til mulighet for å angi stikkord til komponenter

- packages/button-react/src/Button.tsx
- packages/button/button.scss
1. Fjerner GUI-bug og forenkler button
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell utforming](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
> Kanskje WIP: Button-safari-fix-pre-1-0

- portal/src/app/(frontend)/komponenter/komponenter.module.scss
ISSUES CLOSED: #4912
1. Flytter container ett nivå opp, som har samme bredde som under-containeren
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design)
> fix: fikser container query ved å flytte container declaration

- portal/src/app/(frontend)/blog/[slug]/page.tsx
- portal/src/app/(frontend)/komponenter/[slug]/page.tsx
- portal/src/components/PageFooter.tsx
1. Lagt til footer på bloggposter
> feat: footer med innspill-lenke på blogg

- portal/src/app/(frontend)/blog/ArticleCard.tsx
- portal/src/app/(frontend)/blog/blog.module.scss
- portal/src/app/(frontend)/blog/page.tsx
- portal/src/components/site-header/SiteHeader.module.scss
- portal/src/components/site-header/menu/MenuItemList.tsx
- portal/src/sanity/extract.json
- portal/src/sanity/queries/blog.ts
- portal/src/sanity/types.ts
1. "Kom i gang" peker alltid på riktig side
2. Nytt punkt "Artikler" i hovedmenyen som peker på…
3. …ny side med oversikt over artikler/bloggposter
Det ligger enkle skisser [i Figma](https://www.figma.com/design/X3FGhswCcw75OOddlS4oH1/Innhold?node-id=3398-13476&p=f&t=CD5aWtJxhzywrqlV-11), som noen med mer peil enn meg kan jobbe videre på
> Legg til visning av artikler/bloggposter i portalen

- .storybook/preview.tsx
- packages/jokul/src/components/file-input/stories/File.stories.tsx
- packages/jokul/src/components/file-input/stories/FileInput.stories.tsx
- packages/jokul/src/components/file-input/styles/_index.scss
1. lagt til mer info i stories
2. lagt til mulighet for opplasting i fileinput
> docs: endret file stories for å gjøre de mer complete

- portal/src/sanity/extract.json
- portal/src/sanity/schemas/blogPost.ts
- portal/src/sanity/types.ts
1. Gjør det mulig å vise kodeblokker i blogposts
ISSUES CLOSED: #4965
> Legg til støtte for kodeblokk i blogpost

- portal/src/components/BetaTag.tsx
- portal/src/components/site-header/SiteHeader.tsx
1. Legger til en "Beta"-tag i portalen for å indikere at funksjonaliteten fortsatt er under utvikling og kan endres.
ISSUES CLOSED: #4959 
> Legg til beta status for portalen

- .changeset/itchy-pianos-relax.md
- portal/sanity.config.ts
- portal/src/app/(frontend)/blog/[slug]/page.tsx
- portal/src/app/(frontend)/blog/page.tsx
- portal/src/app/(frontend)/komponenter/ComponentCard.tsx
- portal/src/app/(frontend)/komponenter/[slug]/page.tsx
- portal/src/app/(frontend)/komponenter/layout.tsx
- portal/src/app/(frontend)/komponenter/page.tsx
- portal/src/app/(frontend)/layout.tsx
- portal/src/app/api/draft-mode/disable/route.ts
- portal/src/app/api/draft-mode/enable/route.ts
- portal/src/components/DisableDraftMode.tsx
- portal/src/components/site-header/menu/MenuItemList.tsx
- portal/src/sanity/client.ts
- portal/src/sanity/env.ts
- portal/src/sanity/lib/client.ts
- portal/src/sanity/lib/live.ts
- portal/src/sanity/lib/token.ts
1. Legger til mulighet for live forhåndsvisning av innhold i Jøkul-portalen under redigering.
> feat: legg til live preview i Sanity Studio

- .changeset/quiet-plums-drop.md
- packages/jokul/src/components/chip/styles/chip.scss
> 5045 chip forced colors

- .changeset/full-plants-walk.md
- packages/jokul/src/components/menu/styles/menu.scss
> fix: make sure menu has a visible border in forced colors mode

- .changeset/clear-bars-enjoy.md
- packages/jokul/src/components/popover/styles/popover.scss
> Add dark box shadow for popover in dark mode

- .github/workflows/pull_request.yml
1. Prøver å fikse pull-request.yml
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell utforming](https://jokul.fremtind.no/universell-utforming/testguide) …
> pull-request-feil

- portal/src/app/(frontend)/blog/[slug]/page.tsx
- portal/src/app/(frontend)/blog/page.tsx
- portal/src/app/(frontend)/komponenter/ComponentCard.tsx
- portal/src/app/(frontend)/komponenter/[slug]/page.tsx
- portal/src/app/(frontend)/komponenter/page.tsx
Legger til request tags på spørringene våre mot Sanity, for bedre å kunne spore bruken vår av APIet.
> fix: legg til request tags for spørringer mot Sanity

- portal/src/components/portable-text/code-block/CodeBlock.tsx
- portal/src/components/portable-text/code-block/code-block.module.scss
> legg kopier-knapp nederst i code block som en midlertidig løsning

- Dockerfile
- portal/.env.example
- portal/sanity.config.ts
- portal/src/app/studio/Studio.tsx
- portal/src/app/studio/[[...index]]/page.tsx
- portal/src/sanity/env.ts
Oppdater oppsettet av Sanity til å samsvare med best practice. NB! Krever at du endrer navnet på to miljøvariabler lokalt. Se .env.example for hvilke variabler som må defineres.
> Moderniser og forenkle oppsett av sanity

- portal/src/app/(frontend)/global.scss
- portal/src/app/(frontend)/komponenter/[slug]/component.module.scss
- portal/src/app/(frontend)/komponenter/[slug]/components/ComponentConsiderations.tsx
- portal/src/app/(frontend)/komponenter/[slug]/page.tsx
Selvforklarende?
[Fulgt denne skissa](https://www.figma.com/design/X3FGhswCcw75OOddlS4oH1/Innhold?node-id=3458-13237&m=dev)
> FEAT: legge til ting å tenke på i portalen

- .changeset/green-roses-look.md
- packages/jokul/package.json
- packages/jokul/src/components/segmented-control/SegmentedControl.tsx
- packages/jokul/src/components/segmented-control/SegmentedControlButton.tsx
- packages/jokul/src/components/segmented-control/index.ts
- packages/jokul/src/components/segmented-control/stories/segmentedControl.stories.tsx
- packages/jokul/src/components/segmented-control/stories/segmentedControlButton.stories.tsx
- packages/jokul/src/components/segmented-control/styles/_index.scss
- packages/jokul/src/components/segmented-control/styles/segmented-control.scss
- packages/jokul/src/components/segmented-control/types.ts
- packages/jokul/src/styles/styles.scss
1. Hadde ikke lagd index.ts så Segmented Control ble ikke gitt ut riktig
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [universell utforming](https://jokul.fremtind.no/universell-utforming/testguide) …
> docs(changeset): Eksporter Segmented Control riktig

- portal/src/layout/Layout.tsx
- portal/src/layout/header/Header.tsx
Legger til banner i den gamle portalen som informerer om og peker til den nye
-   Closes #5173
> feat: legg til banner som peker til ny portal

- packages/jokul/src/components/checkbox-panel/stories/CheckboxPanel.stories.tsx
- packages/jokul/src/components/radio-panel/stories/RadioPanel.stories.tsx
- Oppdatert Radio og Checkbox-panel stories
-   Closes #5204
> Oppdatert radio og checkbox-panel stories

- packages/jokul/src/components/expander/stories/Expander.stories.tsx
- portal/src/components/header/header.module.scss
- Oppdater Expander story til å funke enkelstående
-   Closes #5219
> Oppdater Expander story

- packages/jokul/src/components/help/styles/help.scss
- pnpm-lock.yaml
- portal/package.json
- portal/src/app/(frontend)/global.scss
- portal/src/app/(frontend)/komponenter/[slug]/component.module.scss
- portal/src/app/(frontend)/komponenter/[slug]/components/ComponentHeader.tsx
- portal/src/app/(frontend)/komponenter/[slug]/components/componentHeader.module.scss
- portal/src/app/(frontend)/komponenter/[slug]/page.tsx
- portal/src/app/(frontend)/komponenter/komponenter.module.scss
- portal/src/app/(frontend)/komponenter/layout.tsx
- portal/src/components/component-card/component-card.module.scss
- portal/src/components/header/header.module.scss
- portal/src/components/portable-text/PortableText.tsx
- portal/src/components/portable-text/kort-fortalt/KortFortalt.tsx
- Fjernet ubrukt kode
- Forbedret layout-håndtering i portalen
- Løst advarsel knyttet til nested rule i SCSS
-   Closes #5232
> Forbedre layout i portalen

- .changeset/full-places-count.md
- packages/jokul/src/components/checkbox-panel/styles/checkbox-panel.scss
- packages/jokul/src/components/checkbox/styles/checkbox.scss
- packages/jokul/src/components/countdown/styles/countdown.scss
- packages/jokul/src/components/description-list/styles/description-list.scss
- packages/jokul/src/components/icon-button/styles/icon-button.scss
- packages/jokul/src/components/icon/styles/icon.scss
- packages/jokul/src/components/image/styles/image.scss
- packages/jokul/src/components/list/styles/list.scss
- packages/jokul/src/components/loader/styles/loader.scss
- packages/jokul/src/components/loader/styles/skeleton-loader.scss
- packages/jokul/src/components/logo/styles/logo.scss
- packages/jokul/src/components/menu/styles/_menu-divider.scss
- packages/jokul/src/components/menu/styles/_menu-item.scss
- packages/jokul/src/components/menu/styles/menu.scss
- packages/jokul/src/components/nav-link/styles/nav-link.scss
- packages/jokul/src/components/popover/styles/popover.scss
- packages/jokul/src/components/progress-bar/styles/progress-bar.scss
- packages/jokul/src/components/radio-panel/styles/radio-panel.scss
- packages/jokul/src/components/summary-table/styles/summary-table.scss
- packages/jokul/src/components/tabs/styles/tabs.scss
Plasserer stilene til alle komponenter som ikke er avhengige av andre komponenters stiler inne i CSS-laget `jokul.components`.
Må fortsatt gjøres for resten av komponentene, men startet med de som ikke har noen avhengigheter for å unngå uænskede overstyringer el. underveis.
> Legg komponentstiler i CSS layers (kun noen komponenter)
